# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas_web', '0002_load_initial_licencas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencaweb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='licencaweb',
            table='licencas_web',
        ),
    ]
