# Generated by Django 2.2.28 on 2026-02-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
        ('licencas_web', '0003_auto_20260114_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencaweb',
            name='plano',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenca_web', to='planos.Plano'),
        ),
    ]
