# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoSdk',
            fields=[
                ('sdk_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdk_empr', models.IntegerField(default=1, verbose_name='Empresa')),
                ('sdk_fili', models.IntegerField(default=1, verbose_name='Filial')),
                ('sdk_pedi', models.IntegerField()),
                ('sdk_tipo', models.CharField(choices=[('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('sdk_valo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sdk_parc', models.IntegerField(default=1)),
                ('sdk_stat', models.CharField(default='pendente', max_length=20)),
                ('sdk_seri', models.CharField(default='SDK', max_length=20)),
                ('sdk_data', models.DateTimeField(auto_now_add=True)),
                ('sdk_resp', models.CharField(blank=True, max_length=255, null=True)),
                ('sdk_erro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recebimentosdk',
                'ordering': ['-sdk_data'],
                'unique_together': {('sdk_empr', 'sdk_fili', 'sdk_pedi')},
            },
        ),
        migrations.CreateModel(
            name='TituloReceberSdk',
            fields=[
                ('titu_id', models.AutoField(primary_key=True, serialize=False)),
                ('titu_empr', models.IntegerField(default=1, verbose_name='Empresa')),
                ('titu_fili', models.IntegerField(default=1, verbose_name='Filial')),
                ('titu_nume', models.IntegerField()),
                ('titu_valo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titu_seri', models.CharField(default='SDK', max_length=20)),
                ('titu_data', models.DateField()),
                ('titu_stat', models.CharField(default='previsto', max_length=20)),
                ('titu_rece', models.ForeignKey(db_column='titu_rece', on_delete=django.db.models.deletion.CASCADE, to='Sdk_recebimentos.RecebimentoSdk')),
            ],
            options={
                'db_table': 'titulosrecebersdk',
                'ordering': ['titu_data'],
                'unique_together': {('titu_empr', 'titu_fili', 'titu_rece', 'titu_nume')},
            },
        ),
    ]
