
from Licencas.models import Empresas, Filiais
from django.db import models

class NotaFiscalEntrada(models.Model):
    codigo_uf_emitente = models.IntegerField(db_column='b02_cuf_emi', blank=True, null=True)
    codigo_numerico_chave = models.IntegerField(db_column='b03_cnf', blank=True, null=True)
    natureza_operacao = models.CharField(db_column='b04_natop', max_length=60, blank=True, null=True)
    modelo = models.CharField(db_column='b06_mod', max_length=2, blank=True, null=True)
    serie = models.CharField(db_column='b07_serie', max_length=3, blank=True, null=True)
    numero_nota_fiscal = models.IntegerField(db_column='b08_nnf', blank=True, null=True)
    data_emissao = models.DateField(db_column='b09_demi', blank=True, null=True)
    data_saida_entrada = models.DateField(db_column='b10_dsaient', blank=True, null=True)
    hora_saida_entrada = models.TimeField(db_column='b10a_hsaient', blank=True, null=True)
    tipo_operacao = models.IntegerField(db_column='b11_tpnf', blank=True, null=True)
    emitente_cnpj = models.CharField(db_column='c02_cnpj', max_length=14, blank=True, null=True)
    emitente_cpf = models.CharField(db_column='c02a_cpf', max_length=11, blank=True, null=True)
    emitente_razao_social = models.CharField(db_column='c03_xnome', max_length=60, blank=True, null=True)
    emitente_nome_fantasia = models.CharField(db_column='c04_xfant', max_length=60, blank=True, null=True)
    emitente_logradouro = models.CharField(db_column='c06_xlgr', max_length=60, blank=True, null=True)
    emitente_numero = models.CharField(db_column='c07_nro', max_length=60, blank=True, null=True)
    emitente_complemento = models.CharField(db_column='c08_xcpl', max_length=60, blank=True, null=True)
    emitente_bairro = models.CharField(db_column='c09_xbairro', max_length=60, blank=True, null=True)
    emitente_codigo_municipio = models.IntegerField(db_column='c10_cmun', blank=True, null=True)
    emitente_nome_municipio = models.CharField(db_column='c11_xmun', max_length=60, blank=True, null=True)
    emitente_uf = models.CharField(db_column='c12_uf', max_length=2, blank=True, null=True)
    emitente_cep = models.IntegerField(db_column='c13_cep', blank=True, null=True)
    emitente_codigo_pais = models.IntegerField(db_column='c14_cpais', blank=True, null=True)
    emitente_nome_pais = models.CharField(db_column='c15_xpais', max_length=60, blank=True, null=True)
    emitente_fone = models.CharField(db_column='c16_fone', max_length=15, blank=True, null=True)
    emitente_ie = models.CharField(db_column='c17_ie', max_length=14, blank=True, null=True)
    emitente_ie_st = models.CharField(db_column='c18_iest', max_length=14, blank=True, null=True)
    emitente_im = models.CharField(db_column='c19_im', max_length=15, blank=True, null=True)
    emitente_cnae = models.CharField(db_column='c20_cnae', max_length=7, blank=True, null=True)
    emitente_crt = models.IntegerField(db_column='c21_crt', blank=True, null=True)
    destinatario_cnpj = models.CharField(db_column='e02_cnpj', max_length=14, blank=True, null=True)
    destinatario_cpf = models.CharField(db_column='e03_cpf', max_length=11, blank=True, null=True)
    destinatario_razao_social = models.CharField(db_column='e04_xnome', max_length=60, blank=True, null=True)
    destinatario_logradouro = models.CharField(db_column='e06_xlgr', max_length=60, blank=True, null=True)
    destinatario_numero = models.CharField(db_column='e07_nro', max_length=60, blank=True, null=True)
    destinatario_complemento = models.CharField(db_column='e08_xcpl', max_length=60, blank=True, null=True)
    destinatario_bairro = models.CharField(db_column='e09_xbairro', max_length=60, blank=True, null=True)
    destinatario_codigo_municipio = models.IntegerField(db_column='e10_cmun', blank=True, null=True)
    destinatario_nome_municipio = models.CharField(db_column='e11_xmun', max_length=60, blank=True, null=True)
    destinatario_uf = models.CharField(db_column='e12_uf', max_length=2, blank=True, null=True)
    destinatario_cep = models.IntegerField(db_column='e13_cep', blank=True, null=True)
    destinatario_codigo_pais = models.IntegerField(db_column='e14_cpais', blank=True, null=True)
    destinatario_nome_pais = models.CharField(db_column='e15_xpais', max_length=60, blank=True, null=True)
    destinatario_fone = models.CharField(db_column='e16_fone', max_length=15, blank=True, null=True)
    destinatario_ie = models.CharField(db_column='e17_ie', max_length=14, blank=True, null=True)
    destinatario_isuf = models.CharField(db_column='e18_isuf', max_length=9, blank=True, null=True)
    destinatario_email = models.CharField(db_column='e19_email', max_length=60, blank=True, null=True)
    valor_total_produtos = models.DecimalField(db_column='w07_vprod_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_nota = models.DecimalField(db_column='w16_vnf_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_desconto = models.DecimalField(db_column='w10_vdesc_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_frete = models.DecimalField(db_column='w08_vfret_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_seguro = models.DecimalField(db_column='w09_vseg_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_icms = models.DecimalField(db_column='w04_vicms_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_ipi = models.DecimalField(db_column='w12_vipi_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_pis = models.DecimalField(db_column='w13_vpis_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_cofins = models.DecimalField(db_column='w14_vcofins_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    valor_total_outras_despesas = models.DecimalField(db_column='w15_voutro_tota', max_digits=15, decimal_places=2, blank=True, null=True)
    modalidade_frete = models.IntegerField(db_column='x02_modfrete', blank=True, null=True)
    transportador_cnpj = models.CharField(db_column='x04_cnpj_transp', max_length=14, blank=True, null=True)
    transportador_cpf = models.CharField(db_column='x05_cpf_transp', max_length=11, blank=True, null=True)
    transportador_razao_social = models.CharField(db_column='x06_xnome_transp', max_length=60, blank=True, null=True)
    transportador_ie = models.CharField(db_column='x07_ie_transp', max_length=14, blank=True, null=True)
    transportador_endereco = models.CharField(db_column='x08_xender_transp', max_length=60, blank=True, null=True)
    transportador_nome_municipio = models.CharField(db_column='x09_xmun_transp', max_length=60, blank=True, null=True)
    transportador_uf = models.CharField(db_column='x10_uf_transp', max_length=2, blank=True, null=True)
    veiculo_placa = models.CharField(db_column='x19_placa_veic', max_length=8, blank=True, null=True)
    veiculo_uf = models.CharField(db_column='x20_uf_veic', max_length=2, blank=True, null=True)
    empresa = models.IntegerField(blank=True, null=True)
    filial = models.IntegerField(blank=True, null=True)
    cliente = models.IntegerField(blank=True, null=True)
    xml_nfe = models.TextField(blank=True, null=True)
    protocolo_nfe = models.CharField(db_column='prot_nfe', max_length=50, blank=True, null=True)
    status_nfe = models.IntegerField(blank=True, null=True)
    xml_cancelamento = models.TextField(db_column='xml_canc', blank=True, null=True)
    protocolo_cancelamento = models.CharField(db_column='prot_canc', max_length=50, blank=True, null=True)
    cancelada = models.BooleanField(blank=True, null=True)
    status_cancelamento = models.IntegerField(db_column='status_canc', blank=True, null=True)
    xml_inutilizacao = models.TextField(db_column='xml_inut', blank=True, null=True)
    inutilizada = models.BooleanField(blank=True, null=True)
    status_inutilizacao = models.IntegerField(db_column='status_inut', blank=True, null=True)
    denegada = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'nfev'


class Nfev(models.Model):
    a02_versao = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    a03_id = models.CharField(max_length=47, blank=True, null=True)
    b02_cuf_emi = models.IntegerField(blank=True, null=True)
    b03_cnf = models.IntegerField(blank=True, null=True)
    b04_natop = models.CharField(max_length=60, blank=True, null=True)
    b05_indpag = models.IntegerField(blank=True, null=True)
    b06_mod = models.CharField(max_length=2, blank=True, null=True)
    b07_serie = models.CharField(max_length=3, blank=True, null=True)
    b08_nnf = models.IntegerField(blank=True, null=True)
    b09_demi = models.DateField(blank=True, null=True)
    b10_dsaient = models.DateField(blank=True, null=True)
    b10a_hsaient = models.TimeField(blank=True, null=True)
    b11_tpnf = models.IntegerField(blank=True, null=True)
    b12_cmunfg = models.IntegerField(blank=True, null=True)
    b21_tplmp = models.IntegerField(blank=True, null=True)
    b22_tpemis = models.IntegerField(blank=True, null=True)
    b23_cdv = models.IntegerField(blank=True, null=True)
    b24_tpamb = models.IntegerField(blank=True, null=True)
    b25_finnfe = models.IntegerField(blank=True, null=True)
    b26_procemi = models.IntegerField(blank=True, null=True)
    b27_verproc = models.CharField(max_length=20, blank=True, null=True)
    b28_dhcont = models.DateField(blank=True, null=True)
    b29_xjust = models.TextField(blank=True, null=True)
    c02_cnpj = models.CharField(max_length=14, blank=True, null=True)
    c02a_cpf = models.CharField(max_length=11, blank=True, null=True)
    c03_xnome = models.CharField(max_length=60, blank=True, null=True)
    c04_xfant = models.CharField(max_length=60, blank=True, null=True)
    c06_xlgr = models.CharField(max_length=60, blank=True, null=True)
    c07_nro = models.CharField(max_length=60, blank=True, null=True)
    c08_xcpl = models.CharField(max_length=60, blank=True, null=True)
    c09_xbairro = models.CharField(max_length=60, blank=True, null=True)
    c10_cmun = models.IntegerField(blank=True, null=True)
    c11_xmun = models.CharField(max_length=60, blank=True, null=True)
    c12_uf = models.CharField(max_length=2, blank=True, null=True)
    c13_cep = models.IntegerField(blank=True, null=True)
    c14_cpais = models.IntegerField(blank=True, null=True)
    c15_xpais = models.CharField(max_length=60, blank=True, null=True)
    c16_fone = models.CharField(max_length=15, blank=True, null=True)
    c17_ie = models.CharField(max_length=14, blank=True, null=True)
    c18_iest = models.CharField(max_length=14, blank=True, null=True)
    c19_im = models.CharField(max_length=15, blank=True, null=True)
    c20_cnae = models.CharField(max_length=7, blank=True, null=True)
    c21_crt = models.IntegerField(blank=True, null=True)
    e02_cnpj = models.CharField(max_length=14, blank=True, null=True)
    e03_cpf = models.CharField(max_length=11, blank=True, null=True)
    e04_xnome = models.CharField(max_length=60, blank=True, null=True)
    e06_xlgr = models.CharField(max_length=60, blank=True, null=True)
    e07_nro = models.CharField(max_length=60, blank=True, null=True)
    e08_xcpl = models.CharField(max_length=60, blank=True, null=True)
    e09_xbairro = models.CharField(max_length=60, blank=True, null=True)
    e10_cmun = models.IntegerField(blank=True, null=True)
    e11_xmun = models.CharField(max_length=60, blank=True, null=True)
    e12_uf = models.CharField(max_length=2, blank=True, null=True)
    e13_cep = models.IntegerField(blank=True, null=True)
    e14_cpais = models.IntegerField(blank=True, null=True)
    e15_xpais = models.CharField(max_length=60, blank=True, null=True)
    e16_fone = models.CharField(max_length=15, blank=True, null=True)
    e17_ie = models.CharField(max_length=14, blank=True, null=True)
    e18_isuf = models.CharField(max_length=9, blank=True, null=True)
    e19_email = models.CharField(max_length=60, blank=True, null=True)
    f02_cnpj = models.CharField(max_length=14, blank=True, null=True)
    f02a_cpf = models.CharField(max_length=11, blank=True, null=True)
    f03_xlgr = models.CharField(max_length=60, blank=True, null=True)
    f04_nro = models.CharField(max_length=60, blank=True, null=True)
    f05_xcpl = models.CharField(max_length=60, blank=True, null=True)
    f06_xbairro = models.CharField(max_length=60, blank=True, null=True)
    f07_cmun = models.IntegerField(blank=True, null=True)
    f08_xmun = models.CharField(max_length=60, blank=True, null=True)
    f09_uf = models.CharField(max_length=2, blank=True, null=True)
    g02_cnpj = models.CharField(max_length=14, blank=True, null=True)
    g02a_cpf = models.CharField(max_length=11, blank=True, null=True)
    g03_xlgr = models.CharField(max_length=60, blank=True, null=True)
    g04_nro = models.CharField(max_length=60, blank=True, null=True)
    g05_xcpl = models.CharField(max_length=60, blank=True, null=True)
    g06_xbarirro = models.CharField(max_length=60, blank=True, null=True)
    g07_cmun = models.IntegerField(blank=True, null=True)
    g08_xmun = models.CharField(max_length=60, blank=True, null=True)
    g09_uf = models.CharField(max_length=2, blank=True, null=True)
    w03_vbc_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w04_vicms_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w05_vbcst_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w06_vst_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w07_vprod_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w08_vfret_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w09_vseg_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w10_vdesc_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w11_vii_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w12_vipi_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w13_vpis_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w14_vcofins_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w15_voutro_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w16_vnf_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w18_vserv_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w19_vbc_iss_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w20_viss_tota = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w21_vpis_serv = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w22_vcofins_serv = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w24_vretpis = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w25_vretcofins = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w26_vretcsll = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w27_vbcirrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w28_virrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w29_vbcretprev = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    w30_vretprev = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    x02_modfrete = models.IntegerField(blank=True, null=True)
    x04_cnpj_transp = models.CharField(max_length=14, blank=True, null=True)
    x05_cpf_transp = models.CharField(max_length=11, blank=True, null=True)
    x06_xnome_transp = models.CharField(max_length=60, blank=True, null=True)
    x07_ie_transp = models.CharField(max_length=14, blank=True, null=True)
    x08_xender_transp = models.CharField(max_length=60, blank=True, null=True)
    x09_xmun_transp = models.CharField(max_length=60, blank=True, null=True)
    x10_uf_transp = models.CharField(max_length=2, blank=True, null=True)
    x12_vserv_transp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    x13_vbcret_transp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    x14_picmsret_transp = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    x15_vicmsret_transp = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    x16_cfop_transp = models.IntegerField(blank=True, null=True)
    x17_cmunfg_transp = models.IntegerField(blank=True, null=True)
    x19_placa_veic = models.CharField(max_length=8, blank=True, null=True)
    x20_uf_veic = models.CharField(max_length=2, blank=True, null=True)
    x21_rntc_veic = models.CharField(max_length=20, blank=True, null=True)
    x23_placa_reboque1 = models.CharField(max_length=8, blank=True, null=True)
    x24_uf_reboque1 = models.CharField(max_length=2, blank=True, null=True)
    x25_rntc_reboque1 = models.CharField(max_length=20, blank=True, null=True)
    x23_placa_reboque2 = models.CharField(max_length=8, blank=True, null=True)
    x24_uf_reboque2 = models.CharField(max_length=2, blank=True, null=True)
    x25_rntc_reboque2 = models.CharField(max_length=20, blank=True, null=True)
    x23_placa_reboque3 = models.CharField(max_length=8, blank=True, null=True)
    x24_uf_reboque3 = models.CharField(max_length=2, blank=True, null=True)
    x25_rntc_reboque3 = models.CharField(max_length=20, blank=True, null=True)
    x23_placa_reboque4 = models.CharField(max_length=8, blank=True, null=True)
    x24_uf_reboque4 = models.CharField(max_length=2, blank=True, null=True)
    x25_rntc_reboque4 = models.CharField(max_length=20, blank=True, null=True)
    x23_placa_reboque5 = models.CharField(max_length=8, blank=True, null=True)
    x24_uf_reboque5 = models.CharField(max_length=2, blank=True, null=True)
    x25_rntc_reboque5 = models.CharField(max_length=20, blank=True, null=True)
    x25a_vagao = models.CharField(max_length=20, blank=True, null=True)
    x25b_balsa = models.CharField(max_length=20, blank=True, null=True)
    empresa = models.IntegerField(blank=True, null=True)
    filial = models.IntegerField(blank=True, null=True)
    cliente = models.IntegerField(blank=True, null=True)
    xml_nfe = models.TextField(blank=True, null=True)
    prot_nfe = models.CharField(max_length=50, blank=True, null=True)
    status_nfe = models.IntegerField(blank=True, null=True)
    xml_canc = models.TextField(blank=True, null=True)
    prot_canc = models.CharField(max_length=50, blank=True, null=True)
    cancelada = models.BooleanField(blank=True, null=True)
    status_canc = models.IntegerField(blank=True, null=True)
    xml_inut = models.TextField(blank=True, null=True)
    inutilizada = models.BooleanField(blank=True, null=True)
    status_inut = models.IntegerField(blank=True, null=True)
    denegada = models.BooleanField(blank=True, null=True)
    tipo_emissao = models.CharField(max_length=1, blank=True, null=True)
    transportadora = models.IntegerField(blank=True, null=True)
    nr_serie_cert = models.CharField(max_length=50, blank=True, null=True)
    nfve_mens = models.IntegerField(blank=True, null=True)
    nfev_comp_mens = models.TextField(blank=True, null=True)
    nfev_mens_fisc = models.IntegerField(blank=True, null=True)
    nfev_comp_fisc = models.TextField(blank=True, null=True)
    form_reci = models.CharField(max_length=2, blank=True, null=True)
    cfop_pred = models.CharField(max_length=4, blank=True, null=True)
    cust_apro = models.CharField(max_length=1, blank=True, null=True)
    base_funr = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    valo_funr = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nfev_veic = models.IntegerField(blank=True, null=True)
    avis_baix_auto = models.BooleanField(blank=True, null=True)
    adto_pedi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.
    nfev_audi = models.BooleanField(blank=True, null=True)
    nfev_audi_data = models.DateField(blank=True, null=True)
    nfev_audi_por = models.IntegerField(blank=True, null=True)
    nfev_assi_por = models.IntegerField(blank=True, null=True)
    nfev_nome_assi = models.CharField(max_length=30, blank=True, null=True)
    nfev_data_assi = models.DateField(blank=True, null=True)
    nfev_hora_assi = models.TimeField(blank=True, null=True)
    usuario = models.IntegerField(blank=True, null=True)
    nfev_data_hora = models.CharField(max_length=20, blank=True, null=True)
    nfev_prat = models.IntegerField(blank=True, null=True)
    nfev_ende = models.IntegerField(blank=True, null=True)
    b25a_indfinal = models.IntegerField(blank=True, null=True)
    nume_peve_devo = models.IntegerField(blank=True, null=True)
    nfev_oste = models.IntegerField(blank=True, null=True)
    nfev_revi = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    f02b_xnome = models.CharField(max_length=60, blank=True, null=True)
    f10_cep = models.CharField(max_length=8, blank=True, null=True)
    f13_fone = models.CharField(max_length=14, blank=True, null=True)
    f15_ie = models.CharField(max_length=14, blank=True, null=True)
    g02b_xnome = models.CharField(max_length=60, blank=True, null=True)
    g10_cep = models.CharField(max_length=8, blank=True, null=True)
    g13_fone = models.CharField(max_length=14, blank=True, null=True)
    g15_ie = models.CharField(max_length=14, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'nfev'



class ItensNotaEntrada(models.Model):
    id = models.IntegerField(primary_key=True)
    nitem = models.IntegerField()
    i02_cprod = models.CharField(max_length=60, blank=True, null=True)
    i03_cean = models.CharField(max_length=14, blank=True, null=True)
    i04_xprod = models.CharField(max_length=120, blank=True, null=True)
    i05_ncm = models.CharField(max_length=8, blank=True, null=True)
    i06_extipi = models.CharField(max_length=3, blank=True, null=True)
    i08_cfop = models.CharField(max_length=4, blank=True, null=True)
    i09_ucom = models.CharField(max_length=6, blank=True, null=True)
    i10_qcom = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    i10a_vuncom = models.DecimalField(max_digits=21, decimal_places=10, blank=True, null=True)
    i11_vprod = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    i12_ceantrib = models.CharField(max_length=14, blank=True, null=True)
    i13_utrib = models.CharField(max_length=6, blank=True, null=True)
    i14_qtrib = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    i14a_vuntrib = models.DecimalField(max_digits=21, decimal_places=10, blank=True, null=True)
    i15_vfrete = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    i16_vseg = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    i17_vdesc = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    i17a_voutro = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    i17b_indtot = models.IntegerField(blank=True, null=True)
    i30_xped = models.CharField(max_length=15, blank=True, null=True)
    i31_nitemped = models.IntegerField(blank=True, null=True)
    j02_tpop = models.CharField(max_length=1, blank=True, null=True)
    j03_chassi = models.CharField(max_length=17, blank=True, null=True)
    j04_ccor = models.CharField(max_length=4, blank=True, null=True)
    j05_xcor = models.CharField(max_length=40, blank=True, null=True)
    j06_pot = models.CharField(max_length=4, blank=True, null=True)
    j07_cilin = models.CharField(max_length=4, blank=True, null=True)
    j08_pesol = models.CharField(max_length=9, blank=True, null=True)
    j09_pesob = models.CharField(max_length=9, blank=True, null=True)
    j10_nserie = models.CharField(max_length=9, blank=True, null=True)
    j11_tpcomb = models.CharField(max_length=2, blank=True, null=True)
    j12_nmotor = models.CharField(max_length=21, blank=True, null=True)
    j13_cmt = models.CharField(max_length=9, blank=True, null=True)
    j14_dist = models.CharField(max_length=4, blank=True, null=True)
    j16_anomod = models.CharField(max_length=4, blank=True, null=True)
    j17_anofab = models.CharField(max_length=4, blank=True, null=True)
    j18_tppint = models.CharField(max_length=1, blank=True, null=True)
    i19_tpveic = models.IntegerField(blank=True, null=True)
    j20_espveic = models.IntegerField(blank=True, null=True)
    j21_vin = models.CharField(max_length=1, blank=True, null=True)
    j22_condveic = models.IntegerField(blank=True, null=True)
    j23_cmod = models.IntegerField(blank=True, null=True)
    j24_ccordenatran = models.IntegerField(blank=True, null=True)
    j25_lota = models.IntegerField(blank=True, null=True)
    j26_tprest = models.IntegerField(blank=True, null=True)
    l102_cprodanp = models.IntegerField(blank=True, null=True)
    l103_codif = models.CharField(max_length=21, blank=True, null=True)
    l104_qtemp = models.DecimalField(max_digits=16, decimal_places=4, blank=True, null=True)
    l120_ufcons = models.CharField(max_length=2, blank=True, null=True)
    l106_qbcprod = models.DecimalField(max_digits=16, decimal_places=4, blank=True, null=True)
    l107_valiqprod = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    l108_vcide = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n11_orig = models.CharField(max_length=1, blank=True, null=True)
    n12_cst = models.CharField(max_length=3, blank=True, null=True)
    n13_modbc = models.CharField(max_length=1, blank=True, null=True)
    n15_vbc = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n14_predbc = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n16_picms = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n17_vicms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n18_modbcst = models.CharField(max_length=1, blank=True, null=True)
    n19_pmvast = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    n20_predbcst = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n21_vbcst = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n22_picmsst = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n23_vicmsst = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n11_orig_simples = models.CharField(max_length=1, blank=True, null=True)
    n12a_csosn = models.CharField(max_length=3, blank=True, null=True)
    n13_modbc_simples = models.CharField(max_length=1, blank=True, null=True)
    n15_vbc_simples = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n14_predbc_simples = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n16_picms_simples = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n17_vicms_simples = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n18_modbcst_simples = models.CharField(max_length=1, blank=True, null=True)
    n19_pmvast_simples = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    n20_predbcst_simples = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n21_vbcst_simples = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n22_picmsst_simples = models.DecimalField(max_digits=9, decimal_places=4, blank=True, null=True)
    n23_vicmsst_simples = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    n29_pcredsn = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    n30_vcredicmssn = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    o02_cienq = models.CharField(max_length=5, blank=True, null=True)
    o03_cnpjprod = models.CharField(max_length=14, blank=True, null=True)
    o04_cselo = models.CharField(max_length=60, blank=True, null=True)
    o05_qselo = models.CharField(max_length=12, blank=True, null=True)
    o06_cenq = models.CharField(max_length=3, blank=True, null=True)
    o09_cst_ipi = models.CharField(max_length=2, blank=True, null=True)
    o10_vbc_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    o13_pipi_ipi = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    o11_qunid = models.DecimalField(max_digits=16, decimal_places=4, blank=True, null=True)
    o12_vunid = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    o14_vipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    p02_vbc_ii = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    p03_vdespadu = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    p04_vii = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    p05_viof = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    q06_cst_pis = models.CharField(max_length=2, blank=True, null=True)
    q07_vbc_pis = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    q08_ppis = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    q10_qbcprod = models.DecimalField(max_digits=16, decimal_places=4, blank=True, null=True)
    q11_valiqprod_pis = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    q09_vpis = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    s06_cst_cofins = models.CharField(max_length=2, blank=True, null=True)
    s07_vbc_cofins = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    s08_pcofins = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    s09_qbcprod = models.DecimalField(max_digits=16, decimal_places=4, blank=True, null=True)
    s10_valiqprod_cofins = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    s11_vcofins = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    u02_vbc_iss = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    u03_valiq_iss = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    u04_vissqn = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    u05_cmunfg_iss = models.IntegerField(blank=True, null=True)
    u06_clistserv_serv = models.IntegerField(blank=True, null=True)
    u07_csittrib_ssqn = models.CharField(max_length=1, blank=True, null=True)
    v01_infadprod = models.TextField(blank=True, null=True)
    empresa = models.IntegerField(blank=True, null=True)
    filial = models.IntegerField(blank=True, null=True)
    cliente = models.IntegerField(blank=True, null=True)
    modelo = models.CharField(max_length=2, blank=True, null=True)
    serie = models.CharField(max_length=3, blank=True, null=True)
    nota = models.IntegerField(blank=True, null=True)
    entrada = models.DateField(blank=True, null=True)
    produto = models.CharField(max_length=20, blank=True, null=True)
    cfop = models.IntegerField(blank=True, null=True)
    moes = models.BooleanField(blank=True, null=True)
    vlr_cont_icms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_isen_icms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_outr_icms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_dife_icms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_cont_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_isen_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_outr_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    vlr_dife_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    o09_cst_ipi_nt = models.CharField(max_length=2, blank=True, null=True)
    perc_cred_icms = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    perc_cred_ipi = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    cust_apro = models.BooleanField(blank=True, null=True)
    base_funr = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    perc_funr = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    valo_funr = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    nume_seri = models.CharField(max_length=30, blank=True, null=True)
    cont_debi = models.IntegerField(blank=True, null=True)
    cont_cred = models.IntegerField(blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.
    precocompra = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    precovenda = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    medio = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    margem = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    deflacao = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    correcao = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    vencimento = models.DateField(blank=True, null=True)
    ccusto = models.IntegerField(blank=True, null=True)
    grade = models.BooleanField(blank=True, null=True)
    infv_data_hora = models.CharField(max_length=20, blank=True, null=True)
    infv_codi_bene = models.CharField(max_length=10, blank=True, null=True)
    dife_icms = models.DecimalField(max_digits=15, decimal_places=4, blank=True, null=True)
    vbcstret = models.FloatField(blank=True, null=True)
    pst = models.FloatField(blank=True, null=True)
    vicmssubstituto = models.FloatField(blank=True, null=True)
    vicmsstret = models.FloatField(blank=True, null=True)
    descanp = models.CharField(max_length=95, blank=True, null=True)
    vfcpst = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    infv_valo_funr = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    la03a_pglp = models.FloatField(blank=True, null=True)
    la03b_pgnn = models.FloatField(blank=True, null=True)
    la03c_pgni = models.FloatField(blank=True, null=True)
    la03d_vpart = models.FloatField(blank=True, null=True)
    adremicmsret = models.FloatField(blank=True, null=True)
    vicmsdeson = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    seto_esto = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'infv'
        unique_together = (('id', 'nitem'),)