# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceteCC',
            fields=[
                ('empr', models.IntegerField()),
                ('fili', models.IntegerField()),
                ('cecu_redu', models.CharField(max_length=10)),
                ('centro_nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo_cc', models.CharField(default='Sem', max_length=1)),
                ('mes_num', models.CharField(max_length=2)),
                ('mes_nome', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('mes_ordem', models.IntegerField()),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'balancete_cc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtratoCaixa',
            fields=[
                ('empresa', models.IntegerField(db_column='Empresa')),
                ('filial', models.IntegerField(db_column='Filial')),
                ('pedido', models.IntegerField(db_column='Pedido', primary_key=True, serialize=False)),
                ('cliente', models.IntegerField(db_column='Cliente')),
                ('nome_cliente', models.CharField(db_column='Nome Cliente', max_length=200)),
                ('produto', models.CharField(db_column='Produto', max_length=100)),
                ('descricao', models.CharField(db_column='Descrição', max_length=200)),
                ('quantidade', models.DecimalField(db_column='Quantidade', decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(db_column='Valor Total', decimal_places=2, max_digits=12)),
                ('data', models.DateField(db_column='Data')),
                ('forma_de_recebimento', models.CharField(db_column='Forma de Recebimento', max_length=50)),
            ],
            options={
                'db_table': 'extrato_caixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrcamentoAnaliticoView',
            fields=[
                ('plan_redu', models.CharField(max_length=20)),
                ('plan_nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('valor_orcado', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'orcamento_2025',
                'managed': False,
            },
        ),
    ]
