# Generated by Django 2.2.28 on 2025-07-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogParametroSistema',
            fields=[
                ('log_codi', models.AutoField(primary_key=True, serialize=False)),
                ('log_tabe', models.CharField(help_text='Tabela alterada', max_length=50)),
                ('log_regi', models.IntegerField(help_text='ID do registro')),
                ('log_acao', models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão')], max_length=20)),
                ('log_valo_ante', models.BooleanField(blank=True, help_text='Valor anterior', null=True)),
                ('log_valo_novo', models.BooleanField(blank=True, help_text='Valor novo', null=True)),
                ('log_usua', models.IntegerField(help_text='Usuário')),
                ('log_data', models.DateTimeField(auto_now_add=True)),
                ('log_ip', models.GenericIPAddressField(blank=True, help_text='IP do usuário', null=True)),
            ],
            options={
                'verbose_name': 'Log de Parâmetro',
                'verbose_name_plural': 'Logs de Parâmetros',
                'db_table': 'log_parametro_sistema',
                'ordering': ['-log_data'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modu_codi', models.AutoField(primary_key=True, serialize=False)),
                ('modu_nome', models.CharField(help_text='Nome do módulo', max_length=50, unique=True)),
                ('modu_desc', models.TextField(help_text='Descrição do módulo')),
                ('modu_ativ', models.BooleanField(default=True, help_text='Módulo ativo no sistema')),
                ('modu_icon', models.CharField(blank=True, help_text='Ícone do módulo', max_length=50)),
                ('modu_orde', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'db_table': 'modulosmobile',
                'ordering': ['modu_orde', 'modu_nome'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoModulo',
            fields=[
                ('perm_codi', models.AutoField(primary_key=True, serialize=False)),
                ('perm_empr', models.IntegerField(help_text='Código da empresa')),
                ('perm_fili', models.IntegerField(help_text='Código da filial')),
                ('perm_ativ', models.BooleanField(default=True, help_text='Módulo liberado')),
                ('perm_usua_libe', models.IntegerField(blank=True, help_text='Usuário que liberou')),
                ('perm_data_alte', models.DateTimeField(auto_now=True, help_text='Data de alteração')),
                ('perm_modu', models.ForeignKey(db_column='perm_modu', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='parametros_admin.Modulo')),
            ],
            options={
                'db_table': 'permissoesmodulosmobile',
                'unique_together': {('perm_empr', 'perm_fili', 'perm_modu')},
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('para_codi', models.AutoField(primary_key=True, serialize=False)),
                ('para_empr', models.IntegerField(help_text='Código da empresa')),
                ('para_fili', models.IntegerField(help_text='Código da filial')),
                ('para_nome', models.CharField(help_text='Nome do parâmetro', max_length=50)),
                ('para_desc', models.TextField(help_text='Descrição do parâmetro')),
                ('para_valo', models.BooleanField(default=False, help_text='Valor do parâmetro (True/False)')),
                ('para_ativ', models.BooleanField(default=True, help_text='Parâmetro ativo')),
                ('para_data_alte', models.DateTimeField(auto_now=True, help_text='Data de alteração')),
                ('para_usua_alte', models.IntegerField(blank=True, help_text='Usuário que alterou')),
                ('para_modu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='parametros_admin.Modulo')),
            ],
            options={
                'db_table': 'parametrosmobile',
                'ordering': ['para_modu', 'para_nome'],
                'unique_together': {('para_empr', 'para_fili', 'para_modu', 'para_nome')},
            },
        ),
    ]
