from django.db import models

"""
class Parametros(models.Model):
    para_empr = models.IntegerField(primary_key=True)
    para_plan_niv1 = models.IntegerField(blank=True, null=True)
    para_plan_niv2 = models.IntegerField(blank=True, null=True)
    para_plan_niv3 = models.IntegerField(blank=True, null=True)
    para_plan_niv4 = models.IntegerField(blank=True, null=True)
    para_plan_niv5 = models.IntegerField(blank=True, null=True)
    para_cecu_niv1 = models.IntegerField(blank=True, null=True)
    para_cecu_niv2 = models.IntegerField(blank=True, null=True)
    para_cecu_niv3 = models.IntegerField(blank=True, null=True)
    para_cecu_niv4 = models.IntegerField(blank=True, null=True)
    para_cecu_niv5 = models.IntegerField(blank=True, null=True)
    para_util_cecu = models.BooleanField(blank=True, null=True)
    para_dbcr = models.BooleanField(blank=True, null=True)
    para_supe = models.BooleanField(blank=True, null=True)
    para_cecu_resu = models.BooleanField(blank=True, null=True)
    para_folh = models.BooleanField(blank=True, null=True)
    para_empr_resp = models.CharField(max_length=200, blank=True, null=True)
    para_carg = models.CharField(max_length=100, blank=True, null=True)
    para_data_inic = models.DateField(blank=True, null=True)
    para_data_fina = models.DateField(blank=True, null=True)
    para_cnpj = models.CharField(max_length=14, blank=True, null=True)
    para_cpf = models.CharField(max_length=11, blank=True, null=True)
    para_fone = models.CharField(max_length=14, blank=True, null=True)
    para_fax = models.CharField(max_length=14, blank=True, null=True)
    para_emai = models.CharField(max_length=200, blank=True, null=True)
    para_grup_clie = models.IntegerField(blank=True, null=True)
    para_cont_clie = models.IntegerField(blank=True, null=True)
    para_grup_forn = models.IntegerField(blank=True, null=True)
    para_cont_forn = models.IntegerField(blank=True, null=True)
    para_juro_ativ = models.IntegerField(blank=True, null=True)
    para_mult_ativ = models.IntegerField(blank=True, null=True)
    para_desc_ativ = models.IntegerField(blank=True, null=True)
    para_juro_pass = models.IntegerField(blank=True, null=True)
    para_mult_pass = models.IntegerField(blank=True, null=True)
    para_desc_pass = models.IntegerField(blank=True, null=True)
    para_plan_niv6 = models.IntegerField(blank=True, null=True)
    para_plan_niv7 = models.IntegerField(blank=True, null=True)
    para_plan_niv8 = models.IntegerField(blank=True, null=True)
    para_plan_niv9 = models.IntegerField(blank=True, null=True)
    para_plan_niv10 = models.IntegerField(blank=True, null=True)
    para_perm_esto_nega = models.BooleanField(blank=True, null=True)
    para_perm_enti_sem_cnpj = models.BooleanField(blank=True, null=True)
    para_perm_enti_com_cnpj_dupl = models.BooleanField(blank=True, null=True)
    para_pedi_comp_libe = models.BooleanField(blank=True, null=True)
    para_nota_comp_some_pedi_libe = models.BooleanField(blank=True, null=True)
    para_port_matr = models.CharField(max_length=100, blank=True, null=True)
    para_prod_sequ = models.BooleanField(blank=True, null=True)
    para_desa_ajud = models.BooleanField(blank=True, null=True)
    para_nite_pedi_vend = models.IntegerField(blank=True, null=True)
    para_pedi_esto = models.BooleanField(blank=True, null=True)
    para_pedi_mofi = models.BooleanField(blank=True, null=True)
    para_tabe_perc = models.BooleanField(blank=True, null=True)
    para_desa_prot = models.BooleanField(blank=True, null=True)
    para_carr_cons_prod = models.BooleanField(blank=True, null=True)
    para_nota_sem_xml = models.BooleanField(blank=True, null=True)
    para_cada_prod_unic = models.BooleanField(blank=True, null=True)
    para_pag_for = models.BooleanField(blank=True, null=True)
    para_calc_ibpt = models.BooleanField(blank=True, null=True)
    para_meos_1 = models.TextField(blank=True, null=True)
    para_meos_2 = models.TextField(blank=True, null=True)
    cfop_vend_esta = models.IntegerField(blank=True, null=True)
    cfop_vend_fora_esta = models.IntegerField(blank=True, null=True)
    cfop_serv_esta = models.IntegerField(blank=True, null=True)
    cfop_serv_fora_esta = models.IntegerField(blank=True, null=True)
    seri_nota_peca_os = models.CharField(max_length=3, blank=True, null=True)
    seri_nota_serv_os = models.CharField(max_length=3, blank=True, null=True)
    orde_serv_esto = models.BooleanField(blank=True, null=True)
    para_fina_comp = models.IntegerField(blank=True, null=True)
    para_fina_vend = models.IntegerField(blank=True, null=True)
    para_cfop_esta_pr = models.IntegerField(blank=True, null=True)
    para_cfop_fora_pr = models.IntegerField(blank=True, null=True)
    para_perc_max_desc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_cnpj_cert = models.BooleanField(blank=True, null=True)
    para_vend_baix_auto = models.BooleanField(blank=True, null=True)
    para_comp_baix_auto = models.BooleanField(blank=True, null=True)
    para_cont_caix = models.IntegerField(blank=True, null=True)
    para_moti_excl_item = models.BooleanField(blank=True, null=True)
    para_mens_esto_nega = models.BooleanField(blank=True, null=True)
    para_tipo_cada = models.IntegerField(blank=True, null=True)
    para_sai_esc = models.BooleanField(blank=True, null=True)
    para_peri_fatu_paga = models.DateField(blank=True, null=True)
    para_cont_cheq_devo = models.IntegerField(blank=True, null=True)
    para_perc_base_inss = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_perc_base_irrf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_perc_inss = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_teto_desc_inss = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_perc_base_sest_sena = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_perc_sest_sena = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_perc_maxi_adia = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_calc_rete_cf = models.BooleanField(blank=True, null=True)
    para_desc_pont_mens = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_impr_40 = models.BooleanField(blank=True, null=True)
    para_cafr_nume_cte = models.BooleanField(blank=True, null=True)
    para_obri_port_paga = models.BooleanField(blank=True, null=True)
    para_obri_situ_paga = models.BooleanField(blank=True, null=True)
    para_obri_port_rece = models.BooleanField(blank=True, null=True)
    para_obri_situ_rece = models.BooleanField(blank=True, null=True)
    para_cont_obri = models.BooleanField(blank=True, null=True)
    para_nfes_obse = models.BooleanField(blank=True, null=True)
    para_dact_peda = models.BooleanField(blank=True, null=True)
    para_dact_fast = models.BooleanField(blank=True, null=True)
    para_veri_moto = models.BooleanField(blank=True, null=True)
    para_cafr_info = models.BooleanField(blank=True, null=True)
    para_venc_pedi_vert = models.BooleanField(blank=True, null=True)
    cfop_vend_esta_st = models.IntegerField(blank=True, null=True)
    cfop_vend_fora_esta_st = models.IntegerField(blank=True, null=True)
    para_obri_aten_os = models.BooleanField(blank=True, null=True)
    para_cons_simi = models.BooleanField(blank=True, null=True)
    para_cons_simi_apre = models.BooleanField(blank=True, null=True)
    para_pedi_vend_form_raza = models.BooleanField(blank=True, null=True)
    para_pedi_vend_altu = models.IntegerField(blank=True, null=True)
    para_cont_adia_forn = models.IntegerField(blank=True, null=True)
    para_cont_adia_clie = models.IntegerField(blank=True, null=True)
    para_noco_some_pedi = models.BooleanField(blank=True, null=True)
    para_cont_adia_moto = models.IntegerField(blank=True, null=True)
    para_nao_cfop_hist_cont = models.BooleanField(blank=True, null=True)
    para_rece = models.IntegerField(blank=True, null=True)
    para_rece_irrf = models.IntegerField(blank=True, null=True)
    para_inss = models.IntegerField(blank=True, null=True)
    para_pref = models.IntegerField(blank=True, null=True)
    para_pedi_duas_via = models.BooleanField(blank=True, null=True)
    para_data_entr_auto = models.BooleanField(blank=True, null=True)
    para_veri_veic = models.BooleanField(blank=True, null=True)
    para_empr_nfse = models.IntegerField(blank=True, null=True)
    para_veri_titu_venc = models.BooleanField(blank=True, null=True)
    para_most_titu_venc = models.BooleanField(blank=True, null=True)
    para_mens_bloq_auto = models.CharField(max_length=60, blank=True, null=True)
    para_nao_queb_kit = models.BooleanField(blank=True, null=True)
    para_cart_fret_repo = models.BooleanField(blank=True, null=True)
    para_cert_fret_repo = models.CharField(max_length=255, blank=True, null=True)
    para_codi_clie_repo = models.CharField(max_length=20, blank=True, null=True)
    para_cont_adto_viag = models.IntegerField(blank=True, null=True)
    para_cont_adto_auto = models.IntegerField(blank=True, null=True)
    para_cont_fret_juri = models.IntegerField(blank=True, null=True)
    para_cont_fret_fisi = models.IntegerField(blank=True, null=True)
    para_cont_admi_fret = models.IntegerField(blank=True, null=True)
    para_cecu_fisi_cart = models.IntegerField(blank=True, null=True)
    para_cecu_juri_cart = models.IntegerField(blank=True, null=True)
    para_cecu_cart = models.IntegerField(blank=True, null=True)
    para_forn_cart = models.IntegerField(blank=True, null=True)
    para_fatu_espe = models.BooleanField(blank=True, null=True)
    para_forn_comp_pedi = models.BooleanField(blank=True, null=True)
    para_sem_cred_icms = models.BooleanField(blank=True, null=True)
    para_pedi_resu = models.BooleanField(blank=True, null=True)
    para_codi_cons = models.IntegerField(blank=True, null=True)
    para_impr_pedi_grav = models.BooleanField(blank=True, null=True)
    para_cecu_acer_moto = models.IntegerField(blank=True, null=True)
    para_cart_fret_valo_moto = models.BooleanField(blank=True, null=True)
    para_adia_pedi = models.BooleanField(blank=True, null=True)
    para_cont_juro_desc = models.IntegerField(blank=True, null=True)
    para_toma_dest_fret_apag = models.BooleanField(blank=True, null=True)
    para_seri_fina_pre_cada = models.BooleanField(blank=True, null=True)
    para_obri_pis_moto = models.BooleanField(blank=True, null=True)
    para_cont_rece_fatu = models.BooleanField(blank=True, null=True)
    para_usua_atm = models.CharField(max_length=50, blank=True, null=True)
    para_senh_atm = models.CharField(max_length=50, blank=True, null=True)
    para_codi_atm = models.CharField(max_length=50, blank=True, null=True)
    para_pedi_matr = models.BooleanField(blank=True, null=True)
    para_obri_pis_tran = models.BooleanField(blank=True, null=True)
    para_perm_segu_cte = models.BooleanField(blank=True, null=True)
    para_impr_peda_dact = models.BooleanField(blank=True, null=True)
    para_calc_segu_cte = models.BooleanField(blank=True, null=True)
    para_desc_com_perm = models.BooleanField(blank=True, null=True)
    field_log_data = models.DateField(db_column='_log_data', blank=True, null=True)  # Field renamed because it started with '_'.
    field_log_time = models.TimeField(db_column='_log_time', blank=True, null=True)  # Field renamed because it started with '_'.
    para_xml_nota_entr_sem_reca = models.BooleanField(blank=True, null=True)
    para_hist_fina_cont = models.BooleanField(blank=True, null=True)
    para_vend_proc_caix = models.BooleanField(blank=True, null=True)
    para_conf_audi = models.BooleanField(blank=True, null=True)
    para_cont_adia_moto_terc = models.IntegerField(blank=True, null=True)
    para_aba_outr_docu = models.BooleanField(blank=True, null=True)
    para_aba_enca = models.BooleanField(blank=True, null=True)
    para_toma_dest_paga = models.BooleanField(blank=True, null=True)
    para_adic_peda_desm = models.BooleanField(blank=True, null=True)
    para_segu_cont_emit = models.BooleanField(blank=True, null=True)
    para_tota_peso_quan = models.BooleanField(blank=True, null=True)
    para_cons_prod_sald = models.BooleanField(blank=True, null=True)
    para_cont_cte_liqu = models.BooleanField(blank=True, null=True)
    para_banc_cobr = models.IntegerField(blank=True, null=True)
    para_cart_cobr = models.IntegerField(blank=True, null=True)
    para_obri_vend_pedi = models.BooleanField(blank=True, null=True)
    para_obri_fina_cte = models.BooleanField(blank=True, null=True)
    para_aliq_iss = models.DecimalField(max_digits=8, decimal_places=5, blank=True, null=True)
    para_os_mag_sul = models.BooleanField(blank=True, null=True)
    para_ecf_mode = models.IntegerField(blank=True, null=True)
    para_ecf_port = models.CharField(max_length=30, blank=True, null=True)
    para_ecf_time = models.IntegerField(blank=True, null=True)
    para_ecf_inte = models.IntegerField(blank=True, null=True)
    para_ecf_linh = models.IntegerField(blank=True, null=True)
    para_ecf_tent_nova = models.BooleanField(blank=True, null=True)
    para_ecf_arre_quan = models.BooleanField(blank=True, null=True)
    para_ecf_bloq_mous = models.BooleanField(blank=True, null=True)
    para_ecf_gave_sina = models.BooleanField(blank=True, null=True)
    para_ecf_exib_mens = models.BooleanField(blank=True, null=True)
    para_ecf_desc_gran = models.BooleanField(blank=True, null=True)
    para_ecf_arre_item = models.BooleanField(blank=True, null=True)
    para_ecf_mens_agua = models.TextField(blank=True, null=True)
    para_ecf_mens_trab = models.CharField(max_length=100, blank=True, null=True)
    para_usa_mark_up = models.BooleanField(blank=True, null=True)
    para_logo_expa_danf = models.BooleanField(blank=True, null=True)
    para_atua_prec_comp = models.BooleanField(blank=True, null=True)
    para_prec_atua_meno_mant = models.BooleanField(blank=True, null=True)
    para_fina_nota_pelo_nume = models.BooleanField(blank=True, null=True)
    para_impr_venc_nota_serv = models.BooleanField(blank=True, null=True)
    para_codi_caix_fech = models.IntegerField(blank=True, null=True)
    para_cont_adto_func = models.IntegerField(blank=True, null=True)
    para_cont_sala_paga = models.IntegerField(blank=True, null=True)
    para_deco_prec_comp = models.BooleanField(blank=True, null=True)
    para_grup_prod_saun = models.IntegerField(blank=True, null=True)
    para_prod_grup_sugr = models.BooleanField(blank=True, null=True)
    para_util_conf_vend = models.BooleanField(blank=True, null=True)
    para_cont_juro_fina = models.IntegerField(blank=True, null=True)
    para_nao_sald_inic_caix = models.BooleanField(blank=True, null=True)
    para_fech_caix_tran_tota = models.BooleanField(blank=True, null=True)
    para_obri_insc_enti_vend = models.BooleanField(blank=True, null=True)
    para_icms_regi = models.BooleanField(blank=True, null=True)
    para_pedi_laje = models.BooleanField(blank=True, null=True)
    para_dupl_prod = models.BooleanField(blank=True, null=True)
    para_obri_comi_pedi = models.BooleanField(blank=True, null=True)
    para_most_venc_nfe = models.BooleanField(blank=True, null=True)
    para_veze = models.BooleanField(blank=True, null=True)
    para_expu = models.BooleanField(blank=True, null=True)
    para_fabr = models.CharField(max_length=20, blank=True, null=True)
    para_marc = models.CharField(max_length=20, blank=True, null=True)
    para_mode = models.CharField(max_length=20, blank=True, null=True)
    para_canc_pedi = models.BooleanField(blank=True, null=True)
    para_impr_dupl_nfe = models.BooleanField(blank=True, null=True)
    para_impr_bole_nfe = models.BooleanField(blank=True, null=True)
    para_mens_padr_bole = models.BooleanField(blank=True, null=True)
    para_obri_assi_nota = models.BooleanField(blank=True, null=True)
    para_os_usin = models.BooleanField(blank=True, null=True)
    para_orca_1 = models.TextField(blank=True, null=True)
    para_orca_2 = models.TextField(blank=True, null=True)
    para_pedi_comp_esto = models.BooleanField(blank=True, null=True)
    para_pedi_comp_fina = models.BooleanField(blank=True, null=True)
    para_impr_nome_fant_nf = models.BooleanField(blank=True, null=True)
    para_edit_emai = models.BooleanField(blank=True, null=True)
    para_alte_clie_nfe_pedi = models.BooleanField(blank=True, null=True)
    para_hist_titu = models.BooleanField(blank=True, null=True)
    para_perc_mult_rece = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_juro_rece = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_juro_dia_rece = models.BooleanField(blank=True, null=True)
    para_perc_juro_mes_rece = models.BooleanField(blank=True, null=True)
    para_perc_mult_paga = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_juro_paga = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_juro_dia_paga = models.BooleanField(blank=True, null=True)
    para_perc_juro_mes_paga = models.BooleanField(blank=True, null=True)
    para_perc_desc_rece = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_desc_dia_rece = models.BooleanField(blank=True, null=True)
    para_perc_desc_mes_rece = models.BooleanField(blank=True, null=True)
    para_perc_desc_paga = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_perc_desc_dia_paga = models.BooleanField(blank=True, null=True)
    para_perc_desc_mes_paga = models.BooleanField(blank=True, null=True)
    para_nao_limp_prod = models.BooleanField(blank=True, null=True)
    para_obse_nota_rece = models.BooleanField(blank=True, null=True)
    para_prec_cust_cons_prod = models.BooleanField(blank=True, null=True)
    para_tele_vend = models.BooleanField(blank=True, null=True)
    para_posi_esto_cust_gere = models.BooleanField(blank=True, null=True)
    para_tabe_defl = models.BooleanField(blank=True, null=True)
    para_form_calc_cust = models.TextField(blank=True, null=True)
    para_prec_padr_50 = models.BooleanField(blank=True, null=True)
    para_defl = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_corr = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_esco_prec = models.BooleanField(blank=True, null=True)
    para_padr_duas_via_sj = models.BooleanField(blank=True, null=True)
    para_codi_barr_igua_prod = models.BooleanField(blank=True, null=True)
    para_obri_cecu_paga = models.BooleanField(blank=True, null=True)
    para_aler_sem_fret = models.BooleanField(blank=True, null=True)
    para_grup_cheq_rece = models.IntegerField(blank=True, null=True)
    para_cont_cheq_rece = models.IntegerField(blank=True, null=True)
    para_obri_vend_nota = models.BooleanField(blank=True, null=True)
    para_desc_item_peve = models.BooleanField(blank=True, null=True)
    para_apre_cust_cons_prod = models.BooleanField(blank=True, null=True)
    para_apag_nume_pedi_incl = models.BooleanField(blank=True, null=True)
    para_pedi_mult_item = models.BooleanField(blank=True, null=True)
    para_3_prec_tabe_norm = models.BooleanField(blank=True, null=True)
    para_requ_said_prec_comp = models.BooleanField(blank=True, null=True)
    para_calc_st_pedi = models.BooleanField(blank=True, null=True)
    para_nao_impr_pedi_nota = models.BooleanField(blank=True, null=True)
    para_impr_assi_pedi_vend = models.BooleanField(blank=True, null=True)
    para_impr_codi_fabr_cupo_vend = models.BooleanField(blank=True, null=True)
    para_impr_40_matr = models.BooleanField(blank=True, null=True)
    para_nume_titu_pedi_ctrl = models.BooleanField(blank=True, null=True)
    para_most_cheq_flux_caix = models.BooleanField(blank=True, null=True)
    para_rate_cecu = models.BooleanField(blank=True, null=True)
    para_gera_nota_pedi = models.BooleanField(blank=True, null=True)
    para_cont_desp_banc = models.IntegerField(blank=True, null=True)
    para_cont_iof = models.IntegerField(blank=True, null=True)
    para_resu_fina_deta_paga = models.BooleanField(blank=True, null=True)
    para_expu_para = models.BooleanField(blank=True, null=True)
    para_seri_cons = models.CharField(max_length=3, blank=True, null=True)
    para_impr_rela_item = models.BooleanField(blank=True, null=True)
    para_orca_desc_perc = models.BooleanField(blank=True, null=True)
    para_cred_titu_rece = models.BooleanField(blank=True, null=True)
    para_perm_unit_zera_pedi = models.BooleanField(blank=True, null=True)
    para_veri_panc = models.BooleanField(blank=True, null=True)
    para_cfop_devo = models.IntegerField(blank=True, null=True)
    para_nfce_caix = models.BooleanField(blank=True, null=True)
    para_obri_clie_vend_caix = models.BooleanField(blank=True, null=True)
    para_obri_nasc_fone_enti = models.BooleanField(blank=True, null=True)
    para_util_tipo_comi_vend = models.BooleanField(blank=True, null=True)
    para_cust_emis_nf = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_gera_titu_adia = models.BooleanField(blank=True, null=True)
    para_perm_alte_pedi_parc = models.BooleanField(blank=True, null=True)
    para_usar_vali_gtin = models.BooleanField(blank=True, null=True)
    para_ocul_vend_sald = models.BooleanField(blank=True, null=True)
    para_peve_cons_movi_esto = models.BooleanField(blank=True, null=True)
    para_atua_prec_naos = models.BooleanField(blank=True, null=True)
    para_etiq_novo_padr = models.BooleanField(blank=True, null=True)
    para_deta_nfee_grad = models.BooleanField(blank=True, null=True)
    para_fech_caix_sven = models.BooleanField(blank=True, null=True)
    para_form_usar_cust_medi = models.BooleanField(blank=True, null=True)
    para_obri_coma_cpf = models.BooleanField(blank=True, null=True)
    para_util_coma = models.BooleanField(blank=True, null=True)
    para_alte_unit_vend_caix = models.BooleanField(blank=True, null=True)
    para_alte_pedi_clie_bloq = models.BooleanField(blank=True, null=True)
    para_nusa_ctrl_cheq_caix = models.BooleanField(blank=True, null=True)
    para_padr_cust_rela = models.IntegerField(blank=True, null=True)
    para_impr_nfce_semm_prev = models.BooleanField(blank=True, null=True)
    para_desc_ambo_peve = models.BooleanField(blank=True, null=True)
    para_desc_dsto_comi_vend = models.BooleanField(blank=True, null=True)
    para_obri_coma_rg = models.BooleanField(blank=True, null=True)
    para_aliq_icms_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_redu_icms_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_aliq_icms_st_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_redu_icms_st_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_mva_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_cst_icms_gera = models.CharField(max_length=3, blank=True, null=True)
    para_cst_pis_gera = models.CharField(max_length=2, blank=True, null=True)
    para_aliq_pis_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_cst_cofi_gera = models.CharField(max_length=2, blank=True, null=True)
    para_aliq_cofi_gera = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_mens_gera = models.IntegerField(blank=True, null=True)
    para_cfop_gera = models.IntegerField(blank=True, null=True)
    para_padr_marg_lucr = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    para_vend_dinh_caix_gera_rece = models.BooleanField(blank=True, null=True)
    posi_esto_list_mapr_form = models.BooleanField(blank=True, null=True)
    para_cecu_reci_rece = models.IntegerField(blank=True, null=True)
    para_cecu_rece_desc = models.IntegerField(blank=True, null=True)
    para_comi_base_perc_vend = models.BooleanField(blank=True, null=True)
    para_mais_tecn_iser = models.BooleanField(blank=True, null=True)
    para_impr_obse_oser = models.BooleanField(blank=True, null=True)
    para_mens_enti_prot = models.BooleanField(blank=True, null=True)
    para_bloq_cheq_devo = models.BooleanField(blank=True, null=True)
    para_traz_ulti_unit = models.BooleanField(blank=True, null=True)
    para_pedi_mult_item_c = models.BooleanField(blank=True, null=True)
    para_fech_serv_os_mult_empr = models.BooleanField(blank=True, null=True)
    para_bloq_entr_caix = models.BooleanField(blank=True, null=True)
    para_pedi_impr_orca_novo_padr = models.BooleanField(blank=True, null=True)
    para_pedi_brin_bar = models.BooleanField(blank=True, null=True)
    para_perm_fina_os = models.BooleanField(blank=True, null=True)
    para_nao_impr_clie_nota = models.BooleanField(blank=True, null=True)
    para_desb_diar = models.BooleanField(blank=True, null=True)
    para_os_proc_caix = models.BooleanField(blank=True, null=True)
    para_os_serv_stat = models.BooleanField(blank=True, null=True)
    para_mesa_obri_bar = models.BooleanField(blank=True, null=True)
    para_impr_orse_matr = models.BooleanField(blank=True, null=True)
    para_esto_movi_entr = models.BooleanField(blank=True, null=True)
    para_impr_info_bala = models.BooleanField(blank=True, null=True)
    para_most_grad = models.BooleanField(blank=True, null=True)
    para_most_joia = models.BooleanField(blank=True, null=True)
    para_calc_valo_cont_os = models.BooleanField(blank=True, null=True)
    para_nao_impr_prod_codi = models.BooleanField(blank=True, null=True)
    cfop_prod_esta = models.IntegerField(blank=True, null=True)
    cfop_prod_fora_esta = models.IntegerField(blank=True, null=True)
    para_praz_prec_unit = models.BooleanField(blank=True, null=True)
    para_prec_cust_orca = models.BooleanField(blank=True, null=True)
    cfop_entr_prod = models.IntegerField(blank=True, null=True)
    para_cons_sald_peve = models.BooleanField(blank=True, null=True)
    para_tira_conf_emai = models.BooleanField(blank=True, null=True)
    para_oper_cpom_fisc = models.BooleanField(blank=True, null=True)
    para_emit_nota_pedi = models.BooleanField(blank=True, null=True)
    para_nao_cabe_orca = models.BooleanField(blank=True, null=True)
    para_most_pedi_sem_fina = models.BooleanField(blank=True, null=True)
    para_obri_juro_mult = models.BooleanField(blank=True, null=True)
    para_sele_ende_clie_nota = models.BooleanField(blank=True, null=True)
    cfop_vend_nfce = models.IntegerField(blank=True, null=True)
    cfop_vest_nfce = models.IntegerField(blank=True, null=True)
    para_impr_coma_auto = models.BooleanField(blank=True, null=True)
    para_couv_entr = models.BooleanField(blank=True, null=True)
    para_most_prod_obse = models.BooleanField(blank=True, null=True)
    para_most_data_part = models.BooleanField(blank=True, null=True)
    para_most_unif = models.BooleanField(blank=True, null=True)
    para_nunc_os_parc = models.BooleanField(blank=True, null=True)
    para_nova_os_parc = models.BooleanField(blank=True, null=True)
    para_emis_cupo_caix = models.BooleanField(blank=True, null=True)
    para_most_unid_medi = models.BooleanField(blank=True, null=True)
    para_data_rece_hoje = models.BooleanField(blank=True, null=True)
    para_clon_nota_entr = models.BooleanField(blank=True, null=True)
    para_reci_entr_fili = models.BooleanField(blank=True, null=True)
    para_caix_pre_pago = models.BooleanField(blank=True, null=True)
    para_mode_nfse = models.IntegerField(blank=True, null=True)
    para_pedi_deta_adic = models.BooleanField(blank=True, null=True)
    para_orca_deta_adic = models.BooleanField(blank=True, null=True)
    para_usua_vend_obri = models.BooleanField(blank=True, null=True)
    para_rece_valo_supe_titu = models.BooleanField(blank=True, null=True)
    para_util_cred_vend = models.BooleanField(blank=True, null=True)
    para_obri_cecu_vend = models.BooleanField(blank=True, null=True)
    para_grad_padr = models.IntegerField(blank=True, null=True)
    para_form_repe_prod = models.BooleanField(blank=True, null=True)
    para_perc_maxi_desc_vend = models.BooleanField(blank=True, null=True)
    para_desc_cond = models.BooleanField(blank=True, null=True)
    para_cfop_vend_futu_esta = models.IntegerField(blank=True, null=True)
    para_cfop_vend_futu_fora_esta = models.IntegerField(blank=True, null=True)
    para_juro_mult_dias_util = models.BooleanField(blank=True, null=True)
    para_auto_dda = models.BooleanField(blank=True, null=True)
    para_meca_pdv = models.BooleanField(blank=True, null=True)
    para_cust_prco = models.BooleanField(blank=True, null=True)
    para_vouc_prod = models.BooleanField(blank=True, null=True)
    para_opca_baix_futu = models.BooleanField(blank=True, null=True)
    para_most_pedi_praz_caix = models.BooleanField(blank=True, null=True)
    para_tran_zera_caix = models.BooleanField(blank=True, null=True)
    para_orde_prod_nume = models.BooleanField(blank=True, null=True)
    para_cada_fami = models.BooleanField(blank=True, null=True)
    para_tabe_tipo_enti = models.BooleanField(blank=True, null=True)
    para_libe_veri_fina = models.BooleanField(blank=True, null=True)
    para_ctrl_proj = models.BooleanField(blank=True, null=True)
    para_most_prec_segu = models.BooleanField(blank=True, null=True)
    para_segu_parc = models.BooleanField(blank=True, null=True)
    para_veri_desc_max_item = models.BooleanField(blank=True, null=True)
    para_carn_reim = models.BooleanField(blank=True, null=True)
    para_bloq_orca = models.BooleanField(blank=True, null=True)
    para_alte_obse_peve = models.BooleanField(blank=True, null=True)
    para_gera_arqu_bosch = models.BooleanField(blank=True, null=True)
    para_fech_caix_vali_nota = models.BooleanField(blank=True, null=True)
    para_conv_metr_cubi = models.BooleanField(blank=True, null=True)
    para_gera_code_barr = models.BooleanField(blank=True, null=True)
    para_digi_code_barr = models.IntegerField(blank=True, null=True)
    para_admi_oper_cart = models.BooleanField(blank=True, null=True)
    para_mdfe_ucte = models.BooleanField(blank=True, null=True)
    para_esto_cinc_prec = models.BooleanField(blank=True, null=True)
    para_mens_esto_pedi_orca = models.BooleanField(blank=True, null=True)
    para_pedi_cust_gere = models.BooleanField(blank=True, null=True)
    para_cont_carr = models.BooleanField(blank=True, null=True)
    para_calc_pelo_xml = models.BooleanField(blank=True, null=True)
    para_cont_paga_proj_cecu = models.BooleanField(blank=True, null=True)
    para_novo_extr_banc = models.BooleanField(blank=True, null=True)
    para_cont_esto_comb = models.BooleanField(blank=True, null=True)
    para_deb_abas = models.IntegerField(blank=True, null=True)
    para_cred_abas = models.IntegerField(blank=True, null=True)
    para_codi_tran = models.IntegerField(blank=True, null=True)
    para_codi_serv = models.IntegerField(blank=True, null=True)
    para_inte_meus_pedi = models.BooleanField(blank=True, null=True)
    para_pedi_rela_acou = models.BooleanField(blank=True, null=True)
    para_nao_envi_xml = models.BooleanField(blank=True, null=True)
    para_nao_most_fatu_caix = models.BooleanField(blank=True, null=True)
    para_filt_prod_rela_fina = models.BooleanField(blank=True, null=True)
    para_veri_exis_os_aber = models.BooleanField(blank=True, null=True)
    para_orca_seto_habi = models.BooleanField(blank=True, null=True)
    para_chek_list = models.BooleanField(blank=True, null=True)
    para_fina_nord_mags = models.BooleanField(blank=True, null=True)
    para_cecu_caix = models.BooleanField(blank=True, null=True)
    para_cont_cont_roma_entr = models.IntegerField(blank=True, null=True)
    para_redu_base_issq = models.BooleanField(blank=True, null=True)
    para_acum_itens_orca = models.BooleanField(blank=True, null=True)
    para_entr_pedi_vend = models.BooleanField(blank=True, null=True)
    para_pedi_piso_cera = models.BooleanField(blank=True, null=True)
    para_fina_data_atua = models.BooleanField(blank=True, null=True)
    para_cont_rece_tran = models.IntegerField(blank=True, null=True)
    para_cont_rece_serv = models.IntegerField(blank=True, null=True)
    para_cont_rece_rece = models.IntegerField(blank=True, null=True)
    para_cont_paga_tran = models.IntegerField(blank=True, null=True)
    para_cont_paga_serv = models.IntegerField(blank=True, null=True)
    para_cont_paga_rece = models.IntegerField(blank=True, null=True)
    para_cont_comp_made = models.IntegerField(blank=True, null=True)
    para_cecu_dav = models.IntegerField(blank=True, null=True)
    para_codi_bene_tabe = models.BooleanField(blank=True, null=True)
    para_soli_adia_pedi_comp = models.BooleanField(blank=True, null=True)
    para_envi_emai_apos_bole = models.BooleanField(blank=True, null=True)
    para_impr_icms_reti_item = models.BooleanField(blank=True, null=True)
    para_vali_data_caix = models.BooleanField(blank=True, null=True)
    para_impr_loca_item = models.BooleanField(blank=True, null=True)
    para_obri_filt_prod = models.BooleanField(blank=True, null=True)
    para_perc_cart_os = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    para_impr_item_ambi = models.BooleanField(blank=True, null=True)
    para_desc_mult_nfse = models.BooleanField(blank=True, null=True)
    para_obri_ncm_prod = models.BooleanField(blank=True, null=True)
    para_bloq_codi_cons = models.BooleanField(blank=True, null=True)
    para_gera_nfe_empr = models.BooleanField(blank=True, null=True)
    para_padr_loca = models.BooleanField(blank=True, null=True)
    para_nao_bloq_apur_icms = models.BooleanField(blank=True, null=True)
    para_codi_list_cor_climba = models.CharField(max_length=2, blank=True, null=True)
    para_codi_list_tamanho_climba = models.CharField(max_length=2, blank=True, null=True)
    para_perm_enti_com_cpf_dupl = models.BooleanField(blank=True, null=True)
    para_cecu_indi_fatu = models.BooleanField(blank=True, null=True)
    para_os_resu = models.BooleanField(blank=True, null=True)
    para_ocul_brut_impr_pedi = models.BooleanField(blank=True, null=True)
    para_aute_usua_canc_item = models.BooleanField(blank=True, null=True)
    para_desc_item_orca = models.BooleanField(blank=True, null=True)
    para_libe_calc_desc_roma = models.BooleanField(blank=True, null=True)
    para_calc_m3 = models.BooleanField(blank=True, null=True)
    para_nao_alte_st = models.BooleanField(blank=True, null=True)
    para_vers_mini = models.BooleanField(blank=True, null=True)
    para_vend_prod_lote = models.BooleanField(blank=True, null=True)
    para_atua_prec_expo_orca = models.BooleanField(blank=True, null=True)
    para_perc_maxi_desc_orca = models.BooleanField(blank=True, null=True)
    para_os_avis_baix_auto = models.BooleanField(blank=True, null=True)
    para_fili_baix_esto = models.IntegerField(blank=True, null=True)
    para_os_obri_assi_tecn = models.BooleanField(blank=True, null=True)
    para_os_devo_item = models.BooleanField(blank=True, null=True)
    para_plan_acip = models.IntegerField(blank=True, null=True)
    para_impr_codi_fabr_os = models.BooleanField(blank=True, null=True)
    para_tecn_gera_os = models.BooleanField(blank=True, null=True)
    para_cecu_conf = models.IntegerField(blank=True, null=True)
    para_cecu_cons_joia = models.IntegerField(blank=True, null=True)
    para_cecu_orca = models.IntegerField(blank=True, null=True)
    para_cecu_cons_relo = models.IntegerField(blank=True, null=True)
    para_quan_prev_orpr = models.BooleanField(blank=True, null=True)
    para_cont_mdf_cred = models.IntegerField(blank=True, null=True)
    para_cont_mdf_debi = models.IntegerField(blank=True, null=True)
    para_caix_nao_gera_fina = models.BooleanField(blank=True, null=True)
    para_pedi_comp_atua_prec_comp = models.BooleanField(blank=True, null=True)
    para_util_cont_cheq_fina = models.BooleanField(blank=True, null=True)
    para_baix_auto_titu = models.BooleanField(blank=True, null=True)
    para_desc_peve_sem_rate = models.BooleanField(blank=True, null=True)
    para_os_gene = models.BooleanField(blank=True, null=True)
    para_ocul_valo_praz = models.BooleanField(blank=True, null=True)
    para_max_desc_dinh = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    para_max_desc_cart = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    para_max_desc_cheq = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    para_max_desc_cred = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    para_max_desc_pix = models.DecimalField(max_digits=16, decimal_places=2, blank=True, null=True)
    para_info_quan_pdv = models.BooleanField(blank=True, null=True)
    para_nao_rate_desc_item_nota = models.BooleanField(blank=True, null=True)
    para_taxa_cart_piso = models.BooleanField(blank=True, null=True)
    para_orca_mult_item = models.BooleanField(blank=True, null=True)
    para_caix_ocul_docu_nfce = models.BooleanField(blank=True, null=True)
    para_cont_esto_seto = models.BooleanField()
    para_grav_bole = models.BooleanField(blank=True, null=True)
    para_valo_prom_orca = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'parametros'"""



class Parametros(models.Model):
    # ============================================================
    # 🏢 EMPRESA E SISTEMA
    # ============================================================
    empresa_id = models.IntegerField(primary_key=True, db_column="para_empr")
    empresa_responsavel_nome = models.CharField(max_length=200, db_column="para_empr_resp", blank=True, null=True)
    empresa_responsavel_cargo = models.CharField(max_length=100, db_column="para_carg", blank=True, null=True)
    empresa_data_inicio = models.DateField(db_column="para_data_inic", blank=True, null=True)
    empresa_data_fim = models.DateField(db_column="para_data_fina", blank=True, null=True)
    empresa_cnpj = models.CharField(max_length=14, db_column="para_cnpj", blank=True, null=True)
    empresa_cpf_responsavel = models.CharField(max_length=11, db_column="para_cpf", blank=True, null=True)
    empresa_telefone = models.CharField(max_length=14, db_column="para_fone", blank=True, null=True)
    empresa_fax = models.CharField(max_length=14, db_column="para_fax", blank=True, null=True)
    empresa_email = models.CharField(max_length=200, db_column="para_emai", blank=True, null=True)
    empresa_logo_expandido_danfe = models.BooleanField(db_column="para_logo_expa_danf", blank=True, null=True)
    empresa_modo_desenvolvedor = models.BooleanField(db_column="para_desa_ajud", blank=True, null=True)
    empresa_porta_matricula = models.CharField(max_length=100, db_column="para_port_matr", blank=True, null=True)
    empresa_fabricante = models.CharField(max_length=20, db_column="para_fabr", blank=True, null=True)
    empresa_marca = models.CharField(max_length=20, db_column="para_marc", blank=True, null=True)
    empresa_modelo = models.CharField(max_length=20, db_column="para_mode", blank=True, null=True)

    # ============================================================
    # 🧾 PEDIDO DE VENDA
    # ============================================================
    pedido_movimenta_estoque = models.BooleanField(db_column="para_pedi_esto", blank=True, null=True)
    pedido_requer_liberacao = models.BooleanField(db_column="para_pedi_comp_libe", blank=True, null=True)
    pedido_permite_edicao = models.BooleanField(db_column="para_pedi_mofi", blank=True, null=True)
    pedido_permite_multiplos_itens = models.BooleanField(db_column="para_pedi_mult_item", blank=True, null=True)
    pedido_duas_vias = models.BooleanField(db_column="para_pedi_duas_via", blank=True, null=True)
    pedido_resumo_consolidado = models.BooleanField(db_column="para_pedi_resu", blank=True, null=True)
    pedido_gera_nota_fiscal = models.BooleanField(db_column="para_gera_nota_pedi", blank=True, null=True)
    pedido_exige_matricula = models.BooleanField(db_column="para_pedi_matr", blank=True, null=True)
    pedido_impressao_moderno = models.BooleanField(db_column="para_pedi_impr_orca_novo_padr", blank=True, null=True)
    pedido_codigo_barras = models.BooleanField(db_column="para_pedi_brin_bar", blank=True, null=True)
    pedido_relat_acoes = models.BooleanField(db_column="para_pedi_rela_acou", blank=True, null=True)
    pedido_recebimento_automatico = models.BooleanField(db_column="para_vend_dinh_caix_gera_rece", blank=True, null=True)
    pedido_gera_financeiro = models.BooleanField(db_column="para_pedi_comp_fina", blank=True, null=True)
    pedido_movimenta_estoque_compra = models.BooleanField(db_column="para_pedi_comp_esto", blank=True, null=True)
    pedido_layout_altura = models.IntegerField(db_column="para_pedi_vend_altu", blank=True, null=True)
    pedido_exibe_razao_social = models.BooleanField(db_column="para_pedi_vend_form_raza", blank=True, null=True)
    pedido_requer_vendedor = models.BooleanField(db_column="para_obri_vend_pedi", blank=True, null=True)
    pedido_permite_cliente_bloqueado = models.BooleanField(db_column="para_alte_pedi_clie_bloq", blank=True, null=True)
    pedido_permite_preco_zero = models.BooleanField(db_column="para_perm_unit_zera_pedi", blank=True, null=True)
    pedido_calcula_st = models.BooleanField(db_column="para_calc_st_pedi", blank=True, null=True)
    pedido_itens_duplicados = models.BooleanField(db_column="para_pedi_mult_item_c", blank=True, null=True)
    pedido_cancelamento_habilitado = models.BooleanField(db_column="para_canc_pedi", blank=True, null=True)
    pedido_assinatura_impressa = models.BooleanField(db_column="para_impr_assi_pedi_vend", blank=True, null=True)
    pedido_imprime_codigo_fabrica = models.BooleanField(db_column="para_impr_codi_fabr_cupo_vend", blank=True, null=True)
    pedido_permite_alterar_parcelas = models.BooleanField(db_column="para_perm_alte_pedi_parc", blank=True, null=True)
    pedido_zera_caixa_transacao = models.BooleanField(db_column="para_tran_zera_caix", blank=True, null=True)

    # ============================================================
    # 📦 ESTOQUE
    # ============================================================
    estoque_permite_negativo = models.BooleanField(db_column="para_perm_esto_nega", blank=True, null=True)
    estoque_aviso_negativo = models.BooleanField(db_column="para_mens_esto_nega", blank=True, null=True)
    estoque_consulta_saldo = models.BooleanField(db_column="para_cons_prod_sald", blank=True, null=True)
    estoque_exibe_custo = models.BooleanField(db_column="para_prec_cust_cons_prod", blank=True, null=True)
    estoque_exibe_custo_na_consulta = models.BooleanField(db_column="para_apre_cust_cons_prod", blank=True, null=True)
    estoque_custo_gerencial = models.BooleanField(db_column="para_posi_esto_cust_gere", blank=True, null=True)
    estoque_respeita_kit = models.BooleanField(db_column="para_nao_queb_kit", blank=True, null=True)
    estoque_movimenta_os = models.BooleanField(db_column="orde_serv_esto", blank=True, null=True)
    estoque_movimenta_entrada_manual = models.BooleanField(db_column="para_esto_movi_entr", blank=True, null=True)
    estoque_sincroniza_preco = models.BooleanField(db_column="para_esto_cinc_prec", blank=True, null=True)
    estoque_consulta_carrinho = models.BooleanField(db_column="para_carr_cons_prod", blank=True, null=True)
    estoque_mensagem_estoque_pedido = models.BooleanField(db_column="para_mens_esto_pedi_orca", blank=True, null=True)

    # ============================================================
    # 💰 FINANCEIRO
    # ============================================================
    """financeiro_conta_caixa = models.IntegerField(db_column="para_cont_caix", blank=True, null=True)
    financeiro_conta_despesa_bancaria = models.IntegerField(db_column="para_cont_desp_banc", blank=True, null=True)
    financeiro_conta_iof = models.IntegerField(db_column="para_cont_iof", blank=True, null=True)
    financeiro_conta_cheque_devolvido = models.IntegerField(db_column="para_cont_cheq_devo", blank=True, null=True)
    financeiro_conta_cheque_recebido = models.IntegerField(db_column="para_cont_cheq_rece", blank=True, null=True)
    financeiro_banco_cobranca = models.IntegerField(db_column="para_banc_cobr", blank=True, null=True)
    financeiro_carteira_cobranca = models.IntegerField(db_column="para_cart_cobr", blank=True, null=True)
    financeiro_gera_boleto = models.BooleanField(db_column="para_grav_bole", blank=True, null=True)
    financeiro_impressao_mensagem_padrao_boleto = models.BooleanField(db_column="para_mens_padr_bole", blank=True, null=True)
    financeiro_impressao_boleto_nfe = models.BooleanField(db_column="para_impr_bole_nfe", blank=True, null=True)
    financeiro_data_pagamento_automatica = models.DateField(db_column="para_peri_fatu_paga", blank=True, null=True)
    financeiro_receita_conta = models.IntegerField(db_column="para_rece", blank=True, null=True)
    financeiro_receita_irrf = models.IntegerField(db_column="para_rece_irrf", blank=True, null=True)
    financeiro_conta_inss = models.IntegerField(db_column="para_inss", blank=True, null=True)
    financeiro_percentual_base_inss = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_perc_base_inss", blank=True, null=True)
    financeiro_percentual_base_irrf = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_perc_base_irrf", blank=True, null=True)
    financeiro_percentual_inss = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_perc_inss", blank=True, null=True)
    financeiro_teto_desconto_inss = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_teto_desc_inss", blank=True, null=True)
    financeiro_percentual_sest_senat = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_perc_sest_sena", blank=True, null=True)
    financeiro_percentual_base_sest_senat = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_perc_base_sest_sena", blank=True, null=True)
    financeiro_percentual_maximo_desconto = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_max_desc", blank=True, null=True)
    financeiro_permite_baixa_automatica_vendas = models.BooleanField(db_column="para_vend_baix_auto", blank=True, null=True)
    financeiro_permite_baixa_automatica_compras = models.BooleanField(db_column="para_comp_baix_auto", blank=True, null=True)
    financeiro_permite_baixa_automatica_titulos = models.BooleanField(db_column="para_baix_auto_titu", blank=True, null=True)
    financeiro_juros_recebimento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_juro_rece", blank=True, null=True)
    financeiro_multa_recebimento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_mult_rece", blank=True, null=True)
    financeiro_desconto_recebimento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_desc_rece", blank=True, null=True)
    financeiro_juros_pagamento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_juro_paga", blank=True, null=True)
    financeiro_multa_pagamento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_mult_paga", blank=True, null=True)
    financeiro_desconto_pagamento = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_desc_paga", blank=True, null=True)
    financeiro_resumo_detalhado_pagamento = models.BooleanField(db_column="para_resu_fina_deta_paga", blank=True, null=True)
    financeiro_calcula_retencao_cofins = models.BooleanField(db_column="para_calc_rete_cf", blank=True, null=True)
    financeiro_historico_contabil = models.BooleanField(db_column="para_hist_fina_cont", blank=True, null=True)
    financeiro_permite_controle_caixa = models.BooleanField(db_column="para_caix_nao_gera_fina", blank=True, null=True)
    financeiro_fechamento_caixa_validar_nota = models.BooleanField(db_column="para_fech_caix_vali_nota", blank=True, null=True)
    financeiro_exige_portador_pagamento = models.BooleanField(db_column="para_obri_port_paga", blank=True, null=True)
    financeiro_exige_situacao_pagamento = models.BooleanField(db_column="para_obri_situ_paga", blank=True, null=True)
    financeiro_exige_portador_recebimento = models.BooleanField(db_column="para_obri_port_rece", blank=True, null=True)
    financeiro_exige_situacao_recebimento = models.BooleanField(db_column="para_obri_situ_rece", blank=True, null=True)
    financeiro_conta_obrigacoes = models.BooleanField(db_column="para_cont_obri", blank=True, null=True)
    financeiro_observacao_nota_recebimento = models.BooleanField(db_column="para_obse_nota_rece", blank=True, null=True)
    financeiro_valor_promocional_orcamento = models.BooleanField(db_column="para_valo_prom_orca", blank=True, null=True)
    financeiro_cartao_frete_reposicao = models.BooleanField(db_column="para_cart_fret_repo", blank=True, null=True)
    financeiro_percentual_cartao_os = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_perc_cart_os", blank=True, null=True)

    # ============================================================
    # 🧾 FISCAL (NF / NFe / NFCe / NFSe)
    # ============================================================
    fiscal_cfop_venda_estadual = models.IntegerField(db_column="cfop_vend_esta", blank=True, null=True)
    fiscal_cfop_venda_fora_estado = models.IntegerField(db_column="cfop_vend_fora_esta", blank=True, null=True)
    fiscal_cfop_servico_estadual = models.IntegerField(db_column="cfop_serv_esta", blank=True, null=True)
    fiscal_cfop_servico_fora_estado = models.IntegerField(db_column="cfop_serv_fora_esta", blank=True, null=True)
    fiscal_cfop_venda_estadual_st = models.IntegerField(db_column="cfop_vend_esta_st", blank=True, null=True)
    fiscal_cfop_venda_fora_estado_st = models.IntegerField(db_column="cfop_vend_fora_esta_st", blank=True, null=True)
    fiscal_cfop_geral = models.IntegerField(db_column="para_cfop_gera", blank=True, null=True)
    fiscal_cfop_fora_pr = models.IntegerField(db_column="para_cfop_fora_pr", blank=True, null=True)
    fiscal_cfop_estadual_pr = models.IntegerField(db_column="para_cfop_esta_pr", blank=True, null=True)
    fiscal_cfop_nfce_venda = models.IntegerField(db_column="cfop_vend_nfce", blank=True, null=True)
    fiscal_cfop_nfce_vestuario = models.IntegerField(db_column="cfop_vest_nfce", blank=True, null=True)
    fiscal_cfop_produto_estadual = models.IntegerField(db_column="cfop_prod_esta", blank=True, null=True)
    fiscal_cfop_produto_fora_estado = models.IntegerField(db_column="cfop_prod_fora_esta", blank=True, null=True)
    fiscal_cfop_entrada_produto = models.IntegerField(db_column="cfop_entr_prod", blank=True, null=True)
    fiscal_cfop_venda_futura_estadual = models.IntegerField(db_column="para_cfop_vend_futu_esta", blank=True, null=True)
    fiscal_cfop_venda_futura_fora_estado = models.IntegerField(db_column="para_cfop_vend_futu_fora_esta", blank=True, null=True)
    fiscal_cfop_devolucao = models.IntegerField(db_column="para_cfop_devo", blank=True, null=True)
    fiscal_cfop_nfse_mode = models.IntegerField(db_column="para_mode_nfse_mode", blank=True, null=True)
    fiscal_cfop_nfse_tipo = models.IntegerField(db_column="para_mode_nfse_tipo", blank=True, null=True)
    fiscal_cfop_nfse_empresa = models.IntegerField(db_column="para_empr_nfse", blank=True, null=True)
    fiscal_permite_geracao_nfe_empresa = models.BooleanField(db_column="para_gera_nfe_empr", blank=True, null=True)
    fiscal_nota_sem_xml = models.BooleanField(db_column="para_nota_sem_xml", blank=True, null=True)
    fiscal_clonar_nota_entrada = models.BooleanField(db_column="para_clon_nota_entr", blank=True, null=True)
    fiscal_emitir_nota_pedido = models.BooleanField(db_column="para_emit_nota_pedi", blank=True, null=True)
    fiscal_imprimir_nome_fantasia_nf = models.BooleanField(db_column="para_impr_nome_fant_nf", blank=True, null=True)
    fiscal_imprimir_dupla_nfe = models.BooleanField(db_column="para_impr_dupl_nfe", blank=True, null=True)
    fiscal_obrigatorio_assinatura_nota = models.BooleanField(db_column="para_obri_assi_nota", blank=True, null=True)
    fiscal_exibir_vencimento_nfe = models.BooleanField(db_column="para_most_venc_nfe", blank=True, null=True)
    fiscal_emitir_cupom_caixa = models.BooleanField(db_column="para_emis_cupo_caix", blank=True, null=True)
    fiscal_exibir_detalhe_nf_grad = models.BooleanField(db_column="para_deta_nfee_grad", blank=True, null=True)
    fiscal_exibir_informacao_balao = models.BooleanField(db_column="para_impr_info_bala", blank=True, null=True)
    fiscal_incluir_obs_nfe = models.BooleanField(db_column="para_nfes_obse", blank=True, null=True)
    fiscal_incluir_icms_retido_item = models.BooleanField(db_column="para_impr_icms_reti_item", blank=True, null=True)
    fiscal_incluir_local_item = models.BooleanField(db_column="para_impr_loca_item", blank=True, null=True)
    fiscal_nao_imprimir_cliente_nota = models.BooleanField(db_column="para_nao_impr_clie_nota", blank=True, null=True)
    fiscal_nao_cabecalho_orcamento = models.BooleanField(db_column="para_nao_cabe_orca", blank=True, null=True)
    fiscal_permite_nfce_caixa = models.BooleanField(db_column="para_nfce_caix", blank=True, null=True)
    fiscal_custo_emissao_nf = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_cust_emis_nf", blank=True, null=True)
    fiscal_cst_icms_geral = models.CharField(max_length=3, db_column="para_cst_icms_gera", blank=True, null=True)
    fiscal_cst_pis_geral = models.CharField(max_length=2, db_column="para_cst_pis_gera", blank=True, null=True)
    fiscal_aliquota_icms_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_aliq_icms_gera", blank=True, null=True)
    fiscal_reducao_icms_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_redu_icms_gera", blank=True, null=True)
    fiscal_aliquota_icms_st_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_aliq_icms_st_gera", blank=True, null=True)
    fiscal_reducao_icms_st_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_redu_icms_st_gera", blank=True, null=True)
    fiscal_mva_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_mva_gera", blank=True, null=True)
    fiscal_aliquota_pis_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_aliq_pis_gera", blank=True, null=True)
    fiscal_cst_cofins_geral = models.CharField(max_length=2, db_column="para_cst_cofi_gera", blank=True, null=True)
    fiscal_aliquota_cofins_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_aliq_cofi_gera", blank=True, null=True)
    fiscal_cfop_geral_geracao = models.IntegerField(db_column="para_cfop_gera_fisc", blank=True, null=True)
    fiscal_imprimir_assinatura_pedido_venda = models.BooleanField(db_column="para_impr_assi_pedi_vend_fisc", blank=True, null=True)
    fiscal_exibir_cliente_nfce = models.BooleanField(db_column="para_obri_clie_vend_caix", blank=True, null=True)
    fiscal_exibir_comand_auto = models.BooleanField(db_column="para_impr_coma_auto", blank=True, null=True)
    fiscal_exibir_unidade_medida = models.BooleanField(db_column="para_most_unid_medi", blank=True, null=True)
    fiscal_exibir_produto_observacao = models.BooleanField(db_column="para_most_prod_obse", blank=True, null=True)
    fiscal_exibir_data_partilha = models.BooleanField(db_column="para_most_data_part", blank=True, null=True)
    fiscal_cfop_nfse = models.IntegerField(db_column="para_mode_nfse", blank=True, null=True)
    fiscal_cnpj_certificado = models.BooleanField(db_column="para_cnpj_cert", blank=True, null=True)
    fiscal_calcular_ibpt = models.BooleanField(db_column="para_calc_ibpt", blank=True, null=True)
    fiscal_tipo_emissao_nfse = models.IntegerField(db_column="para_tipo_emis_nfse", blank=True, null=True)
    fiscal_obrigatorio_pis_motorista = models.BooleanField(db_column="para_obri_pis_moto", blank=True, null=True)
    fiscal_obrigatorio_pis_transporte = models.BooleanField(db_column="para_obri_pis_tran", blank=True, null=True)
    fiscal_tipo_codigo_servico = models.IntegerField(db_column="para_codi_serv", blank=True, null=True)
    fiscal_operacao_cpom = models.BooleanField(db_column="para_oper_cpom_fisc", blank=True, null=True)
    fiscal_mdfe_utiliza_cte = models.BooleanField(db_column="para_mdfe_ucte", blank=True, null=True)
    fiscal_nao_bloquear_apuracao_icms = models.BooleanField(db_column="para_nao_bloq_apur_icms", blank=True, null=True)
    fiscal_exige_ncm_produto = models.BooleanField(db_column="para_obri_ncm_prod", blank=True, null=True)
    fiscal_sem_credito_icms = models.BooleanField(db_column="para_sem_cred_icms", blank=True, null=True)
    fiscal_icms_regime_geral = models.BooleanField(db_column="para_icms_regi", blank=True, null=True)
    fiscal_emitir_nf_lote = models.BooleanField(db_column="para_vend_prod_lote", blank=True, null=True)


    # ============================================================
    # 🧰 ORDEM DE SERVIÇO
    # ============================================================
    os_emitir_nfse = models.BooleanField(db_column="para_emit_nfse", blank=True, null=True)
    os_movimenta_estoque = models.BooleanField(db_column="orde_serv_esto_os", blank=True, null=True)
    os_obrigatorio_assinatura_tecnico = models.BooleanField(db_column="para_os_obri_assi_tecn", blank=True, null=True)
    os_devolve_item = models.BooleanField(db_column="para_os_devo_item", blank=True, null=True)
    os_gerar_automaticamente = models.BooleanField(db_column="para_tecn_gera_os", blank=True, null=True)
    os_multiplas_empresas = models.BooleanField(db_column="para_fech_serv_os_mult_empr", blank=True, null=True)
    os_permite_financeiro = models.BooleanField(db_column="para_perm_fina_os", blank=True, null=True)
    os_exibir_resumo = models.BooleanField(db_column="para_os_resu", blank=True, null=True)
    os_avisar_baixa_automatica = models.BooleanField(db_column="para_os_avis_baix_auto", blank=True, null=True)
    os_exibir_codigo_fabricante = models.BooleanField(db_column="para_impr_codi_fabr_os", blank=True, null=True)
    os_processo_caixa = models.BooleanField(db_column="para_os_proc_caix", blank=True, null=True)
    os_gera_nf_por_numero = models.BooleanField(db_column="para_fina_nota_pelo_nume", blank=True, null=True)
    os_mensagem_agua = models.TextField(db_column="para_ecf_mens_agua", blank=True, null=True)
    os_mensagem_trabalho = models.CharField(max_length=100, db_column="para_ecf_mens_trab", blank=True, null=True)
    os_usinagem_ativa = models.BooleanField(db_column="para_os_usin", blank=True, null=True)
    os_gestao_geral = models.BooleanField(db_column="para_os_gene", blank=True, null=True)
    os_valor_condicional = models.BooleanField(db_column="para_calc_valo_cont_os", blank=True, null=True)
    os_calcula_m3 = models.BooleanField(db_column="para_calc_m3", blank=True, null=True)
    os_setor_habilitado = models.BooleanField(db_column="para_orca_seto_habi", blank=True, null=True)
    os_checklist_ativo = models.BooleanField(db_column="para_chek_list", blank=True, null=True)
    os_gera_arquivo_bosch = models.BooleanField(db_column="para_gera_arqu_bosch", blank=True, null=True)
    os_consulta_joias = models.IntegerField(db_column="para_cecu_cons_joia", blank=True, null=True)
    os_consulta_relogios = models.IntegerField(db_column="para_cecu_cons_relo", blank=True, null=True)
    os_orcamento_centro_custo = models.IntegerField(db_column="para_cecu_orca", blank=True, null=True)
    os_centro_conf = models.IntegerField(db_column="para_cecu_conf", blank=True, null=True)
    os_quantidade_prevista = models.BooleanField(db_column="para_quan_prev_orpr", blank=True, null=True)
    os_utiliza_mdfe = models.BooleanField(db_column="para_mdfe_ucte_os", blank=True, null=True)
    os_centro_indicador_faturamento = models.BooleanField(db_column="para_cecu_indi_fatu", blank=True, null=True)

    # ============================================================
    # 💹 CUSTOS E PREÇOS
    # ============================================================
    custos_utiliza_markup = models.BooleanField(db_column="para_usa_mark_up", blank=True, null=True)
    custos_decotar_preco_compra = models.BooleanField(db_column="para_deco_prec_comp", blank=True, null=True)
    custos_atualiza_preco_compra = models.BooleanField(db_column="para_atua_prec_comp", blank=True, null=True)
    custos_atualiza_preco_orcamento_exportado = models.BooleanField(db_column="para_atua_prec_expo_orca", blank=True, null=True)
    custos_atualiza_preco_compra_pedido = models.BooleanField(db_column="para_pedi_comp_atua_prec_comp", blank=True, null=True)
    custos_utiliza_preco_deflacionado = models.BooleanField(db_column="para_tabe_defl", blank=True, null=True)
    custos_forma_calculo = models.TextField(db_column="para_form_calc_cust", blank=True, null=True)
    custos_permite_deflacao = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_defl", blank=True, null=True)
    custos_permite_correcao = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_corr", blank=True, null=True)
    custos_preco_padrao_50 = models.BooleanField(db_column="para_prec_padr_50", blank=True, null=True)
    custos_padr_margem_lucro = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_padr_marg_lucr", blank=True, null=True)
    custos_posicao_gerencial = models.BooleanField(db_column="para_posi_esto_cust_gere_pos", blank=True, null=True)
    custos_tabela_preco_percentual = models.BooleanField(db_column="para_tabe_perc", blank=True, null=True)
    custos_padrao_custo_relacionado = models.IntegerField(db_column="para_padr_cust_rela", blank=True, null=True)
    custos_calculo_st_pedido = models.BooleanField(db_column="para_calc_st_pedi_cust", blank=True, null=True)
    custos_estoque_gera_custo_gerencial = models.BooleanField(db_column="para_esto_cinc_prec_cust", blank=True, null=True)
    custos_pedido_gera_custo_gerencial = models.BooleanField(db_column="para_pedi_cust_gere", blank=True, null=True)
    custos_calcula_pelo_xml = models.BooleanField(db_column="para_calc_pelo_xml", blank=True, null=True)
    custos_padr_margem_padrao = models.DecimalField(max_digits=15, decimal_places=2, db_column="para_padr_marg_lucr_pad", blank=True, null=True)
    custos_reduzir_icms_geral = models.DecimalField(max_digits=5, decimal_places=2, db_column="para_redu_icms_gera_cust", blank=True, null=True)
    custos_permite_desc_item_peve = models.BooleanField(db_column="para_desc_item_peve", blank=True, null=True)
    custos_permite_desc_ambos = models.BooleanField(db_column="para_desc_ambo_peve", blank=True, null=True)
    custos_permite_desc_max_item = models.BooleanField(db_column="para_veri_desc_max_item", blank=True, null=True)
    custos_max_desc_dinheiro = models.DecimalField(max_digits=16, decimal_places=2, db_column="para_max_desc_dinh", blank=True, null=True)
    custos_max_desc_cartao = models.DecimalField(max_digits=16, decimal_places=2, db_column="para_max_desc_cart", blank=True, null=True)
    custos_max_desc_cheque = models.DecimalField(max_digits=16, decimal_places=2, db_column="para_max_desc_cheq", blank=True, null=True)
    custos_max_desc_credito = models.DecimalField(max_digits=16, decimal_places=2, db_column="para_max_desc_cred", blank=True, null=True)
    custos_max_desc_pix = models.DecimalField(max_digits=16, decimal_places=2, db_column="para_max_desc_pix", blank=True, null=True)
    custos_aliquota_iss = models.DecimalField(max_digits=8, decimal_places=5, db_column="para_aliq_iss", blank=True, null=True)
    custos_mostra_preco_seguro = models.BooleanField(db_column="para_most_prec_segu", blank=True, null=True)
    custos_seguro_parcelado = models.BooleanField(db_column="para_segu_parc", blank=True, null=True)
    custos_conv_metragem_cubica = models.BooleanField(db_column="para_conv_metr_cubi", blank=True, null=True)
    custos_valor_promocional_orcamento = models.BooleanField(db_column="para_valo_prom_orca_cust", blank=True, null=True)
    custos_padrao_localizacao = models.BooleanField(db_column="para_padr_loca", blank=True, null=True)
    custos_gera_codigo_barras = models.BooleanField(db_column="para_gera_code_barr", blank=True, null=True)
    custos_digitos_codigo_barras = models.IntegerField(db_column="para_digi_code_barr", blank=True, null=True)
    custos_fechamento_caixa_trans_total = models.BooleanField(db_column="para_fech_caix_tran_tota", blank=True, null=True)
    custos_mostra_valor_prazo = models.BooleanField(db_column="para_ocul_valo_praz", blank=True, null=True)
    custos_forma_uso_custo_medio = models.BooleanField(db_column="para_form_usar_cust_medi", blank=True, null=True)
    custos_utiliza_tipo_comissao_vendedor = models.BooleanField(db_column="para_util_tipo_comi_vend", blank=True, null=True)
    custos_gera_titulo_adiantamento = models.BooleanField(db_column="para_gera_titu_adia", blank=True, null=True)

        # ============================================================
    # 👤 USUÁRIO E SEGURANÇA
    # ============================================================
    usuario_codigo_atm = models.CharField(max_length=50, db_column="para_codi_atm", blank=True, null=True)
    usuario_nome_atm = models.CharField(max_length=50, db_column="para_usua_atm", blank=True, null=True)
    usuario_senha_atm = models.CharField(max_length=50, db_column="para_senh_atm", blank=True, null=True)
    usuario_permite_seguro_cte = models.BooleanField(db_column="para_perm_segu_cte", blank=True, null=True)
    usuario_verifica_motorista = models.BooleanField(db_column="para_veri_moto", blank=True, null=True)
    usuario_verifica_veiculo = models.BooleanField(db_column="para_veri_veic", blank=True, null=True)
    usuario_autoriza_cancelamento_item = models.BooleanField(db_column="para_aute_usua_canc_item", blank=True, null=True)
    usuario_permite_alterar_cliente_bloqueado = models.BooleanField(db_column="para_alte_pedi_clie_bloq_user", blank=True, null=True)
    usuario_exige_vendedor = models.BooleanField(db_column="para_obri_vend_nota", blank=True, null=True)
    usuario_exige_comanda_cpf = models.BooleanField(db_column="para_obri_coma_cpf", blank=True, null=True)
    usuario_exige_comanda_rg = models.BooleanField(db_column="para_obri_coma_rg", blank=True, null=True)
    usuario_utiliza_comanda = models.BooleanField(db_column="para_util_coma", blank=True, null=True)
    usuario_permite_desc_comissao = models.BooleanField(db_column="para_desc_dsto_comi_vend", blank=True, null=True)
    usuario_permite_desc_comissao_peve = models.BooleanField(db_column="para_desc_item_peve_user", blank=True, null=True)
    usuario_requer_login_seguro = models.BooleanField(db_column="para_conf_audi", blank=True, null=True)
    usuario_exige_filtragem_produtos = models.BooleanField(db_column="para_obri_filt_prod", blank=True, null=True)
    usuario_exige_centro_custo_pagamento = models.BooleanField(db_column="para_obri_cecu_paga", blank=True, null=True)
    usuario_exige_centro_custo_venda = models.BooleanField(db_column="para_obri_cecu_vend", blank=True, null=True)
    usuario_exige_inscricao_venda = models.BooleanField(db_column="para_obri_insc_enti_vend", blank=True, null=True)
    usuario_permite_cadastro_entidade_sem_cnpj = models.BooleanField(db_column="para_perm_enti_sem_cnpj", blank=True, null=True)
    usuario_permite_cadastro_entidade_cnpj_duplicado = models.BooleanField(db_column="para_perm_enti_com_cnpj_dupl", blank=True, null=True)
    usuario_permite_cadastro_entidade_cpf_duplicado = models.BooleanField(db_column="para_perm_enti_com_cpf_dupl", blank=True, null=True)
    usuario_exige_nascimento_fone = models.BooleanField(db_column="para_obri_nasc_fone_enti", blank=True, null=True)
    usuario_verifica_titulos_vencidos = models.BooleanField(db_column="para_veri_titu_venc", blank=True, null=True)
    usuario_mostra_titulos_vencidos = models.BooleanField(db_column="para_most_titu_venc", blank=True, null=True)
    usuario_mensagem_bloqueio_automatica = models.CharField(max_length=60, db_column="para_mens_bloq_auto", blank=True, null=True)
    usuario_nao_utiliza_controle_cheque_caixa = models.BooleanField(db_column="para_nusa_ctrl_cheq_caix", blank=True, null=True)
    usuario_controle_projeto = models.BooleanField(db_column="para_ctrl_proj", blank=True, null=True)
    usuario_permite_projeto = models.BooleanField(db_column="para_ctrl_proj_perm", blank=True, null=True)
    usuario_exibe_informacoes_quantidade_pdv = models.BooleanField(db_column="para_info_quan_pdv", blank=True, null=True)
    usuario_nao_rateia_desconto_item_nota = models.BooleanField(db_column="para_nao_rate_desc_item_nota", blank=True, null=True)
    usuario_taxa_cartao_piso = models.BooleanField(db_column="para_taxa_cart_piso", blank=True, null=True)
    usuario_mesa_obrigatoria_balcao = models.BooleanField(db_column="para_mesa_obri_bar", blank=True, null=True)
    usuario_exibe_modo_desenvolvedor = models.BooleanField(db_column="para_desa_prot", blank=True, null=True)

    # ============================================================
    # 🔗 INTEGRAÇÕES E AUTOMAÇÕES
    # ============================================================
    integracao_mdfe_ativo = models.BooleanField(db_column="para_mdfe_ucte_ativo", blank=True, null=True)
    integracao_emitir_nf_pedido = models.BooleanField(db_column="para_emit_nota_pedi_int", blank=True, null=True)
    integracao_mercadolivre = models.BooleanField(db_column="para_inte_meus_pedi_ml", blank=True, null=True)
    integracao_mdfe_automatico = models.BooleanField(db_column="para_mdfe_ucte_auto", blank=True, null=True)
    integracao_gera_arquivo_bosch = models.BooleanField(db_column="para_gera_arqu_bosch_int", blank=True, null=True)
    integracao_gera_codigo_barras = models.BooleanField(db_column="para_gera_code_barr_int", blank=True, null=True)
    integracao_envia_email_apos_boleto = models.BooleanField(db_column="para_envi_emai_apos_bole", blank=True, null=True)
    integracao_nao_envia_xml = models.BooleanField(db_column="para_nao_envi_xml", blank=True, null=True)
    integracao_api_movidesk = models.BooleanField(db_column="para_fina_nord_mags", blank=True, null=True)
    integracao_mdf_utiliza_cte = models.BooleanField(db_column="para_mdfe_ucte_mdf", blank=True, null=True)
    integracao_automacao_financeira = models.BooleanField(db_column="para_fina_data_atua", blank=True, null=True)
    integracao_importacao_xml = models.BooleanField(db_column="para_calc_pelo_xml_imp", blank=True, null=True)
    integracao_exportacao_xml = models.BooleanField(db_column="para_nao_envi_xml_exp", blank=True, null=True)
    integracao_sistema_externo = models.BooleanField(db_column="para_expu_para", blank=True, null=True)
    integracao_mercadopago = models.BooleanField(db_column="para_inte_meus_pedi_mp", blank=True, null=True)
    integracao_repositorio_certificados = models.CharField(max_length=255, db_column="para_cert_fret_repo", blank=True, null=True)
    integracao_fretamento_certificado = models.CharField(max_length=255, db_column="para_cert_fret_repo_fret", blank=True, null=True)
    integracao_frete_reposicao = models.BooleanField(db_column="para_cart_fret_repo_int", blank=True, null=True)
    integracao_portal_pagamento = models.BooleanField(db_column="para_pag_for", blank=True, null=True)
    integracao_liberacao_automatica_financeiro = models.BooleanField(db_column="para_libe_veri_fina", blank=True, null=True)
    integracao_envio_automacoes = models.BooleanField(db_column="para_expu", blank=True, null=True)
    integracao_uso_banco_digital = models.BooleanField(db_column="para_auto_dda", blank=True, null=True)
    integracao_api_interna = models.BooleanField(db_column="para_inte_meus_pedi_api", blank=True, null=True)
    integracao_uso_mecapdv = models.BooleanField(db_column="para_meca_pdv", blank=True, null=True)
    integracao_verifica_existencia_os_aberta = models.BooleanField(db_column="para_veri_exis_os_aber", blank=True, null=True)
    integracao_envia_dados_bi = models.BooleanField(db_column="para_util_conf_vend", blank=True, null=True)
    integracao_repositorio_movidesk = models.BooleanField(db_column="para_fina_nord_mags_repo", blank=True, null=True)
    integracao_sincroniza_estoque = models.BooleanField(db_column="para_esto_cinc_prec_sync", blank=True, null=True)
    integracao_controla_fluxo_vendas = models.BooleanField(db_column="para_vend_proc_caix", blank=True, null=True)
    integracao_envia_dados_contabilidade = models.BooleanField(db_column="para_hist_fina_cont_int", blank=True, null=True)
    integracao_gera_nf_automaticamente = models.BooleanField(db_column="para_gera_nota_pedi_auto", blank=True, null=True)
    integracao_api_interna_pedidos = models.BooleanField(db_column="para_inte_meus_pedi_int", blank=True, null=True)
    integracao_relatorio_dashboard = models.BooleanField(db_column="para_util_conf_vend_dash", blank=True, null=True)
    integracao_tipo_comissao_vendedor = models.BooleanField(db_column="para_util_tipo_comi_vend_int", blank=True, null=True)
    integracao_controle_financeiro_projetos = models.BooleanField(db_column="para_cont_paga_proj_cecu", blank=True, null=True)
    integracao_automacao_recalculo = models.BooleanField(db_column="para_calc_rete_cf_auto", blank=True, null=True)
    integracao_sincroniza_produtos = models.BooleanField(db_column="para_pedi_rela_acou_sync", blank=True, null=True)
    integracao_envia_emails = models.BooleanField(db_column="para_envi_emai_apos_bole_int", blank=True, null=True)
    integracao_integra_api_externa = models.BooleanField(db_column="para_expu_para_ext", blank=True, null=True)
    integracao_bloqueia_exportacao = models.BooleanField(db_column="para_expu_bloq", blank=True, null=True)
    integracao_utiliza_meios_online = models.BooleanField(db_column="para_meos_1", blank=True, null=True)
    integracao_exibe_meio_pagamento_2 = models.TextField(db_column="para_meos_2", blank=True, null=True)

"""


    class Meta:
        managed = False
        db_table = "parametros"
        verbose_name = "Parâmetro"
        verbose_name_plural = "Parâmetros"