# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centrodecustos',
            fields=[
                ('cecu_empr', models.IntegerField()),
                ('cecu_redu', models.IntegerField(primary_key=True, serialize=False)),
                ('cecu_niv1', models.IntegerField(blank=True, null=True)),
                ('cecu_expa', models.CharField(blank=True, max_length=60, null=True)),
                ('cecu_grup', models.CharField(blank=True, max_length=60, null=True)),
                ('cecu_nive', models.IntegerField(blank=True, null=True)),
                ('cecu_anal', models.CharField(blank=True, max_length=1, null=True)),
                ('cecu_natu', models.CharField(blank=True, max_length=2, null=True)),
                ('cecu_refe', models.CharField(blank=True, max_length=60, null=True)),
                ('cecu_dati', models.DateField(blank=True, null=True)),
                ('cecu_data', models.DateField(blank=True, null=True)),
                ('cecu_inat', models.BooleanField(blank=True, null=True)),
                ('cecu_data_inat', models.DateField(blank=True, null=True)),
                ('cecu_obse', models.TextField(blank=True, null=True)),
                ('cecu_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('cecu_dre', models.CharField(blank=True, max_length=2, null=True)),
                ('cecu_redu_plan', models.IntegerField(blank=True, null=True)),
                ('cecu_prod', models.CharField(blank=True, max_length=20, null=True)),
                ('cecu_situ', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'centrodecustos',
                'managed': False,
            },
        ),
    ]
