# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarCobranca',
            fields=[
                ('empresa', models.IntegerField()),
                ('filial', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_email', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_titulo', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=5)),
                ('parcela', models.CharField(max_length=3)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forma_recebimento_codigo', models.CharField(max_length=2)),
                ('forma_recebimento_nome', models.CharField(max_length=50)),
                ('linha_digitavel', models.CharField(blank=True, max_length=255, null=True)),
                ('url_boleto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'enviarcobranca',
                'managed': False,
            },
        ),
    ]
