# Generated by Django 2.2.28 on 2025-07-14 16:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_acao', models.CharField(choices=[('GET', 'Consulta'), ('POST', 'Criação'), ('PUT', 'Atualização'), ('PATCH', 'Atualização Parcial'), ('DELETE', 'Exclusão')], max_length=10)),
                ('url', models.TextField()),
                ('ip', models.GenericIPAddressField(null=True)),
                ('navegador', models.CharField(max_length=255)),
                ('dados', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dados_antes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dados_depois', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('campos_alterados', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(db_index=True, max_length=100, null=True)),
                ('licenca', models.CharField(db_index=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'db_table': 'auditoria_logacao',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['empresa', 'licenca', 'data_hora'], name='auditoria_l_empresa_f6ee85_idx'),
        ),
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['usuario', 'data_hora'], name='auditoria_l_usuario_b81e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['modelo', 'objeto_id'], name='auditoria_l_modelo_54c59b_idx'),
        ),
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['tipo_acao', 'data_hora'], name='auditoria_l_tipo_ac_c74951_idx'),
        ),
    ]
