# fly.toml app configuration file generated for mobile-sps on 2025-08-05T09:13:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mobile-sps'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  DJANGO_SETTINGS_MODULE = 'core.settings'
  SECRET_KEY = 'sua-chave-secreta'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  
  min_machines_running = 1    # Garante que pelo menos 1 estará rodando

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
