# backend/render.yaml
services:
  - type: web
    name: mobile-sps-backend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: '' # vazio pq o Docker já cuida
    startCommand: '' # também vazio
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: '0'
      - key: SECRET_KEY
        value: sua-secret-key
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        value: postgres://usuario:senha@host:porta/nomebanco
