# Generated by Django 5.2 on 2025-04-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entidades', '0001_initial'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCasamento',
            fields=[
                ('list_empr', models.IntegerField(verbose_name='Empresa')),
                ('list_fili', models.IntegerField(verbose_name='Filial')),
                ('list_nume', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('list_data', models.DateField(verbose_name='Data')),
                ('list_stat', models.CharField(choices=[('0', 'Aberta'), ('1', 'Aguardando cliente'), ('2', 'Finalizada'), ('3', 'Cancelada')], default='0', max_length=1, verbose_name='Status')),
                ('list_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entidades.entidades')),
            ],
            options={
                'db_table': 'lista_casamento',
            },
        ),
        migrations.CreateModel(
            name='ItensListaCasamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_comp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('item_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos')),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='listacasamento.listacasamento')),
            ],
            options={
                'db_table': 'itens_lista_casamento',
            },
        ),
    ]
