# Generated by Django 2.2.28 on 2025-04-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listacasamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenslistacasamento',
            name='item_empr',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itenslistacasamento',
            name='item_fili',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itenslistacasamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itenslistacasamento',
            name='item_list',
            field=models.ForeignKey(db_column='item_list', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='listacasamento.ListaCasamento'),
        ),
        migrations.AlterField(
            model_name='itenslistacasamento',
            name='item_prod',
            field=models.ForeignKey(db_column='item_prod', on_delete=django.db.models.deletion.CASCADE, to='Produtos.Produtos'),
        ),
    ]
