# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listacasamento', '0002_auto_20250424_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenslistacasamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='listacasamento',
            options={'managed': False, 'verbose_name': 'Lista de Casamento', 'verbose_name_plural': 'Listas de Casamento'},
        ),
    ]
