# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('empresa_id', models.IntegerField(db_column='para_empr', primary_key=True, serialize=False)),
                ('empresa_responsavel_nome', models.CharField(blank=True, db_column='para_empr_resp', max_length=200, null=True)),
                ('empresa_responsavel_cargo', models.CharField(blank=True, db_column='para_carg', max_length=100, null=True)),
                ('empresa_data_inicio', models.DateField(blank=True, db_column='para_data_inic', null=True)),
                ('empresa_data_fim', models.DateField(blank=True, db_column='para_data_fina', null=True)),
                ('empresa_cnpj', models.CharField(blank=True, db_column='para_cnpj', max_length=14, null=True)),
                ('empresa_cpf_responsavel', models.CharField(blank=True, db_column='para_cpf', max_length=11, null=True)),
                ('empresa_telefone', models.CharField(blank=True, db_column='para_fone', max_length=14, null=True)),
                ('empresa_fax', models.CharField(blank=True, db_column='para_fax', max_length=14, null=True)),
                ('empresa_email', models.CharField(blank=True, db_column='para_emai', max_length=200, null=True)),
                ('empresa_logo_expandido_danfe', models.BooleanField(blank=True, db_column='para_logo_expa_danf', null=True)),
                ('empresa_modo_desenvolvedor', models.BooleanField(blank=True, db_column='para_desa_ajud', null=True)),
                ('empresa_porta_matricula', models.CharField(blank=True, db_column='para_port_matr', max_length=100, null=True)),
                ('empresa_fabricante', models.CharField(blank=True, db_column='para_fabr', max_length=20, null=True)),
                ('empresa_marca', models.CharField(blank=True, db_column='para_marc', max_length=20, null=True)),
                ('empresa_modelo', models.CharField(blank=True, db_column='para_mode', max_length=20, null=True)),
                ('pedido_movimenta_estoque', models.BooleanField(blank=True, db_column='para_pedi_esto', null=True)),
                ('pedido_requer_liberacao', models.BooleanField(blank=True, db_column='para_pedi_comp_libe', null=True)),
                ('pedido_permite_edicao', models.BooleanField(blank=True, db_column='para_pedi_mofi', null=True)),
                ('pedido_permite_multiplos_itens', models.BooleanField(blank=True, db_column='para_pedi_mult_item', null=True)),
                ('pedido_duas_vias', models.BooleanField(blank=True, db_column='para_pedi_duas_via', null=True)),
                ('pedido_resumo_consolidado', models.BooleanField(blank=True, db_column='para_pedi_resu', null=True)),
                ('pedido_gera_nota_fiscal', models.BooleanField(blank=True, db_column='para_gera_nota_pedi', null=True)),
                ('pedido_exige_matricula', models.BooleanField(blank=True, db_column='para_pedi_matr', null=True)),
                ('pedido_impressao_moderno', models.BooleanField(blank=True, db_column='para_pedi_impr_orca_novo_padr', null=True)),
                ('pedido_codigo_barras', models.BooleanField(blank=True, db_column='para_pedi_brin_bar', null=True)),
                ('pedido_relat_acoes', models.BooleanField(blank=True, db_column='para_pedi_rela_acou', null=True)),
                ('pedido_recebimento_automatico', models.BooleanField(blank=True, db_column='para_vend_dinh_caix_gera_rece', null=True)),
                ('pedido_gera_financeiro', models.BooleanField(blank=True, db_column='para_pedi_comp_fina', null=True)),
                ('pedido_movimenta_estoque_compra', models.BooleanField(blank=True, db_column='para_pedi_comp_esto', null=True)),
                ('pedido_layout_altura', models.IntegerField(blank=True, db_column='para_pedi_vend_altu', null=True)),
                ('pedido_exibe_razao_social', models.BooleanField(blank=True, db_column='para_pedi_vend_form_raza', null=True)),
                ('pedido_requer_vendedor', models.BooleanField(blank=True, db_column='para_obri_vend_pedi', null=True)),
                ('pedido_permite_cliente_bloqueado', models.BooleanField(blank=True, db_column='para_alte_pedi_clie_bloq', null=True)),
                ('pedido_permite_preco_zero', models.BooleanField(blank=True, db_column='para_perm_unit_zera_pedi', null=True)),
                ('pedido_calcula_st', models.BooleanField(blank=True, db_column='para_calc_st_pedi', null=True)),
                ('pedido_itens_duplicados', models.BooleanField(blank=True, db_column='para_pedi_mult_item_c', null=True)),
                ('pedido_cancelamento_habilitado', models.BooleanField(blank=True, db_column='para_canc_pedi', null=True)),
                ('pedido_assinatura_impressa', models.BooleanField(blank=True, db_column='para_impr_assi_pedi_vend', null=True)),
                ('pedido_imprime_codigo_fabrica', models.BooleanField(blank=True, db_column='para_impr_codi_fabr_cupo_vend', null=True)),
                ('pedido_permite_alterar_parcelas', models.BooleanField(blank=True, db_column='para_perm_alte_pedi_parc', null=True)),
                ('pedido_zera_caixa_transacao', models.BooleanField(blank=True, db_column='para_tran_zera_caix', null=True)),
                ('estoque_permite_negativo', models.BooleanField(blank=True, db_column='para_perm_esto_nega', null=True)),
                ('estoque_aviso_negativo', models.BooleanField(blank=True, db_column='para_mens_esto_nega', null=True)),
                ('estoque_consulta_saldo', models.BooleanField(blank=True, db_column='para_cons_prod_sald', null=True)),
                ('estoque_exibe_custo', models.BooleanField(blank=True, db_column='para_prec_cust_cons_prod', null=True)),
                ('estoque_exibe_custo_na_consulta', models.BooleanField(blank=True, db_column='para_apre_cust_cons_prod', null=True)),
                ('estoque_custo_gerencial', models.BooleanField(blank=True, db_column='para_posi_esto_cust_gere', null=True)),
                ('estoque_respeita_kit', models.BooleanField(blank=True, db_column='para_nao_queb_kit', null=True)),
                ('estoque_movimenta_os', models.BooleanField(blank=True, db_column='orde_serv_esto', null=True)),
                ('estoque_movimenta_entrada_manual', models.BooleanField(blank=True, db_column='para_esto_movi_entr', null=True)),
                ('estoque_sincroniza_preco', models.BooleanField(blank=True, db_column='para_esto_cinc_prec', null=True)),
                ('estoque_consulta_carrinho', models.BooleanField(blank=True, db_column='para_carr_cons_prod', null=True)),
                ('estoque_mensagem_estoque_pedido', models.BooleanField(blank=True, db_column='para_mens_esto_pedi_orca', null=True)),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
                'db_table': 'parametros',
                'managed': False,
            },
        ),
    ]
