# Generated by Django 2.2.28 on 2025-05-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaGlobal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lice_nome', models.CharField(max_length=255)),
                ('lice_docu', models.CharField(max_length=20)),
                ('lice_slug', models.CharField(max_length=255, unique=True)),
                ('lice_stat', models.BooleanField(default=True)),
                ('modulo_dashboard', models.BooleanField(default=False)),
                ('modulo_entidades', models.BooleanField(default=False)),
                ('modulo_usuarios', models.BooleanField(default=False)),
                ('modulo_licencas', models.BooleanField(default=False)),
                ('modulo_listacasamento', models.BooleanField(default=False)),
                ('modulo_orcamentos', models.BooleanField(default=False)),
                ('modulo_pedidos', models.BooleanField(default=False)),
                ('modulo_entradas_estoque', models.BooleanField(default=False)),
                ('modulo_saida_estoque', models.BooleanField(default=False)),
                ('modulo_produtos', models.BooleanField(default=False)),
                ('lice_data_cria', models.DateTimeField(auto_now_add=True)),
                ('lice_data_atlz', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licença Global',
                'verbose_name_plural': 'Licenças Globais',
                'db_table': 'licencasglobal',
                'ordering': ['lice_nome'],
            },
        ),
    ]
