# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osexterna',
            fields=[
                ('osex_empr', models.IntegerField(db_column='osex_empr', verbose_name='Empresa')),
                ('osex_fili', models.IntegerField(db_column='osex_fili', verbose_name='Filial')),
                ('osex_codi', models.IntegerField(db_column='osex_codi', primary_key=True, serialize=False, verbose_name='Código')),
                ('osex_clie', models.IntegerField(blank=True, db_column='osex_clie', null=True, verbose_name='Cliente')),
                ('osex_resp', models.IntegerField(blank=True, db_column='osex_resp', null=True, verbose_name='Responsável')),
                ('osex_valo_tota', models.DecimalField(blank=True, db_column='osex_valo_tota', decimal_places=2, max_digits=16, null=True, verbose_name='Valor Total')),
                ('osex_data_aber', models.DateField(blank=True, db_column='osex_data_aber', null=True, verbose_name='Data Abertura')),
                ('osex_data_fech', models.DateField(blank=True, db_column='osex_data_fech', null=True, verbose_name='Data Fechamento')),
                ('osex_canc_just', models.CharField(blank=True, db_column='osex_canc_just', max_length=255, null=True, verbose_name='Justificativa Cancelamento')),
                ('osex_canc_usua', models.IntegerField(blank=True, db_column='osex_canc_usua', null=True, verbose_name='Usuário Cancelamento')),
                ('osex_stat', models.IntegerField(blank=True, choices=[(0, 'Aberta'), (1, 'Em assinatura'), (2, 'Assinada'), (3, 'Cancelada'), (4, 'Finalizada')], db_column='osex_stat', null=True, verbose_name='Status')),
                ('osex_usua', models.IntegerField(blank=True, db_column='osex_usua', null=True, verbose_name='Usuário')),
                ('osex_ende', models.CharField(blank=True, db_column='osex_ende', max_length=255, null=True, verbose_name='Endereço')),
                ('osex_ende_nume', models.CharField(blank=True, db_column='osex_ende_nume', max_length=10, null=True, verbose_name='Número')),
                ('osex_bair', models.CharField(blank=True, db_column='osex_bair', max_length=60, null=True, verbose_name='Bairro')),
                ('osex_cida', models.CharField(blank=True, db_column='osex_cida', max_length=60, null=True, verbose_name='Cidade')),
                ('osex_clau', models.CharField(blank=True, db_column='osex_clau', max_length=1, null=True, verbose_name='Cláusula')),
                ('osex_km_inic', models.DecimalField(blank=True, db_column='osex_km_inic', decimal_places=2, max_digits=16, null=True, verbose_name='Km Inicial')),
                ('osex_km_tota', models.DecimalField(blank=True, db_column='osex_km_tota', decimal_places=2, max_digits=16, null=True, verbose_name='Km Total')),
                ('osex_assi_clie', models.TextField(blank=True, db_column='osex_assi_clie', null=True, verbose_name='Assinatura Cliente')),
                ('osex_assi_oper', models.TextField(blank=True, db_column='osex_assi_oper', null=True, verbose_name='Assinatura Operador')),
            ],
            options={
                'db_table': 'osexterna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicososexterna',
            fields=[
                ('serv_empr', models.IntegerField()),
                ('serv_fili', models.IntegerField()),
                ('serv_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('serv_quan', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_valo_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_valo_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_temp_esti', models.TimeField(blank=True, null=True)),
                ('serv_os', models.IntegerField()),
                ('serv_comp', models.TextField(blank=True, null=True)),
                ('serv_sequ', models.IntegerField(primary_key=True, serialize=False)),
                ('serv_conc', models.BooleanField(blank=True, null=True)),
                ('serv_temp_util', models.TimeField(blank=True, null=True)),
                ('serv_km_said', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_km_cheg', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_km_reto', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_km_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serv_data_etap', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicososexterna',
                'managed': False,
            },
        ),
    ]
