# core/fiscal/defaults_cfop.py

def deduzir_defaults_cfop(cfop: str):
    """
    Regras base por CFOP (sem considerar regime).
    - 1.xxx / 2.xxx = Entrada
    - 5.xxx / 6.xxx = Saída
    - Final 05 = ST
    - Final 49 / 99 = operações diversas (geralmente PIS/COFINS)
    - 6.xxx = pode gerar DIFAL (interestadual)
    """
    c = str(cfop).strip()

    icms = False
    ipi = False
    pis_cofins = False
    st = False
    difal = False
    cbs = False
    ibs = False

    # ENTRADA
    if c.startswith(("1", "2")):
        icms = True
        pis_cofins = True

    # SAÍDA
    if c.startswith(("5", "6")):
        icms = True
        pis_cofins = True

    # IPI (operações típicas de indústria / remessa)
    if c.endswith(("01", "02", "04", "05", "51", "52", "54")):
        ipi = True

    # ST (Substituição Tributária)
    if c.endswith(("05", "06", "65", "66", "67", "68")):
        st = True

    # DIFAL
    if c.startswith("6"):
        difal = True

    # PIS/COFINS operações diversas
    if c.endswith(("49", "99")):
        pis_cofins = True

    return dict(
        icms=icms,
        ipi=ipi,
        pis_cofins=pis_cofins,
        st=st,
        difal=difal,
        cbs=cbs,
        ibs=ibs,
    )


def aplicar_regime(defaults: dict, regime: str | None):
    """
    regime:
    '1' = Simples Nacional
    '2' = Simples com Excesso
    '3' = Regime Normal
    """

    if not regime:
        return defaults

    regime = str(regime)

    # Simples Nacional: em regra NÃO destaca ICMS/PIS/COFINS na NF-e (CST 102, etc.)
    if regime == "1":
        defaults["icms"] = False
        defaults["ipi"] = False
        defaults["pis_cofins"] = False
        defaults["cbs"] = False
        defaults["ibs"] = False
        # ST e DIFAL podem continuar conforme CFOP

    # Simples com excesso de limite: pode voltar a destacar ICMS, mas PIS/COFINS ainda é delicado
    elif regime == "2":
        defaults["icms"] = defaults.get("icms", False)
        defaults["pis_cofins"] = False  # normalmente continua simplificado
        defaults["ipi"] = False

    # Regime normal: usa regras bases
    elif regime == "3":
        # mantém defaults como estão
        pass

    return defaults


def deduzir_defaults(cfop: str, regime: str | None = None):
    base = deduzir_defaults_cfop(cfop)
    return aplicar_regime(base, regime)


CFOP_DEFAULTS = {
    "1101": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1102": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1111": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1113": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1116": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1117": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1118": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1120": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1121": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1122": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1124": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1125": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1126": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1128": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1151": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1152": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1153": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1154": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1201": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1202": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1203": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1204": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1205": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1206": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1207": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1208": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1209": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1251": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1252": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1253": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1254": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1255": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1256": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1257": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1301": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1302": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1303": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1304": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1305": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1306": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1351": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1352": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1353": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1354": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1355": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1356": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1360": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1401": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1403": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1406": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1407": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1408": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1409": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1410": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1411": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1414": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1415": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1451": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1452": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1501": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1503": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1504": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1505": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1506": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1551": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1552": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1553": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1554": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1555": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1556": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1557": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1601": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1602": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1603": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1604": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1605": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1651": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1652": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1653": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1658": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1659": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1660": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1661": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1662": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1663": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1664": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1901": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1902": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1903": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1904": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1905": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1906": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "1907": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1908": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1909": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1910": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1911": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1912": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1913": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1914": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1915": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1916": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1917": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1918": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1919": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1920": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1921": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1922": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1923": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1924": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1925": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1926": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1931": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1932": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1933": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1934": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "1949": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2101": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2102": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2111": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2113": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2116": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2117": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2118": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2120": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2121": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2653": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2122": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2124": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2125": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2126": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2128": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2151": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2152": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2153": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2154": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2201": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2202": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2203": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2204": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2205": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2206": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2207": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2208": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2209": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2251": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2252": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2253": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2254": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2255": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2256": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2257": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2301": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2302": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2303": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2304": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2305": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2306": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2351": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2352": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2353": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2354": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2355": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2356": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2401": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2403": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2406": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2407": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2408": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2409": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2410": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2411": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2414": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2415": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2501": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2503": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2504": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2505": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2506": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2551": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2552": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2553": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2554": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2555": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2556": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2557": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2603": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2651": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2652": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "6905": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "2658": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2659": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2660": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2661": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2662": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2663": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2664": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2901": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2902": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2903": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2904": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2905": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2906": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "2907": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2908": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2909": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2910": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2911": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2912": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2913": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2914": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2915": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2916": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2917": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2918": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2919": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2920": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2921": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2922": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2923": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2924": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2925": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2931": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2932": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2933": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2934": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "2949": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3101": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3102": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3126": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3127": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3128": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3201": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3202": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3205": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "3206": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "3207": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3211": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3217": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3251": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3301": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3351": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3352": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3353": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3354": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3355": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3356": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3503": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3551": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3553": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3556": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3651": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3652": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3653": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3930": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "3949": {'icms': False, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5101": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5102": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5103": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5104": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5105": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5106": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5109": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5110": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5111": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5112": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5113": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5114": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5115": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5116": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5117": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5118": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5119": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5120": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5122": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5123": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5124": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5125": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5151": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5152": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5153": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5155": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5156": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5201": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5202": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5205": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5206": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5207": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5208": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5209": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5210": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5251": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5252": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5253": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5254": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5255": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5256": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5257": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5258": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5301": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5302": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5303": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5304": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5305": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5306": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5307": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5351": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5352": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5353": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5354": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5355": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5356": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5357": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5359": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5360": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5401": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5402": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5403": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5405": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "6303": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "5408": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5409": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5410": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5411": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5412": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5413": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5414": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5415": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5451": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5501": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5502": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5503": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5504": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5505": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5551": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5552": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5553": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5554": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5555": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5556": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5557": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5601": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5602": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5603": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5605": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5606": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5651": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5652": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5653": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5654": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5655": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5656": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5657": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5658": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5659": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5660": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5661": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5662": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5663": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5664": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5665": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5666": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5667": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5901": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5902": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5903": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5904": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5905": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5906": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "5907": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5908": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5909": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5910": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5911": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5912": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5913": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5914": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5915": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5916": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5917": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5918": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5919": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5920": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5921": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "6904": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "5922": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5923": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5924": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5925": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5926": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5927": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5928": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5929": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5931": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5932": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5933": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5934": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "5949": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "6101": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6102": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6103": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6104": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6105": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6106": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6107": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6108": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6109": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6110": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6111": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6112": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6113": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6114": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6115": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6116": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6117": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6118": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6119": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6120": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6122": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6123": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6124": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6125": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6151": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6152": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6153": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6155": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6156": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6201": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6202": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6205": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6206": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6207": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6208": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6209": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6210": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6251": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6252": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6253": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6254": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6255": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6256": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6257": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6258": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6301": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6302": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6304": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6305": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6306": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6307": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6351": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6352": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6353": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6354": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6355": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6356": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6357": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6359": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6360": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6401": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6402": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6403": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6404": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6408": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6409": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6410": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6411": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6412": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6413": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6414": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6415": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6501": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6502": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6503": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6504": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6505": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6551": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6552": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6553": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6554": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6555": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6556": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6557": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6603": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6651": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6652": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6653": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6654": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6655": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6656": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6657": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6658": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6659": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6660": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6661": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6662": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6663": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6664": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6665": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6666": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6667": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6901": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6902": {'icms': True, 'ipi': True, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6903": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6906": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': True, 'difal': True, 'cbs': False, 'ibs': False},
    "6907": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6908": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6909": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6910": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6911": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6912": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6913": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6914": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6915": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6916": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6917": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6918": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6919": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6920": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6921": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6922": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6923": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6924": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6925": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6929": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6931": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6932": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6933": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6934": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "6949": {'icms': True, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': True, 'cbs': False, 'ibs': False},
    "7101": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7102": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7105": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "7106": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "7127": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7201": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7202": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7205": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "7206": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "7207": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7210": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7211": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7251": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7301": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7358": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7501": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7551": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7553": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7556": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7651": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7654": {'icms': False, 'ipi': True, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7667": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': True, 'difal': False, 'cbs': False, 'ibs': False},
    "7930": {'icms': False, 'ipi': False, 'pis_cofins': False, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
    "7949": {'icms': False, 'ipi': False, 'pis_cofins': True, 'st': False, 'difal': False, 'cbs': False, 'ibs': False},
}
