# Generated by Django 2.2.28 on 2025-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantacaoTela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.IntegerField(default=1)),
                ('Filial', models.IntegerField(default=1)),
                ('cliente', models.CharField(max_length=120)),
                ('modulo', models.CharField(choices=[('cadastro', 'Cadastros'), ('estoque', 'Estoque'), ('compras', 'Compras'), ('vendas', 'Vendas'), ('financeiro', 'Financeiro'), ('agricola', 'Agrícola'), ('os', 'Ordem de Serviço'), ('transportes', 'Transportes'), ('confeccao', 'Confecção'), ('materiais', 'Controle de Materiais')], max_length=30)),
                ('tela', models.CharField(max_length=100)),
                ('implantador', models.CharField(max_length=120)),
                ('data_implantacao', models.DateField()),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='nao_iniciado', max_length=20)),
                ('treinado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
