# Generated by Django 2.2.28 on 2025-05-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implantacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='implantacaotela',
            table='implantacoes',
        ),
    ]
