# Generated by Django 2.2.28 on 2025-05-26 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implantacao', '0002_auto_20250525_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implantacaotela',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='implantacaotela',
            name='tela',
        ),
        migrations.AddField(
            model_name='implantacaotela',
            name='modulos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='implantacaotela',
            name='telas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
