# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implantacao', '0003_auto_20250526_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implantacaotela',
            options={'managed': False},
        ),
    ]
