# Generated by Django 5.2 on 2025-04-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('codigo', models.AutoField(db_column='grup_codi', primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(db_column='grup_desc', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'FamiliaProduto',
                'db_table': 'familiaprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('codigo', models.AutoField(db_column='grup_codi', primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(db_column='grup_desc', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Grupo de Produto',
                'verbose_name_plural': 'Grupos de Produtos',
                'db_table': 'gruposprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.AutoField(db_column='grup_codi', primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(db_column='grup_desc', max_length=255, verbose_name='Nome')),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubgrupoProduto',
            fields=[
                ('codigo', models.AutoField(db_column='grup_codi', primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(db_column='grup_desc', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'subgruposprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('prod_empr', models.CharField(db_column='prod_empr', max_length=50)),
                ('prod_codi', models.CharField(db_column='prod_codi', max_length=50, primary_key=True, serialize=False)),
                ('prod_nome', models.CharField(db_column='prod_nome', max_length=255)),
                ('prod_unme', models.CharField(db_column='prod_unme', max_length=10)),
                ('prod_loca', models.CharField(blank=True, db_column='prod_loca', max_length=255, null=True)),
                ('prod_ncm', models.CharField(db_column='prod_ncm', max_length=10)),
                ('prod_foto', models.ImageField(blank=True, db_column='prod_foto', null=True, upload_to='fotos/')),
                ('prod_fami', models.ForeignKey(blank=True, db_column='prod_fami', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='Produtos.familiaproduto')),
                ('prod_grup', models.ForeignKey(blank=True, db_column='prod_grup', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='Produtos.grupoproduto')),
                ('prod_marc', models.ForeignKey(blank=True, db_column='prod_marc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='Produtos.marca')),
                ('prod_sugr', models.ForeignKey(blank=True, db_column='prod_sugr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='Produtos.subgrupoproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaldoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_column='sapr_empr', max_length=50)),
                ('filial', models.CharField(db_column='sapr_fili', max_length=50)),
                ('saldo_estoque', models.DecimalField(db_column='sapr_sald', decimal_places=2, max_digits=10)),
                ('produto_codigo', models.ForeignKey(db_column='sapr_prod', on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos')),
            ],
            options={
                'db_table': 'saldosprodutos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabelaprecos',
            fields=[
                ('tabe_empr', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('tabe_fili', models.IntegerField(default=1)),
                ('tabe_prco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_vipi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_pipi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_fret', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tabe_desp', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tabe_cust', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_marg', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tabe_impo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_avis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_praz', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tabe_apra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_vare', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('tabe_valo_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_perc_reaj', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_hist', models.TextField(blank=True, null=True)),
                ('tabe_cuge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_entr', models.DateField(blank=True, null=True)),
                ('tabe_perc_st', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tabe_prod', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos', verbose_name='Produto')),
            ],
            options={
                'db_table': 'tabelaprecos',
                'managed': False,
                'unique_together': {('tabe_empr', 'tabe_fili', 'tabe_prod')},
            },
        ),
    ]
