# Generated by Django 5.2 on 2025-04-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoproduto',
            name='produto_codigo',
            field=models.ForeignKey(db_column='sapr_prod', on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos'),
        ),
    ]
