# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_auto_20250424_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosDetalhados',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=10)),
                ('grupo_id', models.CharField(max_length=20, null=True)),
                ('grupo_nome', models.CharField(max_length=255, null=True)),
                ('marca_id', models.CharField(max_length=20, null=True)),
                ('marca_nome', models.CharField(max_length=255, null=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('preco_vista', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('preco_prazo', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('foto', models.TextField(null=True)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('peso_liquido', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('empresa', models.CharField(max_length=20, null=True)),
                ('filial', models.CharField(max_length=20, null=True)),
                ('valor_total_estoque', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('valor_total_venda_vista', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('valor_total_venda_prazo', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'produtos_detalhados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabelaprecoshist',
            fields=[
                ('tabe_id', models.AutoField(primary_key=True, serialize=False)),
                ('tabe_empr', models.IntegerField()),
                ('tabe_fili', models.IntegerField()),
                ('tabe_prod', models.CharField(max_length=20)),
                ('tabe_data_hora', models.DateTimeField()),
                ('tabe_perc_reaj', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_avis_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_avis_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_apra_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_apra_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_hist', models.TextField(blank=True, null=True)),
                ('tabe_prco_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_prco_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_pipi_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_pipi_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_fret_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_fret_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_desp_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_desp_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_cust_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_cust_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_cuge_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_cuge_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_icms_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_icms_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_impo_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_impo_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_marg_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_marg_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_praz_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_praz_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_valo_st_ante', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tabe_valo_st_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tabelaprecoshist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('unid_codi', models.CharField(db_column='unid_codi', max_length=10, primary_key=True, serialize=False)),
                ('unid_desc', models.CharField(db_column='unid_desc', max_length=50)),
            ],
            options={
                'db_table': 'unidadesmedidas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='saldoproduto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tabelaprecos',
            options={'managed': False, 'verbose_name': 'Tabela de Preço', 'verbose_name_plural': 'Tabelas de Preços'},
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_coba',
            field=models.CharField(blank=True, db_column='prod_coba', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prod_foto',
            field=models.BinaryField(blank=True, db_column='prod_foto', null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prod_unme',
            field=models.ForeignKey(db_column='prod_unme', on_delete=django.db.models.deletion.PROTECT, to='Produtos.UnidadeMedida'),
        ),
    ]
