# Generated by Django 2.2.28 on 2025-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0003_auto_20250709_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_empr', models.IntegerField()),
                ('lote_prod', models.CharField(max_length=60)),
                ('lote_lote', models.IntegerField()),
                ('lote_unit', models.DecimalField(decimal_places=2, help_text='Preço unitário', max_digits=15)),
                ('lote_sald', models.DecimalField(decimal_places=2, help_text='Saldo', max_digits=15)),
                ('lote_usua', models.IntegerField()),
                ('lote_data_alt', models.DateTimeField(auto_now=True, help_text='Data de alteração')),
                ('lote_data_venc', models.DateField(help_text='Data de vencimento')),
                ('lote_ativ', models.BooleanField(default=True, help_text='Lote ativo')),
                ('lote_data_fabr', models.DateField(blank=True, help_text='Data de fabricação', null=True)),
                ('lote_obse', models.TextField(blank=True, help_text='Observações do lote', null=True)),
            ],
            options={
                'verbose_name': 'Lote de Venda',
                'verbose_name_plural': 'Lotes de Venda',
                'db_table': 'lotesvenda',
                'ordering': ['lote_empr', 'lote_prod', 'lote_lote'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_cera_m2cx',
            field=models.DecimalField(blank=True, db_column='prod_cera_m2cx', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_cera_pccx',
            field=models.DecimalField(blank=True, db_column='prod_cera_pccx', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='codigo',
            field=models.AutoField(db_column='fami_codi', primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='descricao',
            field=models.CharField(db_column='fami_desc', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='codigo',
            field=models.AutoField(db_column='marc_codi', primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(db_column='marc_desc', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subgrupoproduto',
            name='codigo',
            field=models.AutoField(db_column='sugr_codi', primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subgrupoproduto',
            name='descricao',
            field=models.CharField(db_column='sugr_desc', max_length=255, verbose_name='Descrição'),
        ),
    ]
