# Generated by Django 2.2.28 on 2025-11-28 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_auto_20250911_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentoestoque',
            fields=[
                ('moes_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('moes_fili', models.IntegerField()),
                ('moes_tipo', models.CharField(max_length=1)),
                ('moes_docu', models.IntegerField()),
                ('moes_seri', models.CharField(max_length=6)),
                ('moes_mode', models.CharField(max_length=2)),
                ('moes_enti', models.IntegerField()),
                ('moes_data', models.DateField(blank=True, null=True)),
                ('moes_prod', models.CharField(blank=True, max_length=20, null=True)),
                ('moes_quan', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('moes_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('moes_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moes_item', models.IntegerField()),
                ('moes_fina', models.CharField(blank=True, max_length=2, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('moes_data_hora', models.CharField(blank=True, max_length=40, null=True)),
                ('moes_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('moes_ctrl_ctb', models.IntegerField(blank=True, null=True)),
                ('moes_seto', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movimentoestoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('ncm_codi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ncm_desc', models.TextField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'ncm',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='familiaproduto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupoproduto',
            options={'managed': False, 'verbose_name': 'Grupo de Produto', 'verbose_name_plural': 'Grupos de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subgrupoproduto',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_cera_kgcx',
            field=models.DecimalField(blank=True, db_column='prod_cera_kgcx', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_codi_nume',
            field=models.CharField(blank=True, db_column='prod_codi_nume', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_gtin',
            field=models.CharField(blank=True, db_column='prod_gtin', default='SEM GTIN', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='prod_orig_merc',
            field=models.CharField(blank=True, db_column='prod_orig_merc', default='0', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='NcmAliquota',
            fields=[
                ('nali_id', models.AutoField(primary_key=True, serialize=False)),
                ('nali_empr', models.IntegerField(default=1)),
                ('nali_aliq_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nali_aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nali_aliq_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nali_aliq_cbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nali_aliq_ibs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nali_ncm', models.OneToOneField(db_column='nali_ncm', on_delete=django.db.models.deletion.CASCADE, to='Produtos.Ncm')),
            ],
            options={
                'db_table': 'ncm_aliquotas_ibpt',
            },
        ),
    ]
