# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaidasEstoque',
            fields=[
                ('said_sequ', models.IntegerField(primary_key=True, serialize=False)),
                ('said_empr', models.IntegerField(default=1)),
                ('said_fili', models.IntegerField(default=1)),
                ('said_prod', models.CharField(db_column='said_prod', max_length=10)),
                ('said_enti', models.CharField(blank=True, db_column='said_enti', max_length=10, null=True)),
                ('said_data', models.DateField()),
                ('said_quan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('said_tota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('said_obse', models.CharField(blank=True, max_length=100, null=True)),
                ('said_usua', models.IntegerField()),
            ],
            options={
                'db_table': 'saidasestoque',
                'ordering': ['-said_data'],
            },
        ),
        migrations.AddConstraint(
            model_name='saidasestoque',
            constraint=models.UniqueConstraint(fields=('said_empr', 'said_fili', 'said_prod', 'said_data'), name='pk_saida_estoque'),
        ),
    ]
