# Generated by Django 5.2.5 on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obra_empr", models.IntegerField()),
                ("obra_fili", models.IntegerField()),
                ("obra_codi", models.IntegerField()),
                ("obra_nome", models.CharField(max_length=150)),
                ("obra_desc", models.TextField(blank=True, null=True)),
                ("obra_dini", models.DateField()),
                ("obra_dpre", models.DateField(blank=True, null=True)),
                ("obra_dfim", models.DateField(blank=True, null=True)),
                ("obra_orca", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("obra_cust", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (
                    "obra_stat",
                    models.CharField(
                        choices=[("PL", "Planejada"), ("EA", "Em andamento"), ("PA", "Paralisada"), ("CO", "Concluída"), ("CA", "Cancelada")],
                        default="PL",
                        max_length=2,
                    ),
                ),
                ("obra_ativ", models.BooleanField(default=True)),
                ("obra_crea", models.DateTimeField(auto_now_add=True)),
                ("obra_alte", models.DateTimeField(auto_now=True)),
                ("obra_clie", models.IntegerField(db_column="obra_clie")),
                ("obra_resp", models.IntegerField(blank=True, null=True, db_column="obra_resp")),
            ],
            options={"db_table": "gestao_obras", "ordering": ("-obra_codi",), "unique_together": {("obra_empr", "obra_fili", "obra_codi")}},
        ),
        migrations.CreateModel(
            name="ObraEtapa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("etap_empr", models.IntegerField()),
                ("etap_fili", models.IntegerField()),
                ("etap_codi", models.IntegerField()),
                ("etap_nome", models.CharField(max_length=120)),
                ("etap_desc", models.TextField(blank=True, null=True)),
                ("etap_orde", models.PositiveIntegerField(default=1)),
                ("etap_dinp", models.DateField(blank=True, null=True)),
                ("etap_dfip", models.DateField(blank=True, null=True)),
                ("etap_dinr", models.DateField(blank=True, null=True)),
                ("etap_dfir", models.DateField(blank=True, null=True)),
                ("etap_situ", models.CharField(choices=[("PE", "Pendente"), ("EA", "Em andamento"), ("FI", "Finalizada")], default="PE", max_length=2)),
                ("etap_perc", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("etap_crea", models.DateTimeField(auto_now_add=True)),
                ("etap_alte", models.DateTimeField(auto_now=True)),
                ("etap_obra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="etapas", to="GestaoObras.obra")),
            ],
            options={"db_table": "gestao_obras_etapas", "ordering": ("etap_obra", "etap_orde"), "unique_together": {("etap_empr", "etap_fili", "etap_codi")}},
        ),
        migrations.CreateModel(
            name="ObraMaterialMovimento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movm_empr", models.IntegerField()),
                ("movm_fili", models.IntegerField()),
                ("movm_codi", models.IntegerField()),
                ("movm_tipo", models.CharField(choices=[("EN", "Entrada"), ("SA", "Saída")], max_length=2)),
                ("movm_prod", models.CharField(max_length=20)),
                ("movm_desc", models.CharField(max_length=255)),
                ("movm_quan", models.DecimalField(decimal_places=3, max_digits=15)),
                ("movm_unid", models.CharField(default="UN", max_length=6)),
                ("movm_cuni", models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ("movm_data", models.DateField()),
                ("movm_docu", models.CharField(blank=True, max_length=30, null=True)),
                ("movm_obse", models.TextField(blank=True, null=True)),
                ("movm_crea", models.DateTimeField(auto_now_add=True)),
                ("movm_etap", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movimentos_materiais", to="GestaoObras.obraetapa")),
                ("movm_obra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos_materiais", to="GestaoObras.obra")),
            ],
            options={"db_table": "gestao_obras_movimentos_materiais", "ordering": ("-movm_data", "-movm_codi"), "unique_together": {("movm_empr", "movm_fili", "movm_codi")}},
        ),
        migrations.CreateModel(
            name="ObraLancamentoFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lfin_empr", models.IntegerField()),
                ("lfin_fili", models.IntegerField()),
                ("lfin_codi", models.IntegerField()),
                ("lfin_tipo", models.CharField(choices=[("RE", "Receita"), ("DE", "Despesa")], max_length=2)),
                ("lfin_cate", models.CharField(max_length=80)),
                ("lfin_desc", models.CharField(max_length=255)),
                ("lfin_valo", models.DecimalField(decimal_places=2, max_digits=15)),
                ("lfin_dcom", models.DateField()),
                ("lfin_dpag", models.DateField(blank=True, null=True)),
                ("lfin_obse", models.TextField(blank=True, null=True)),
                ("lfin_crea", models.DateTimeField(auto_now_add=True)),
                ("lfin_etap", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lancamentos_financeiros", to="GestaoObras.obraetapa")),
                ("lfin_obra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lancamentos_financeiros", to="GestaoObras.obra")),
            ],
            options={"db_table": "gestao_obras_lancamentos_financeiros", "ordering": ("-lfin_dcom", "-lfin_codi"), "unique_together": {("lfin_empr", "lfin_fili", "lfin_codi")}},
        ),
        migrations.CreateModel(
            name="ObraProcesso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proc_empr", models.IntegerField()),
                ("proc_fili", models.IntegerField()),
                ("proc_codi", models.IntegerField()),
                ("proc_titu", models.CharField(max_length=120)),
                ("proc_desc", models.TextField(blank=True, null=True)),
                ("proc_dlim", models.DateField(blank=True, null=True)),
                ("proc_prio", models.CharField(choices=[("BA", "Baixa"), ("ME", "Média"), ("AL", "Alta"), ("CR", "Crítica")], default="ME", max_length=2)),
                ("proc_stat", models.CharField(choices=[("AB", "Aberto"), ("EA", "Em andamento"), ("CO", "Concluído"), ("BL", "Bloqueado")], default="AB", max_length=2)),
                ("proc_crea", models.DateTimeField(auto_now_add=True)),
                ("proc_alte", models.DateTimeField(auto_now=True)),
                ("proc_etap", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processos", to="GestaoObras.obraetapa")),
                ("proc_obra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processos", to="GestaoObras.obra")),
                ("proc_resp", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "gestao_obras_processos", "ordering": ("-proc_codi",), "unique_together": {("proc_empr", "proc_fili", "proc_codi")}},
        ),
    ]
