# Generated by Django 2.2.28 on 2026-03-30 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoObras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ('obra_codi',)},
        ),
        migrations.AlterField(
            model_name='obra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obraetapa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obralancamentofinanceiro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obramaterialmovimento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obraprocesso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ObraMaterialEstoqueSaldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omes_empr', models.IntegerField()),
                ('omes_fili', models.IntegerField()),
                ('omes_tipo', models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Saída')], max_length=2)),
                ('omes_prod', models.CharField(max_length=20)),
                ('omes_desc', models.CharField(max_length=255)),
                ('omes_quan', models.DecimalField(decimal_places=3, max_digits=15)),
                ('omes_unid', models.CharField(default='UN', max_length=6)),
                ('omes_valo_unit', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('omes_data_movi', models.DateField(default=datetime.date.today)),
                ('omes_docu', models.CharField(blank=True, max_length=30, null=True)),
                ('omes_valo_tota', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('omes_sald_atua', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('omes_obse', models.TextField(blank=True, null=True)),
                ('omes_crea', models.DateTimeField(auto_now_add=True)),
                ('omes_alte', models.DateTimeField(auto_now=True)),
                ('omes_usua', models.IntegerField(blank=True, null=True)),
                ('omes_etap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_materiais', to='GestaoObras.ObraEtapa')),
                ('omes_movm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_materiais', to='GestaoObras.ObraMaterialMovimento')),
                ('omes_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_materiais', to='GestaoObras.Obra')),
            ],
            options={
                'db_table': 'gestao_obras_material_estoque_saldos',
                'ordering': ('-omes_data_movi', '-omes_prod'),
                'unique_together': {('omes_empr', 'omes_fili', 'omes_prod')},
            },
        ),
    ]
