# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosGeral',
            fields=[
                ('empresa', models.IntegerField()),
                ('filial', models.IntegerField()),
                ('numero_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_cliente', models.IntegerField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_pedido', models.DateField()),
                ('quantidade_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itens_do_pedido', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_financeiro', models.CharField(max_length=50)),
                ('nome_vendedor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pedidos_geral',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='itenspedidovenda',
            name='iped_data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itenspedidovenda',
            name='iped_suto',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='itenspedidovenda',
            name='iped_empr',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='itenspedidovenda',
            name='iped_pedi',
            field=models.CharField(db_column='iped_pedi', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itenspedidovenda',
            name='iped_prod',
            field=models.CharField(db_column='iped_prod', max_length=60),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_forn',
            field=models.CharField(db_column='pedi_forn', max_length=60),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_nume',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_stat',
            field=models.CharField(choices=[(0, 'Pendente'), (1, 'Processando'), (2, 'Enviado'), (3, 'Concluído'), (4, 'Cancelado')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='pedi_vend',
            field=models.CharField(db_column='pedi_vend', default=0, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='pedidovenda',
            unique_together={('pedi_empr', 'pedi_fili', 'pedi_nume')},
        ),
    ]
