# Generated by Django 2.2.28 on 2026-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_id', models.IntegerField()),
                ('documento', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'db_table': 'registro_ponto',
                'ordering': ['data_hora'],
            },
        ),
    ]
