# Generated by Django 2.2.28 on 2025-12-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_nome', models.CharField(max_length=100, unique=True)),
                ('perf_ativ', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='PermissaoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_acao', models.CharField(max_length=30)),
                ('perf_data', models.DateTimeField(auto_now_add=True)),
                ('perf_op', models.CharField(max_length=20)),
                ('perf_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('perf_oper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perf_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilweb.Perfil')),
            ],
            options={
                'db_table': 'permissao_log',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_ativ', models.BooleanField(default=True)),
                ('perf_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilweb.Perfil')),
                ('perf_usua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_perfil',
                'unique_together': {('perf_usua', 'perf_perf')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_acao', models.CharField(max_length=30)),
                ('perf_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('perf_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilweb.Perfil')),
            ],
            options={
                'db_table': 'permissao_perfil',
                'unique_together': {('perf_perf', 'perf_ctype', 'perf_acao')},
            },
        ),
        migrations.CreateModel(
            name='PerfilHeranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_pais_rel', to='perfilweb.Perfil')),
                ('perf_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_filhos_rel', to='perfilweb.Perfil')),
            ],
            options={
                'db_table': 'perfil_heranca',
                'unique_together': {('perf_filho', 'perf_pai')},
            },
        ),
    ]
