# Generated by Django 2.2.28 on 2026-01-14 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Licencas', '__first__'),
        ('Entidades', '__first__'),
        ('Produtos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('filial', models.IntegerField()),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], default='55', max_length=2)),
                ('serie', models.CharField(max_length=3)),
                ('numero', models.IntegerField()),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('tipo_operacao', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Saída')])),
                ('finalidade', models.IntegerField(choices=[(1, 'Normal'), (2, 'Complementar'), (3, 'Ajuste'), (4, 'Devolução')], default=1)),
                ('ambiente', models.IntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2)),
                ('status', models.IntegerField(choices=[(0, 'Rascunho'), (100, 'Autorizada'), (101, 'Cancelada'), (102, 'Inutilizada'), (301, 'Dendegada(Irregularidade Emitente)'), (302, 'Dendegada(Irregularidade Destinatário)')], default=0)),
                ('chave_acesso', models.CharField(blank=True, max_length=50, null=True)),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=60, null=True)),
                ('xml_assinado', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='Entidades.Entidades')),
                ('emitente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='Licencas.Filiais')),
            ],
            options={
                'db_table': 'nf_nota',
            },
        ),
        migrations.CreateModel(
            name='NotaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('cfop', models.CharField(max_length=4)),
                ('ncm', models.CharField(max_length=8)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('cst_icms', models.CharField(max_length=3)),
                ('cst_ipi', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_pis', models.CharField(max_length=2)),
                ('cst_cofins', models.CharField(max_length=2)),
                ('cst_ibs', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cbs', models.CharField(blank=True, max_length=3, null=True)),
                ('fonte_tributacao', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Notas_Fiscais.Nota')),
                ('produto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='Produtos.Produtos')),
            ],
            options={
                'verbose_name': 'Item Nota Fiscal (Domínio)',
                'verbose_name_plural': 'Itens Nota Fiscal (Domínio)',
                'db_table': 'nf_nota_item',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_frete', models.IntegerField(choices=[(0, 'Emitente'), (1, 'Destinatário'), (2, 'Terceiros'), (9, 'Sem Frete')])),
                ('placa_veiculo', models.CharField(blank=True, max_length=8, null=True)),
                ('uf_veiculo', models.CharField(blank=True, max_length=2, null=True)),
                ('nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='Notas_Fiscais.Nota')),
                ('transportadora', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='Entidades.Entidades')),
            ],
            options={
                'verbose_name': 'Transporte Nota Fiscal',
                'verbose_name_plural': 'Transportes Nota Fiscal',
                'db_table': 'nf_transporte',
            },
        ),
        migrations.CreateModel(
            name='NotaItemImposto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icms_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('icms_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('icms_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('icms_st_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('icms_st_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('icms_st_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('icms_mva_st', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ipi_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ipi_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ipi_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('pis_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('pis_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pis_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cofins_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cofins_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fcp_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ibs_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ibs_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ibs_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cbs_base', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cbs_aliquota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cbs_valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='Notas_Fiscais.NotaItem')),
            ],
            options={
                'verbose_name': 'Impostos do Item (Domínio)',
                'verbose_name_plural': 'Impostos dos Itens (Domínio)',
                'db_table': 'nf_item_imposto',
            },
        ),
        migrations.CreateModel(
            name='NotaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('xml', models.TextField(blank=True, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=60, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Notas_Fiscais.Nota')),
            ],
            options={
                'verbose_name': 'Evento Nota Fiscal',
                'verbose_name_plural': 'Eventos Nota Fiscal',
                'db_table': 'nf_nota_evento',
            },
        ),
        migrations.AddIndex(
            model_name='transporte',
            index=models.Index(fields=['nota'], name='nf_transpor_nota_id_d4ea47_idx'),
        ),
        migrations.AddIndex(
            model_name='notaitemimposto',
            index=models.Index(fields=['item'], name='nf_item_imp_item_id_15e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='notaitem',
            index=models.Index(fields=['nota'], name='nf_nota_ite_nota_id_4a9323_idx'),
        ),
        migrations.AddIndex(
            model_name='notaitem',
            index=models.Index(fields=['produto'], name='nf_nota_ite_produto_7a0db9_idx'),
        ),
        migrations.AddIndex(
            model_name='notaevento',
            index=models.Index(fields=['nota', 'tipo'], name='nf_nota_eve_nota_id_1bfb6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('empresa', 'filial', 'modelo', 'serie', 'numero')},
        ),
    ]
