# Generated by Django 2.2.28 on 2026-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notas_Fiscais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notaitem',
            old_name='total',
            new_name='total_item',
        ),
    ]
