# Generated by Django 2.2.28 on 2026-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas_Fiscais', '0002_auto_20260114_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='motivo_status',
            field=models.TextField(blank=True, help_text='Motivo do status retornado pela SEFAZ', null=True),
        ),
    ]
