# Generated by Django 2.2.28 on 2026-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas_Fiscais', '0003_nota_motivo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pedido_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Número do Pedido de Venda de origem', max_length=20, null=True),
        ),
    ]
