# Generated by Django 2.2.28 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notas_Fiscais", "0004_nota_pedido_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="chave_referenciada",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Chave (44 dígitos) da NF-e referenciada",
                max_length=44,
                null=True,
            ),
        ),
    ]

