# Generated by Django 2.2.28 on 2026-01-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produtos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOPFiscal',
            fields=[
                ('cfop_codi', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cfop_desc', models.TextField()),
            ],
            options={
                'db_table': 'cfopfiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CFOP',
            fields=[
                ('cfop_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfop_empr', models.IntegerField()),
                ('cfop_codi', models.CharField(max_length=10, unique=True)),
                ('cfop_desc', models.CharField(max_length=255)),
                ('cfop_exig_ipi', models.BooleanField(default=False)),
                ('cfop_exig_icms', models.BooleanField(default=False)),
                ('cfop_exig_pis_cofins', models.BooleanField(default=False)),
                ('cfop_exig_cbs', models.BooleanField(default=False)),
                ('cfop_exig_ibs', models.BooleanField(default=False)),
                ('cfop_gera_st', models.BooleanField(default=False)),
                ('cfop_gera_difal', models.BooleanField(default=False)),
                ('cfop_icms_base_inclui_ipi', models.BooleanField(default=False)),
                ('cfop_st_base_inclui_ipi', models.BooleanField(default=False)),
                ('cfop_ipi_tota_nf', models.BooleanField(default=False)),
                ('cfop_st_tota_nf', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cfopweb',
            },
        ),
        migrations.CreateModel(
            name='TabelaICMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_origem', models.CharField(db_column='tabe_uf_orig', max_length=2)),
                ('uf_destino', models.CharField(db_column='tabe_uf_dest', max_length=2)),
                ('empresa', models.IntegerField(db_column='tabe_empr')),
                ('aliq_interna', models.DecimalField(db_column='tabe_aliq_interna', decimal_places=2, max_digits=5)),
                ('aliq_inter', models.DecimalField(db_column='tabe_aliq_inter', decimal_places=2, max_digits=5)),
                ('mva_st', models.DecimalField(blank=True, db_column='tabe_mva_st', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'tabela_icms',
                'unique_together': {('empresa', 'uf_origem', 'uf_destino')},
            },
        ),
        migrations.CreateModel(
            name='NCM_CFOP_DIF',
            fields=[
                ('ncmdif_id', models.AutoField(primary_key=True, serialize=False)),
                ('ncm_empr', models.IntegerField()),
                ('ncm_ipi_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_pis_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_cofins_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_cbs_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_ibs_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_icms_aliq_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm_st_aliq_dif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFOP.CFOP')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.Ncm')),
            ],
            options={
                'db_table': 'ncm_cfop_dif',
                'unique_together': {('ncm', 'cfop')},
            },
        ),
        migrations.CreateModel(
            name='MapaCFOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_oper', models.CharField(choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('DEVOLUCAO_VENDA', 'Devolução de Venda'), ('DEVOLUCAO_COMPRA', 'Devolução de Compra'), ('REMESSA', 'Remessa'), ('TRANSFERENCIA', 'Transferência'), ('BONIFICACAO', 'Bonificação'), ('EXPORTACAO', 'Exportação')], max_length=30)),
                ('uf_origem', models.CharField(max_length=2)),
                ('uf_destino', models.CharField(max_length=2)),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CFOP.CFOP')),
            ],
            options={
                'db_table': 'mapa_cfop',
                'unique_together': {('tipo_oper', 'uf_origem', 'uf_destino')},
            },
        ),
    ]
