# Generated by Django 2.2.28 on 2026-01-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '__first__'),
        ('CFOP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfop',
            options={'ordering': ['cfop_codi'], 'verbose_name': 'CFOP', 'verbose_name_plural': 'CFOPs'},
        ),
        migrations.AlterModelOptions(
            name='cfopfiscal',
            options={'managed': False, 'verbose_name': 'CFOP Fiscal (Consulta)', 'verbose_name_plural': 'CFOPs Fiscais (Consulta)'},
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_codi',
            field=models.CharField(help_text='Código fiscal de operação (ex: 5102). Deve ter 4 dígitos.', max_length=10, unique=True, verbose_name='Código CFOP'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_desc',
            field=models.CharField(help_text='Descrição da operação', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_empr',
            field=models.IntegerField(help_text='ID da empresa vinculada', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_exig_cbs',
            field=models.BooleanField(default=False, help_text='Calcula CBS (Reforma Tributária)', verbose_name='Exige CBS'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_exig_ibs',
            field=models.BooleanField(default=False, help_text='Calcula IBS (Reforma Tributária)', verbose_name='Exige IBS'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_exig_icms',
            field=models.BooleanField(default=False, help_text='Calcula e destaca ICMS na nota', verbose_name='Exige ICMS'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_exig_ipi',
            field=models.BooleanField(default=False, help_text='Calcula e destaca IPI na nota', verbose_name='Exige IPI'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_exig_pis_cofins',
            field=models.BooleanField(default=False, help_text='Calcula e destaca PIS/COFINS na nota', verbose_name='Exige PIS/COFINS'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_gera_difal',
            field=models.BooleanField(default=False, help_text='Calcula Diferencial de Alíquota', verbose_name='Gera DIFAL'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_gera_st',
            field=models.BooleanField(default=False, help_text='Calcula Substituição Tributária', verbose_name='Gera ST'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_icms_base_inclui_ipi',
            field=models.BooleanField(default=False, help_text='Adiciona valor do IPI na base do ICMS', verbose_name='Base ICMS inclui IPI'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_ipi_tota_nf',
            field=models.BooleanField(default=False, help_text='Soma o valor do IPI ao total da nota', verbose_name='IPI compõe Total NF'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_st_base_inclui_ipi',
            field=models.BooleanField(default=False, help_text='Adiciona valor do IPI na base do ST', verbose_name='Base ST inclui IPI'),
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop_st_tota_nf',
            field=models.BooleanField(default=False, help_text='Soma o valor do ST ao total da nota', verbose_name='ST compõe Total NF'),
        ),
        migrations.CreateModel(
            name='ProdutoFiscalPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ipi', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cbs', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ibs', models.CharField(blank=True, max_length=3, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ibs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('produto', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='Produtos.Produtos')),
            ],
            options={
                'verbose_name': 'Fiscal Padrão Produto',
                'verbose_name_plural': 'Fiscais Padrão Produto',
                'db_table': 'produto_fiscal_padrao',
            },
        ),
        migrations.CreateModel(
            name='NcmFiscalPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ipi', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cbs', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ibs', models.CharField(blank=True, max_length=3, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ibs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ncm', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='Produtos.Ncm')),
            ],
            options={
                'verbose_name': 'Fiscal Padrão NCM',
                'verbose_name_plural': 'Fiscais Padrão NCM',
                'db_table': 'ncm_fiscal_padrao',
            },
        ),
    ]
