# Generated by Django 2.2.28 on 2026-01-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFOP', '0002_auto_20260113_1534'),
    ]

    operations = [
        # Operations removed as they are now covered by 0001 and 0002 fixes
    ]
