# Generated by Django 2.2.28 on 2026-01-13 17:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('CFOP', '0003_auto_20260113_1657'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- cfop_icms_base_inclui_ipi
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_icms_base_inclui_ipi') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_icms_base_inclui_ipi boolean DEFAULT false;
                END IF;

                -- cfop_st_base_inclui_ipi
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_st_base_inclui_ipi') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_st_base_inclui_ipi boolean DEFAULT false;
                END IF;

                -- cfop_exig_cbs
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_exig_cbs') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_exig_cbs boolean DEFAULT false;
                END IF;

                -- cfop_exig_ibs
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_exig_ibs') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_exig_ibs boolean DEFAULT false;
                END IF;

                -- cfop_exig_icms
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_exig_icms') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_exig_icms boolean DEFAULT false;
                END IF;

                -- cfop_exig_ipi
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_exig_ipi') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_exig_ipi boolean DEFAULT false;
                END IF;

                -- cfop_exig_pis_cofins
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_exig_pis_cofins') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_exig_pis_cofins boolean DEFAULT false;
                END IF;

                -- cfop_gera_difal
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_gera_difal') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_gera_difal boolean DEFAULT false;
                END IF;

                -- cfop_gera_st
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_gera_st') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_gera_st boolean DEFAULT false;
                END IF;

                -- cfop_ipi_tota_nf
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_ipi_tota_nf') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_ipi_tota_nf boolean DEFAULT false;
                END IF;

                -- cfop_st_tota_nf
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfopweb' AND column_name='cfop_st_tota_nf') THEN
                    ALTER TABLE cfopweb ADD COLUMN cfop_st_tota_nf boolean DEFAULT false;
                END IF;
            END $$;
            """
        )
    ]
