# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFOP', '0004_fix_legacy_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelaicms',
            name='id',
            field=models.AutoField(db_column='tabe_id', primary_key=True, serialize=False),
        ),
    ]
