# Generated by Django 2.2.28 on 2026-01-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFOP', '0005_auto_20260114_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOPFiscalPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ipi', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_cbs', models.CharField(blank=True, max_length=3, null=True)),
                ('cst_ibs', models.CharField(blank=True, max_length=3, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_cbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliq_ibs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cfop', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='CFOP.CFOP')),
            ],
            options={
                'verbose_name': 'Fiscal Padrão CFOP',
                'verbose_name_plural': 'Fiscais Padrão CFOP',
                'db_table': 'cfop_fiscal_padrao',
            },
        ),
    ]
