# Generated by Django 2.2.28 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFOP", "0006_cfopfiscalpadrao"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfopfiscalpadrao",
            name="tipo_entidade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="cfopfiscalpadrao",
            name="uf_destino",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="cfopfiscalpadrao",
            name="uf_origem",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="ncmfiscalpadrao",
            name="tipo_entidade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="ncmfiscalpadrao",
            name="uf_destino",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="ncmfiscalpadrao",
            name="uf_origem",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="produtofiscalpadrao",
            name="tipo_entidade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="produtofiscalpadrao",
            name="uf_destino",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="produtofiscalpadrao",
            name="uf_origem",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]

