# Generated by Django 2.2.28 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFOP", "0007_fiscalpadrao_contexto"),
    ]

    operations = [
        migrations.AddField(
            model_name="ncmfiscalpadrao",
            name="cfop",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]

