# Generated by Django 2.2.28 on 2026-03-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CFOP", "0008_ncmfiscalpadrao_cfop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ncmfiscalpadrao",
            name="ncm",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal",
                to="Produtos.Ncm",
            ),
        ),
    ]

