# Generated by Django 2.2.28 on 2026-04-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoComissao',
            fields=[
                ('lcom_id', models.AutoField(primary_key=True, serialize=False)),
                ('lcom_empr', models.IntegerField(verbose_name='Empresa')),
                ('lcom_fili', models.IntegerField(verbose_name='Filial')),
                ('lcom_bene', models.IntegerField(verbose_name='Vendedor/Beneficiário')),
                ('lcom_data', models.DateField(verbose_name='Data')),
                ('lcom_tipo_origem', models.CharField(blank=True, choices=[('pedido', 'Pedido'), ('nota', 'Nota'), ('titulo', 'Título')], max_length=20, null=True)),
                ('lcom_docu', models.CharField(max_length=20, verbose_name='Documento')),
                ('lcom_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Base Comissão')),
                ('lcom_perc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Comissão')),
                ('lcom_valo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Comissão')),
                ('lcom_stat', models.IntegerField(choices=[(1, 'Em aberto'), (2, 'Pago'), (3, 'Parcial'), (4, 'Cancelado'), (5, 'Estornado')], default=1)),
                ('lcom_obse', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Lançamento Comissão',
                'verbose_name_plural': 'Lancamentos Comissões',
                'db_table': 'lancamentos_comissoes_web',
                'ordering': ['lcom_id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoComissao',
            fields=[
                ('pagc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pagc_empr', models.IntegerField(verbose_name='Empresa')),
                ('pagc_fili', models.IntegerField(verbose_name='Filial')),
                ('pagc_data', models.DateField(verbose_name='Data')),
                ('pagc_bene', models.IntegerField(verbose_name='Vendedor/Beneficiário')),
                ('pagc_valo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Pagamento')),
                ('pagc_obse', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Pagamento Comissão',
                'verbose_name_plural': 'Pagamentos Comissões',
                'db_table': 'pagamentos_comissoes_web',
                'ordering': ['pagc_id'],
            },
        ),
        migrations.CreateModel(
            name='RegraComissao',
            fields=[
                ('regc_id', models.AutoField(primary_key=True, serialize=False)),
                ('regc_empr', models.IntegerField(verbose_name='Empresa')),
                ('regc_fili', models.IntegerField(verbose_name='Filial')),
                ('regc_bene', models.IntegerField(verbose_name='Vendedor/Beneficiário')),
                ('regc_perc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Comissão')),
                ('regc_ativ', models.BooleanField(default=True, verbose_name='Ativo')),
                ('regc_data_ini', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('regc_data_fim', models.DateField(blank=True, null=True, verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'Regra Comissão',
                'verbose_name_plural': 'Regras Comissões',
                'db_table': 'regras_comissoes_web',
                'ordering': ['regc_id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoComissaoItem',
            fields=[
                ('pgci_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgci_valo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Pagamento')),
                ('pgci_lanc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.LancamentoComissao', verbose_name='Lançamento Comissão')),
                ('pgci_paga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comissoes.PagamentoComissao')),
            ],
            options={
                'verbose_name': 'Item Pagamento Comissão',
                'verbose_name_plural': 'Itens Pagamentos Comissões',
                'db_table': 'pagamentos_comissoes_itens_web',
                'ordering': ['pgci_id'],
            },
        ),
        migrations.AddField(
            model_name='lancamentocomissao',
            name='lcom_regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.RegraComissao', verbose_name='Regra Comissão'),
        ),
        migrations.AlterUniqueTogether(
            name='lancamentocomissao',
            unique_together={('lcom_empr', 'lcom_fili', 'lcom_bene', 'lcom_tipo_origem', 'lcom_docu')},
        ),
    ]
