# Generated by Django 2.2.28 on 2026-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocomissao',
            name='lcom_cecu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cento de Custo'),
        ),
        migrations.AddField(
            model_name='pagamentocomissao',
            name='pagc_cecu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cento de Custo'),
        ),
        migrations.AddField(
            model_name='pagamentocomissaoitem',
            name='pgci_cecu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cento de Custo'),
        ),
        migrations.AddField(
            model_name='pagamentocomissaoitem',
            name='pgci_obse',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='regracomissao',
            name='regc_cecu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cento de Custo'),
        ),
    ]
