# Generated by Django 2.2.28 on 2026-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nfedocumento',
            name='fiscal_nfe_empresa_04e07a_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfedocumento',
            name='fiscal_nfe_empresa_5c2f2c_idx',
        ),
        migrations.AddIndex(
            model_name='nfedocumento',
            index=models.Index(fields=['empresa', 'filial', 'tipo'], name='fiscal_nfe__empresa_0dcccc_idx'),
        ),
        migrations.AddIndex(
            model_name='nfedocumento',
            index=models.Index(fields=['empresa', 'filial', 'criado_em'], name='fiscal_nfe__empresa_a0d5d7_idx'),
        ),
    ]
