# Generated by Django 2.2.28 on 2026-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaDevolucao',
            fields=[
                ('tdvl_empr', models.IntegerField()),
                ('tdvl_fili', models.IntegerField()),
                ('tdvl_nume', models.IntegerField(primary_key=True, serialize=False)),
                ('tdvl_pdor', models.IntegerField(help_text='Pedido de origem')),
                ('tdvl_clie', models.CharField(max_length=60)),
                ('tdvl_vend', models.CharField(blank=True, max_length=15, null=True)),
                ('tdvl_data', models.DateField()),
                ('tdvl_tipo', models.CharField(choices=[('TROC', 'Troca'), ('DEVO', 'Devolução')], default='DEVO', max_length=4)),
                ('tdvl_stat', models.CharField(choices=[('0', 'Rascunho'), ('1', 'Processando'), ('2', 'Concluída'), ('3', 'Cancelada')], default='0', max_length=4)),
                ('tdvl_tode', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tdvl_tore', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tdvl_safi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tdvl_obse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trocas_devolucoes',
                'managed': True,
                'unique_together': {('tdvl_empr', 'tdvl_fili', 'tdvl_nume')},
            },
        ),
        migrations.CreateModel(
            name='ItensTrocaDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itdv_empr', models.IntegerField()),
                ('itdv_fili', models.IntegerField()),
                ('itdv_tdvl', models.IntegerField(help_text='Número da troca/devolução')),
                ('itdv_item', models.IntegerField()),
                ('itdv_pdor', models.IntegerField(help_text='Pedido de origem')),
                ('itdv_itor', models.IntegerField(help_text='Item do pedido de origem')),
                ('itdv_pror', models.CharField(help_text='Produto origem', max_length=60)),
                ('itdv_qtor', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('itdv_prre', models.CharField(blank=True, help_text='Produto reposição', max_length=60, null=True)),
                ('itdv_qtre', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('itdv_vlor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('itdv_vlre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('itdv_moti', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'itens_trocas_devolucoes',
                'managed': True,
                'unique_together': {('itdv_empr', 'itdv_fili', 'itdv_tdvl', 'itdv_item')},
            },
        ),
    ]
