# Generated by Django 2.2.28 on 2026-02-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renegociado',
            fields=[
                ('rene_id', models.AutoField(primary_key=True, serialize=False)),
                ('rene_empr', models.IntegerField(blank=True, null=True)),
                ('rene_fili', models.IntegerField(blank=True, null=True)),
                ('rene_clie', models.IntegerField(blank=True, null=True)),
                ('rene_titu', models.CharField(blank=True, max_length=13, null=True)),
                ('rene_seri', models.CharField(blank=True, default='REN', max_length=5, null=True)),
                ('rene_parc', models.CharField(blank=True, max_length=3, null=True)),
                ('rene_venc', models.DateField(blank=True, null=True)),
                ('rene_valo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rene_bole', models.CharField(blank=True, max_length=50, null=True)),
                ('rene_perc_mult', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rene_valo_mult', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rene_perc_juro', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rene_valo_juro', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rene_juro_dia', models.BooleanField(blank=True, null=True)),
                ('rene_dias', models.IntegerField(blank=True, null=True)),
                ('rene_vlfn', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rene_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rene_data', models.DateField(blank=True, null=True)),
                ('rene_stat', models.CharField(choices=[('A', 'Ativa'), ('Q', 'Quebrada'), ('C', 'Concluída'), ('X', 'Cancelada')], default='A', max_length=1)),
                ('rene_usua', models.IntegerField(blank=True, null=True)),
                ('rene_obse', models.CharField(blank=True, max_length=250, null=True)),
                ('rene_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Renegociacao.Renegociado')),
            ],
            options={
                'db_table': 'renegociado',
                'managed': True,
            },
        ),
    ]
