# Generated by Django 5.2 on 2025-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('enti_empr', models.IntegerField()),
                ('enti_fili', models.CharField(default='', max_length=100)),
                ('enti_clie', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('enti_nome', models.CharField(default='', max_length=100)),
                ('enti_tipo_enti', models.CharField(choices=[('FO', 'FORNECEDOR'), ('CL', 'CLIENTE'), ('AM', 'AMBOS'), ('OU', 'OUTROS'), ('VE', 'VENDEDOR'), ('FU', 'FUNCIONÁRIOS')], default='1', max_length=100)),
                ('enti_fant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('enti_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('enti_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('enti_insc_esta', models.CharField(blank=True, max_length=11, null=True)),
                ('enti_cep', models.CharField(max_length=8)),
                ('enti_ende', models.CharField(max_length=60)),
                ('enti_nume', models.CharField(max_length=4)),
                ('enti_cida', models.CharField(max_length=60)),
                ('enti_esta', models.CharField(max_length=2)),
                ('enti_fone', models.CharField(blank=True, max_length=14, null=True)),
                ('enti_celu', models.CharField(blank=True, max_length=15, null=True)),
                ('enti_emai', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'entidades',
                'managed': 'false',
            },
        ),
        migrations.CreateModel(
            name='Sequencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sequencial', models.CharField(max_length=100, unique=True)),
                ('ultimo_valor', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sequencial',
                'managed': 'false',
            },
        ),
    ]
