# Generated by Django 2.2.28 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
