# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0003_auto_20250424_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequencial',
        ),
        migrations.RemoveField(
            model_name='entidades',
            name='enti_fili',
        ),
        migrations.AlterField(
            model_name='entidades',
            name='enti_tipo_enti',
            field=models.CharField(choices=[('FO', 'FORNECEDOR'), ('CL', 'CLIENTE'), ('AM', 'AMBOS'), ('OU', 'OUTROS'), ('VE', 'VENDEDOR'), ('FU', 'FUNCIONÁRIOS')], default='FO', max_length=100),
        ),
    ]
