# Generated by Django 2.2.28 on 2025-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entidades', '0004_auto_20250709_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidades',
            name='enti_agen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_bair',
            field=models.CharField(default='PR', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_banc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_coco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_codi_pais',
            field=models.CharField(default='1058', max_length=6),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_comp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_diag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_dico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_mobi_senh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_mobi_usua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_pais',
            field=models.CharField(default='1058', max_length=60),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_tien',
            field=models.CharField(blank=True, choices=[('B', 'BANCO'), ('C', 'CAIXA')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entidades',
            name='enti_vend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
