# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('entr_sequ', models.IntegerField(primary_key=True, serialize=False)),
                ('entr_empr', models.IntegerField(default=1)),
                ('entr_fili', models.IntegerField(default=1)),
                ('entr_prod', models.CharField(db_column='entr_prod', max_length=10)),
                ('entr_enti', models.CharField(blank=True, db_column='entr_enti', max_length=10, null=True)),
                ('entr_data', models.DateField()),
                ('entr_quan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entr_tota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entr_obse', models.CharField(blank=True, max_length=100, null=True)),
                ('entr_usua', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Entrada Estoque',
                'verbose_name_plural': 'Entradas Estoque',
                'db_table': 'entradasestoque',
                'ordering': ['entr_sequ'],
                'unique_together': {('entr_empr', 'entr_fili', 'entr_prod', 'entr_data')},
            },
        ),
    ]
