# Generated by Django 2.2.28 on 2026-03-31 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situacoes',
            fields=[
                ('situ_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('situ_nome', models.CharField(max_length=60)),
                ('situ_obse', models.TextField(blank=True, null=True)),
                ('situ_nao_list', models.BooleanField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('situ_nao_list_cp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'situacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('orca_id', models.AutoField(primary_key=True, serialize=False)),
                ('orca_empr', models.IntegerField(verbose_name='Empresa')),
                ('orca_fili', models.IntegerField(blank=True, null=True, verbose_name='Filial')),
                ('orca_desc', models.CharField(max_length=120, verbose_name='Descrição')),
                ('orca_ano', models.IntegerField(verbose_name='Ano')),
                ('orca_tipo', models.CharField(choices=[('A', 'Anual'), ('M', 'Mensal')], default='M', max_length=1, verbose_name='Tipo')),
                ('orca_cena', models.CharField(choices=[('R', 'Realista'), ('P', 'Pessimista'), ('O', 'Otimista')], default='R', max_length=1, verbose_name='Cenário')),
                ('orca_ativ', models.BooleanField(default=True, verbose_name='Ativo')),
                ('orca_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orcamento_financeiro_cc',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('orci_id', models.AutoField(primary_key=True, serialize=False)),
                ('orci_empr', models.IntegerField(verbose_name='Empresa')),
                ('orci_fili', models.IntegerField(blank=True, null=True, verbose_name='Filial')),
                ('orci_orca', models.IntegerField(verbose_name='ID Orçamento')),
                ('orci_cecu', models.IntegerField(verbose_name='Centro de Custo')),
                ('orci_ano', models.IntegerField(verbose_name='Ano')),
                ('orci_mes', models.IntegerField(verbose_name='Mês')),
                ('orci_valo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('orci_obse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'orcamentoitem_financeiro_cc',
                'ordering': ['orci_id'],
                'unique_together': {('orci_empr', 'orci_fili', 'orci_orca', 'orci_cecu', 'orci_ano', 'orci_mes')},
            },
        ),
    ]
