# Generated by Django 2.2.28 on 2026-03-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produtos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_empr', models.IntegerField()),
                ('form_fili', models.IntegerField()),
                ('form_vers', models.IntegerField()),
                ('form_ativ', models.BooleanField(default=True)),
                ('form_prod', models.ForeignKey(db_column='form_prod', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.Produtos')),
            ],
            options={
                'db_table': 'formulaproduto',
                'managed': True,
                'unique_together': {('form_empr', 'form_fili', 'form_prod', 'form_vers')},
            },
        ),
        migrations.CreateModel(
            name='FormulaSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_empr', models.IntegerField()),
                ('said_fili', models.IntegerField()),
                ('said_quan', models.DecimalField(decimal_places=4, max_digits=15)),
                ('said_perc_cust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('said_principal', models.BooleanField(default=False)),
                ('said_form', models.ForeignKey(db_column='said_form', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='formulacao.FormulaProduto')),
                ('said_prod', models.ForeignKey(db_column='said_prod', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.Produtos')),
            ],
            options={
                'db_table': 'formulasaida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('op_empr', models.IntegerField()),
                ('op_fili', models.IntegerField()),
                ('op_nume', models.IntegerField(primary_key=True, serialize=False)),
                ('op_data', models.DateField()),
                ('op_data_hora', models.DateTimeField(blank=True, null=True)),
                ('op_vers', models.IntegerField()),
                ('op_quan', models.DecimalField(decimal_places=4, max_digits=15)),
                ('op_status', models.CharField(max_length=1)),
                ('op_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('op_prod', models.ForeignKey(db_column='op_prod', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.Produtos')),
            ],
            options={
                'db_table': 'opformulacao',
                'managed': True,
                'unique_together': {('op_empr', 'op_fili', 'op_nume')},
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_empr', models.IntegerField()),
                ('form_fili', models.IntegerField()),
                ('form_vers', models.IntegerField()),
                ('form_item', models.IntegerField()),
                ('form_qtde', models.DecimalField(decimal_places=4, max_digits=15)),
                ('form_perd_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('form_form', models.ForeignKey(db_column='form_form', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='formulacao.FormulaProduto')),
                ('form_insu', models.ForeignKey(db_column='form_insu', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Produtos.Produtos')),
            ],
            options={
                'db_table': 'formulaitem',
                'managed': True,
                'unique_together': {('form_empr', 'form_fili', 'form_insu', 'form_vers', 'form_item')},
            },
        ),
    ]
