# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lctobancario',
            fields=[
                ('laba_empr', models.IntegerField()),
                ('laba_fili', models.IntegerField()),
                ('laba_banc', models.IntegerField()),
                ('laba_ctrl', models.IntegerField(primary_key=True, serialize=False)),
                ('laba_data', models.DateField(blank=True, null=True)),
                ('laba_tire', models.IntegerField(blank=True, null=True)),
                ('laba_cont', models.IntegerField(blank=True, null=True)),
                ('laba_cecu', models.IntegerField(blank=True, null=True)),
                ('laba_valo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('laba_even', models.IntegerField(blank=True, null=True)),
                ('laba_soci', models.CharField(blank=True, max_length=20, null=True)),
                ('laba_codi_hist', models.IntegerField(blank=True, null=True)),
                ('laba_hist', models.TextField(blank=True, null=True)),
                ('laba_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('laba_ctrl_ctb', models.IntegerField(blank=True, null=True)),
                ('laba_dbcr', models.CharField(blank=True, max_length=1, null=True)),
                ('laba_nume_mens', models.IntegerField(blank=True, null=True)),
                ('laba_enti', models.IntegerField(blank=True, null=True)),
                ('laba_cheq', models.IntegerField(blank=True, null=True)),
                ('laba_data_comp', models.DateField(blank=True, null=True)),
                ('laba_cheq_comp', models.BooleanField(blank=True, null=True)),
                ('laba_data_bomp', models.DateField(blank=True, null=True)),
                ('laba_nomi', models.CharField(blank=True, max_length=65, null=True)),
                ('laba_inte', models.BooleanField(blank=True, null=True)),
                ('laba_desc_pont', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('laba_ctrl_paga', models.IntegerField(blank=True, null=True)),
                ('laba_ctrc_rece', models.IntegerField(blank=True, null=True)),
                ('laba_soli_adto', models.IntegerField(blank=True, null=True)),
                ('laba_mens_feri', models.BooleanField(blank=True, null=True)),
                ('laba_dife_depe', models.BooleanField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('laba_pag_for', models.BooleanField(blank=True, null=True)),
                ('laba_audi', models.BooleanField(blank=True, null=True)),
                ('laba_audi_data', models.DateField(blank=True, null=True)),
                ('laba_audi_por', models.IntegerField(blank=True, null=True)),
                ('laba_data_reci', models.DateField(blank=True, null=True)),
                ('laba_via_reci', models.IntegerField(blank=True, null=True)),
                ('laba_tiop', models.IntegerField(blank=True, null=True)),
                ('laba_prat', models.IntegerField(blank=True, null=True)),
                ('lanc_proj_resp_paga', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lctobancario',
                'managed': False,
            },
        ),
    ]
