# Generated by Django 2.2.28 on 2025-09-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Licencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlevisita',
            fields=[
                ('ctrl_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl_numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('ctrl_data', models.DateField(blank=True, null=True, verbose_name='Data da Visita')),
                ('ctrl_novo', models.IntegerField(blank=True, null=True, verbose_name='Novo Cliente')),
                ('ctrl_base', models.IntegerField(blank=True, null=True, verbose_name='Base')),
                ('ctrl_prop', models.IntegerField(blank=True, null=True, verbose_name='Proposta')),
                ('ctrl_leva', models.IntegerField(blank=True, null=True, verbose_name='Levantamento')),
                ('ctrl_proj', models.IntegerField(blank=True, null=True, verbose_name='Projeto')),
                ('ctrl_obse', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ctrl_contato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato')),
                ('ctrl_fone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('field_log_data', models.DateField(auto_now_add=True, db_column='_log_data', null=True, verbose_name='Data Log')),
                ('field_log_time', models.TimeField(auto_now_add=True, db_column='_log_time', null=True, verbose_name='Hora Log')),
                ('ctrl_km_inic', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='KM Inicial')),
                ('ctrl_km_fina', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='KM Final')),
                ('ctrl_prox_visi', models.DateField(blank=True, null=True, verbose_name='Próxima Visita')),
                ('ctrl_nume_orca', models.IntegerField(blank=True, null=True, verbose_name='Número Orçamento')),
            ],
            options={
                'verbose_name': 'Controle de Visita',
                'verbose_name_plural': 'Controles de Visitas',
                'db_table': 'controlevisita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapavisita',
            fields=[
                ('etap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('etap_nume', models.IntegerField()),
                ('etap_descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('etap_obse', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Etapa de Visita',
                'verbose_name_plural': 'Etapas de Visitas',
                'db_table': 'etapavisita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensVisita',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_fili', models.IntegerField(db_column='item_fili')),
                ('item_prod', models.CharField(max_length=60, verbose_name='Produto/Serviço')),
                ('item_desc_prod', models.TextField(blank=True, null=True, verbose_name='Descrição do Produto')),
                ('item_quan', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Quantidade')),
                ('item_unit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('item_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total')),
                ('item_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Desconto')),
                ('item_unli', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('item_data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('item_obse', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('item_empr', models.ForeignKey(db_column='item_empr', on_delete=django.db.models.deletion.CASCADE, to='Licencas.Empresas')),
                ('item_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_visita', to='controledevisitas.Controlevisita')),
            ],
            options={
                'verbose_name': 'Item de Visita',
                'verbose_name_plural': 'Itens de Visita',
                'db_table': 'itensvisita',
                'unique_together': {('item_empr', 'item_fili', 'item_visita', 'item_prod')},
            },
        ),
    ]
