# Generated by Django 2.2.28 on 2025-09-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledevisitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensvisita',
            name='item_prod',
            field=models.CharField(max_length=60, verbose_name='Código do Produto'),
        ),
    ]
