# Generated by Django 2.2.28 on 2025-09-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledevisitas', '0002_auto_20250901_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvisita',
            name='item_caix',
            field=models.IntegerField(blank=True, null=True, verbose_name='Caixas Necessárias'),
        ),
        migrations.AddField(
            model_name='itensvisita',
            name='item_m2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Metragem (m²)'),
        ),
        migrations.AddField(
            model_name='itensvisita',
            name='item_nome_ambi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Ambiente'),
        ),
        migrations.AddField(
            model_name='itensvisita',
            name='item_queb',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, null=True, verbose_name='% Quebra'),
        ),
        migrations.AddField(
            model_name='itensvisita',
            name='item_tipo_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PISOS', 'Pisos')], default='NORMAL', max_length=10, verbose_name='Tipo de Cálculo'),
        ),
    ]
