# Generated by Django 2.2.28 on 2025-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledevisitas', '0003_auto_20250901_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensvisita',
            name='item_tipo_calculo',
            field=models.CharField(choices=[('normal', 'Normal'), ('pisos', 'Pisos')], default='normal', max_length=10, verbose_name='Tipo de Cálculo'),
        ),
    ]
