# Generated by Django 2.2.28 on 2026-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraICMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_origem', models.CharField(max_length=2)),
                ('uf_destino', models.CharField(max_length=2)),
                ('contribuinte', models.BooleanField()),
                ('simples_nacional', models.BooleanField()),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aliquota_destino', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota Interna Destino (DIFAL)')),
                ('reducao_base', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mva_st', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('aliquota_st', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('reducao_base_st', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('cst', models.CharField(max_length=3)),
                ('csosn', models.CharField(blank=True, max_length=4, null=True)),
                ('diferimento', models.BooleanField(default=False)),
                ('isento', models.BooleanField(default=False)),
            ],
        ),
    ]
