# Generated by Django 2.2.28 on 2026-03-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transportes", "0002_regraicms"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Mdfe",
                    fields=[
                        ("mdf_id", models.AutoField(primary_key=True, serialize=False, db_column="mdf_id", verbose_name="ID MDFe")),
                    ],
                    options={
                        "managed": False,
                        "db_table": "mdfe",
                        "verbose_name": "MDFe",
                        "verbose_name_plural": "MDFes",
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="MdfeDocumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_doc", models.CharField(choices=[("00", "NFe"), ("01", "CTe")], db_column="mdfd_tipo", default="00", max_length=2, verbose_name="Tipo Documento")),
                ("chave", models.CharField(blank=True, db_column="mdfd_chave", max_length=44, null=True, verbose_name="Chave (44 dígitos)")),
                ("cmun_descarga", models.CharField(blank=True, db_column="mdfd_cmun_desc", max_length=7, null=True, verbose_name="Município Descarga (IBGE)")),
                ("xmun_descarga", models.CharField(blank=True, db_column="mdfd_xmun_desc", max_length=60, null=True, verbose_name="Nome Município Descarga")),
                ("mdfe", models.ForeignKey(db_column="mdfd_mdfe_id", db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name="documentos", to="transportes.Mdfe")),
            ],
            options={
                "managed": True,
                "db_table": "mdfe_documento",
            },
        ),
    ]
