# Generated by Django 2.2.28 on 2026-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_mdfedocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdfeantt',
            fields=[
                ('mdfe_antt_id', models.IntegerField(db_column='mdfe_antt_id', primary_key=True, serialize=False, verbose_name='ID MDFe ANTT')),
                ('mdfe_antt_rntrc', models.IntegerField(blank=True, db_column='mdfe_antt_rntrc', null=True, verbose_name='RNTRC')),
                ('mdfe_antt_ciot', models.IntegerField(blank=True, db_column='mdfe_antt_ciot', null=True, verbose_name='CIOT')),
                ('mdfe_antt_cpf', models.CharField(blank=True, db_column='mdfe_antt_cpf', max_length=11, null=True, verbose_name='CPF')),
                ('mdfe_antt_cnpj', models.CharField(blank=True, db_column='mdfe_antt_cnpj', max_length=14, null=True, verbose_name='CNPJ')),
            ],
            options={
                'db_table': 'mdfeantt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mdfecontratante',
            fields=[
                ('mdfe_cont_id', models.IntegerField(db_column='mdfe_cont_id', primary_key=True, serialize=False, verbose_name='ID Contratante')),
                ('mdfe_cont_cont', models.IntegerField(blank=True, db_column='mdfe_cont_cont', null=True, verbose_name='ID Contratante')),
                ('mdfe_cont_cnpj_cpf', models.CharField(blank=True, db_column='mdfe_cont_cnpj_cpf', max_length=255, null=True, verbose_name='CNPJ ou CPF do Contratante')),
            ],
            options={
                'verbose_name': 'MDFe Contratante',
                'verbose_name_plural': 'MDFes Contratantes',
                'db_table': 'mdfecontratante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mdfeseguro',
            fields=[
                ('mdfe_segu_id', models.IntegerField(db_column='mdfe_segu_id', primary_key=True, serialize=False, verbose_name='ID Seguro')),
                ('mdfe_segu_resp', models.IntegerField(blank=True, choices=[(1, 'Emitente'), (2, 'Contratante')], db_column='mdfe_segu_resp', null=True, verbose_name='ID Responsável')),
                ('mdfe_segu_cnpj_resp', models.CharField(blank=True, db_column='mdfe_segu_cnpj_resp', max_length=14, null=True, verbose_name='CNPJ do Responsável')),
                ('mdfe_segu_cpf_resp', models.CharField(blank=True, db_column='mdfe_segu_cpf_resp', max_length=11, null=True, verbose_name='CPF do Responsável')),
                ('mdfe_segu_nome_segu', models.CharField(blank=True, db_column='mdfe_segu_nome_segu', max_length=30, null=True, verbose_name='Nome do Seguro')),
                ('mdfe_segu_cnpj_segu', models.CharField(blank=True, db_column='mdfe_segu_cnpj_segu', max_length=14, null=True, verbose_name='CNPJ do Seguro')),
                ('mdfe_segu_apol', models.CharField(blank=True, db_column='mdfe_segu_apol', max_length=20, null=True, verbose_name='Número do Apólice')),
                ('mdfe_segu_aver', models.CharField(blank=True, db_column='mdfe_segu_aver', max_length=40, null=True, verbose_name='Número da averbação')),
            ],
            options={
                'db_table': 'mdfeseguro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotoristaDocumento',
            fields=[
                ('id', models.AutoField(db_column='moto_docu_id', primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(db_column='moto_tipo_doc', max_length=30)),
                ('empresa', models.IntegerField(db_column='moto_empr')),
                ('filial', models.IntegerField(db_column='moto_fili')),
                ('entidade', models.IntegerField(db_column='moto_enti')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('valido', 'Válido'), ('vencendo', 'Vencendo'), ('vencido', 'Vencido')], db_column='moto_stat', default='pendente', max_length=20)),
                ('numero', models.CharField(blank=True, db_column='moto_nume', max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, db_column='moto_data_emis', null=True)),
                ('data_validade', models.DateField(blank=True, db_column='moto_data_val', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='moto_cria_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='moto_atual_em')),
                ('alerta_em_dias', models.IntegerField(db_column='moto_alerta_dias', default=30)),
                ('observacoes', models.TextField(blank=True, db_column='moto_obse', null=True)),
                ('anexos', models.TextField(blank=True, db_column='moto_anexos', null=True)),
            ],
            options={
                'db_table': 'motoristas_documentos',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoMotorista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tdoc_desc', max_length=100)),
                ('slug', models.CharField(db_column='tdoc_slug', max_length=30, unique=True)),
                ('exige_validade', models.BooleanField(db_column='tdoc_exige_val', default=True)),
                ('alerta_padrao_dias', models.IntegerField(db_column='tdoc_alerta', default=30)),
                ('ativo', models.BooleanField(db_column='tdoc_ativo', default=True)),
            ],
            options={
                'db_table': 'tipos_documentos_motoristas',
                'ordering': ('descricao',),
            },
        ),
        migrations.AlterField(
            model_name='ctedocumento',
            name='tipo_doc',
            field=models.CharField(choices=[('00', 'NFe'), ('01', 'CTe'), ('02', 'DANFE TERCEIROS')], db_column='ctdo_tipo', default='00', max_length=2, verbose_name='Tipo Documento'),
        ),
        migrations.CreateModel(
            name='MotoristasCadastros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.IntegerField(db_column='moto_empr')),
                ('filial', models.IntegerField(db_column='moto_fili')),
                ('entidade', models.IntegerField(db_column='moto_enti')),
                ('status', models.CharField(choices=[('ATV', 'Ativo'), ('INA', 'Inativo'), ('BLO', 'Bloqueado')], db_column='moto_stat', default='ATV', max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='moto_cria_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='moto_atual_em')),
            ],
            options={
                'db_table': 'motoristas',
                'ordering': ('-criado_em',),
                'unique_together': {('empresa', 'filial', 'entidade')},
            },
        ),
        migrations.CreateModel(
            name='MotoristaDadosComplementares',
            fields=[
                ('id', models.AutoField(db_column='mdad_id', primary_key=True, serialize=False)),
                ('empresa', models.IntegerField(db_column='mdad_empr')),
                ('filial', models.IntegerField(db_column='mdad_fili')),
                ('entidade', models.IntegerField(db_column='mdad_enti')),
                ('cnh_numero', models.CharField(blank=True, db_column='mdad_cnh', max_length=20, null=True)),
                ('cnh_categoria', models.CharField(blank=True, db_column='mdad_cnh_cat', max_length=5, null=True)),
                ('cnh_validade', models.DateField(blank=True, db_column='mdad_cnh_val', null=True)),
                ('rg_numero', models.CharField(blank=True, db_column='mdad_rg', max_length=20, null=True)),
                ('ear', models.BooleanField(db_column='mdad_ear', default=False)),
                ('ear_validade', models.DateField(blank=True, db_column='mdad_ear_val', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='mdad_cria_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='mdad_atual_em')),
            ],
            options={
                'db_table': 'motoristas_dados_complementares',
                'ordering': ('-criado_em',),
                'unique_together': {('empresa', 'filial', 'entidade')},
            },
        ),
    ]
