# Generated by Django 2.2.28 on 2026-04-15 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportes", "0004_auto_20260414_1109"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE abastecusto
            ADD COLUMN IF NOT EXISTS abas_veic_sequ integer;
            """,
            reverse_sql="""
            ALTER TABLE abastecusto
            DROP COLUMN IF EXISTS abas_veic_sequ;
            """,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE abastecusto
            ADD COLUMN IF NOT EXISTS abas_plac varchar(7);
            """,
            reverse_sql="""
            ALTER TABLE abastecusto
            DROP COLUMN IF EXISTS abas_plac;
            """,
        ),
    ]

