# Generated by Django 2.2.28 on 2026-04-15 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transportes", "0005_abastecusto_veiculo_cols"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS bombasaldos (
                bomb_id bigserial,
                bomb_empr integer not null,
                bomb_fili integer not null,
                bomb_bomb varchar(10),
                bomb_comb varchar(10),
                bomb_sald numeric(15,4),
                bomb_tipo_movi integer,
                bomb_data date,
                bomb_usua integer
            );

            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_empr integer;
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_fili integer;
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_bomb varchar(10);
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_comb varchar(10);
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_sald numeric(15,4);
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_tipo_movi integer;
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_data date;
            ALTER TABLE bombasaldos
            ADD COLUMN IF NOT EXISTS bomb_usua integer;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'bombasaldos'
                      AND column_name = 'bomb_id'
                ) THEN
                    ALTER TABLE bombasaldos ADD COLUMN bomb_id bigserial;
                END IF;
            END $$;

            UPDATE bombasaldos
            SET bomb_id = nextval(pg_get_serial_sequence('bombasaldos', 'bomb_id'))
            WHERE bomb_id IS NULL;

            ALTER TABLE bombasaldos
            ALTER COLUMN bomb_id SET NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS bombasaldos_bomb_id_uq
            ON bombasaldos (bomb_id);

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint c
                    JOIN pg_class t ON t.oid = c.conrelid
                    WHERE t.relname = 'bombasaldos'
                      AND c.contype = 'p'
                ) THEN
                    ALTER TABLE bombasaldos ADD CONSTRAINT bombasaldos_pk PRIMARY KEY (bomb_id);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS bombasaldos_bomb_id_uq;
            ALTER TABLE bombasaldos DROP COLUMN IF EXISTS bomb_id;
            """,
        ),
    ]

