from django.db import models


class Veiculos(models.Model):
    veic_empr = models.IntegerField(primary_key=True, verbose_name='Empresa')
    veic_tran = models.IntegerField(verbose_name='Transportadora')
    veic_sequ = models.IntegerField(verbose_name='Sequencial')
    veic_espe = models.CharField(max_length=40, blank=True, null=True, verbose_name='Especie')
    veic_marc = models.CharField(max_length=40, blank=True, null=True, verbose_name='Marca')
    veic_frot = models.CharField(max_length=6, blank=True, null=True, verbose_name='Frota')
    veic_aqui = models.DateField(blank=True, null=True, verbose_name='Aquisição')
    veic_ano_fabr = models.CharField(max_length=4, blank=True, null=True, verbose_name='Ano de Fabricação')
    veic_ano_mode = models.CharField(max_length=4, blank=True, null=True, verbose_name='Ano de Modelo')
    veic_cor = models.CharField(max_length=40, blank=True, null=True, verbose_name='Cor')
    veic_tipo = models.CharField(max_length=1, blank=True, null=True, verbose_name='Tipo')
    veic_baix = models.DateField(blank=True, null=True, verbose_name='Baixado')
    veic_moti = models.CharField(max_length=40, blank=True, null=True, verbose_name='Motivo')
    veic_chass = models.CharField(max_length=17, blank=True, null=True, verbose_name='Chassi')
    veic_nume_moto = models.CharField(max_length=40, blank=True, null=True, verbose_name='Número da Moto')
    veic_rena = models.CharField(max_length=11, blank=True, null=True, verbose_name='Renavam')
    veic_rena_expe = models.DateField(blank=True, null=True, verbose_name='Expiração do Renavam')
    veic_nome_segu = models.CharField(max_length=40, blank=True, null=True, verbose_name='Nome do Seguidor')
    veic_venc_segu = models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguidor')
    veic_comb = models.CharField(max_length=1, blank=True, null=True, verbose_name='Combustível')
    veic_plac = models.CharField(max_length=7, blank=True, null=True, verbose_name='Placa')
    veic_cida = models.CharField(max_length=7, blank=True, null=True, verbose_name='Cidade')
    veic_nome_cida = models.CharField(max_length=60, blank=True, null=True, verbose_name='Nome da Cidade')
    veic_esta = models.CharField(max_length=2, blank=True, null=True, verbose_name='Estado')
    veic_valo_aqui = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, verbose_name='Valor Aquisição')
    veic_venc_exti = models.DateField(blank=True, null=True, verbose_name='Vencimento Extintor')
    veic_ipva = models.DateField(blank=True, null=True, verbose_name='IPVA')
    veic_segu_obri = models.DateField(blank=True, null=True, verbose_name='Seguidor Obrigatório')
    veic_capa = models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True, verbose_name='Capacidade')
    veic_adic_km = models.IntegerField(blank=True, null=True, verbose_name='Adicional KM')
    veic_moto = models.IntegerField(blank=True, null=True, verbose_name='Motorista')
    veic_perc_comi = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name='Percentual Comissão')
    veic_agre = models.BooleanField(blank=True, null=True, verbose_name='Agregado')
    veic_inic_agre = models.DateField(blank=True, null=True, verbose_name='Início do Agregado')
    veic_fim_agre = models.DateField(blank=True, null=True, verbose_name='Fim do Agregado')
    veic_inat = models.BooleanField(blank=True, null=True, verbose_name='Inativo')
    veic_tara_km = models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True, verbose_name='Tara KM')
    veic_capa_km = models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True, verbose_name='Capacidade KM')
    veic_capa_m3 = models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True, verbose_name='Capacidade M3')
    veic_eixo = models.IntegerField(blank=True, null=True, verbose_name='Eixo')
    veic_impl = models.CharField(max_length=20, blank=True, null=True, verbose_name='Implementação')
    veic_rntr = models.CharField(max_length=8, blank=True, null=True, verbose_name='RNTR')
    veic_prop_veic = models.CharField(max_length=1, blank=True, null=True, verbose_name='Proprietário do Veículo')
    veic_tipo_veic = models.CharField(max_length=1, blank=True, null=True, verbose_name='Tipo de Veículo')
    veic_tipo_roda = models.CharField(max_length=2, blank=True, null=True, verbose_name='Tipo de Roda')
    veic_tipo_carr = models.CharField(max_length=2, blank=True, null=True, verbose_name='Tipo de Carroceria')
    veic_car1 = models.IntegerField(blank=True, null=True, verbose_name='Carroceria 1')
    veic_car2 = models.IntegerField(blank=True, null=True, verbose_name='Carroceria 2')
    veic_car3 = models.IntegerField(blank=True, null=True, verbose_name='Carroceria 3')
    veic_car4 = models.IntegerField(blank=True, null=True, verbose_name='Carroceria 4')
    veic_tipo_prop = models.CharField(max_length=1, blank=True, null=True, verbose_name='Tipo de Proprietário')
    veic_fili_patr = models.IntegerField(blank=True, null=True, verbose_name='Filial da Proprietária')
    veic_codi_patr = models.CharField(max_length=13, blank=True, null=True, verbose_name='Código da Proprietária')
    veic_moni = models.CharField(max_length=40, blank=True, null=True, verbose_name='Monitor')
    veic_nume_rast = models.CharField(max_length=40, blank=True, null=True, verbose_name='Número de Rastreio')
    veic_obse = models.TextField(blank=True, null=True, verbose_name='Observações')
    veic_cecu = models.IntegerField(blank=True, null=True, verbose_name='Código do CC')

    class Meta:
        managed = False
        db_table = 'veiculos'
        unique_together = (('veic_empr', 'veic_tran', 'veic_sequ'),)