# Generated by Django 2.2.28 on 2026-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nome', models.CharField(max_length=100)),
                ('plan_prec', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_desc', models.TextField()),
                ('plan_trial', models.BooleanField(default=False)),
                ('plan_trial_dias', models.IntegerField(default=15)),
                ('plan_data_ativ', models.DateTimeField(blank=True, null=True)),
                ('plan_data_expi', models.DateTimeField(blank=True, null=True)),
                ('plan_ativ', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'planos',
                'ordering': ['id', 'plan_nome'],
            },
        ),
    ]
