# Generated by Django 5.2 on 2025-04-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCTabUsers',
            fields=[
                ('uciduser', models.AutoField(primary_key=True, serialize=False)),
                ('ucusername', models.CharField(max_length=150, unique=True)),
                ('uclogin', models.CharField(max_length=150)),
                ('ucpassword', models.CharField(max_length=128)),
                ('ucemail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'uctabusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empr_codi', models.AutoField(db_column='empr_codi', primary_key=True, serialize=False)),
                ('empr_nome', models.CharField(db_column='empr_nome', max_length=100, verbose_name='Nome da Empresa')),
                ('empr_docu', models.CharField(db_column='empr_cnpj', max_length=14, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Filiais',
            fields=[
                ('empr_empr', models.IntegerField(db_column='empr_empr', primary_key=True, serialize=False)),
                ('empr_nome', models.CharField(db_column='empr_nome', max_length=100, verbose_name='Nome da Filial')),
                ('empr_docu', models.CharField(db_column='empr_cnpj', max_length=14, unique=True, verbose_name='CNPJ da Filial')),
                ('empr_codi', models.ForeignKey(db_column='empr_codi', on_delete=django.db.models.deletion.CASCADE, to='Auth.empresas')),
            ],
            options={
                'db_table': 'filiais',
            },
        ),
        migrations.CreateModel(
            name='UserEmpresaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresas', to='Auth.empresas')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_filiais', to='Auth.filiais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_filiais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_empresa_filial',
                'unique_together': {('user', 'empresa', 'filial')},
            },
        ),
    ]
