# Generated by Django 5.2 on 2025-04-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCTabUsers',
            fields=[
                ('uciduser', models.AutoField(primary_key=True, serialize=False)),
                ('ucusername', models.CharField(max_length=150)),
                ('uclogin', models.CharField(max_length=150)),
                ('ucpassword', models.CharField(max_length=128)),
                ('ucemail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'uctabusers',
                'managed': False,
            },
        ),
    ]
