# Generated by Django 2.2.28 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencas',
            fields=[
                ('lice_id', models.AutoField(primary_key=True, serialize=False)),
                ('lice_docu', models.CharField(max_length=14, unique=True)),
                ('lice_nome', models.CharField(max_length=100)),
                ('lice_emai', models.EmailField(blank=True, max_length=254, null=True)),
                ('lice_bloq', models.BooleanField(default=False)),
                ('lice_nume_empr', models.IntegerField()),
                ('lice_nume_fili', models.IntegerField()),
                ('_log_data', models.DateField(blank=True, null=True)),
                ('_log_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'licencas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserEmpresaFilial',
        ),
    ]
