# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('seri_empr', models.IntegerField()),
                ('seri_fili', models.IntegerField()),
                ('seri_codi', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('seri_nome', models.CharField(choices=[('SA', 'Nota de Saída'), ('EN', 'Nota de Entrada'), ('FR', 'Fatura a Receber'), ('FP', 'Fatura a Pagar'), ('NC', 'Nota do Consumidor')], max_length=2)),
                ('seri_docu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
    ]
