# Generated by Django 2.2.28 on 2025-04-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empr_codi', models.AutoField(db_column='empr_codi', primary_key=True, serialize=False)),
                ('empr_nome', models.CharField(db_column='empr_nome', max_length=100, verbose_name='Nome da Empresa')),
                ('empr_docu', models.CharField(db_column='empr_cnpj', max_length=14, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'db_table': 'empresas',
                'managed': 'false',
            },
        ),
        migrations.CreateModel(
            name='Licencas',
            fields=[
                ('lice_id', models.AutoField(primary_key=True, serialize=False)),
                ('lice_docu', models.CharField(max_length=14, unique=True)),
                ('lice_nome', models.CharField(max_length=100)),
                ('lice_emai', models.EmailField(blank=True, max_length=254, null=True)),
                ('lice_bloq', models.BooleanField(default=False)),
                ('lice_nume_empr', models.IntegerField()),
                ('lice_nume_fili', models.IntegerField()),
                ('_log_data', models.DateField(blank=True, null=True)),
                ('_log_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'licencas',
                'managed': 'false',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usua_codi', models.AutoField(primary_key=True, serialize=False)),
                ('usua_nome', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='usua_senh_mobi', max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': 'false',
            },
        ),
        migrations.CreateModel(
            name='Filiais',
            fields=[
                ('empr_empr', models.IntegerField(db_column='empr_empr', primary_key=True, serialize=False)),
                ('empr_nome', models.CharField(db_column='empr_nome', max_length=100, verbose_name='Nome da Filial')),
                ('empr_docu', models.CharField(db_column='empr_cnpj', max_length=14, unique=True, verbose_name='CNPJ da Filial')),
                ('empr_codi', models.ForeignKey(db_column='empr_codi', on_delete=django.db.models.deletion.CASCADE, to='Licencas.Empresas')),
            ],
            options={
                'db_table': 'filiais',
                'managed': 'false',
            },
        ),
    ]
