# Generated by Django 2.2.28 on 2025-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencas',
            name='lice_modu_libe',
            field=models.TextField(default='{}'),
        ),
    ]
