# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixageral',
            fields=[
                ('caix_empr', models.IntegerField()),
                ('caix_fili', models.IntegerField()),
                ('caix_caix', models.IntegerField()),
                ('caix_data', models.DateField(primary_key=True, serialize=False)),
                ('caix_hora', models.TimeField(auto_now_add=True)),
                ('caix_aber', models.CharField(max_length=1)),
                ('caix_oper', models.IntegerField()),
                ('caix_ecf', models.CharField(blank=True, max_length=30, null=True)),
                ('caix_orig', models.IntegerField(blank=True, null=True)),
                ('caix_valo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('caix_ctrl', models.IntegerField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
                ('caix_fech_data', models.DateField(blank=True, null=True)),
                ('caix_fech_hora', models.TimeField(blank=True, null=True)),
                ('caix_obse_fech', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caixageral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movicaixa',
            fields=[
                ('movi_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('movi_fili', models.IntegerField()),
                ('movi_caix', models.IntegerField()),
                ('movi_data', models.DateField()),
                ('movi_ctrl', models.IntegerField(verbose_name='Controle')),
                ('movi_entr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('movi_said', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('movi_tipo', models.IntegerField(choices=[('1', 'DINHEIRO'), ('2', 'CHEQUE'), ('3', 'CARTÃO DE CREDITO'), ('4', 'CARTÃO DE DEBITO'), ('5', 'CREDIÁRIO'), ('6', 'PIX')], verbose_name='Tipo de Movimento')),
                ('movi_obse', models.TextField(blank=True, null=True)),
                ('movi_oper', models.IntegerField(blank=True, null=True)),
                ('movi_hora', models.TimeField(blank=True, null=True)),
                ('movi_nume_vend', models.IntegerField(blank=True, null=True, verbose_name='Pedido de Venda')),
                ('movi_clie', models.IntegerField(blank=True, null=True, verbose_name='Cliente')),
                ('movi_vend', models.IntegerField(blank=True, null=True, verbose_name='Vendedor')),
                ('movi_cont', models.IntegerField(blank=True, null=True)),
                ('movi_even', models.IntegerField(blank=True, null=True)),
                ('movi_cecu', models.IntegerField(blank=True, null=True)),
                ('movi_cheq', models.IntegerField(blank=True, null=True)),
                ('movi_nomi', models.CharField(blank=True, max_length=40, null=True)),
                ('movi_bomp', models.DateField(blank=True, null=True)),
                ('movi_titu', models.CharField(blank=True, max_length=13, null=True, verbose_name='Titulo')),
                ('movi_seri', models.CharField(blank=True, default='CAI', max_length=5, null=True, verbose_name='Serie')),
                ('movi_parc', models.CharField(blank=True, max_length=4, null=True)),
                ('movi_cheq_banc', models.IntegerField(blank=True, null=True)),
                ('movi_cheq_agen', models.CharField(blank=True, max_length=15, null=True)),
                ('movi_cheq_cont', models.CharField(blank=True, max_length=15, null=True)),
                ('movi_seri_nota', models.CharField(blank=True, max_length=3, null=True)),
                ('movi_nume_nota', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('movi_coo', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('movi_seri_ecf', models.CharField(blank=True, max_length=20, null=True)),
                ('movi_codi_admi', models.IntegerField(blank=True, null=True)),
                ('movi_tipo_movi', models.IntegerField(blank=True, null=True)),
                ('movi_banc_tran', models.IntegerField(blank=True, null=True)),
                ('movi_sequ_tran', models.IntegerField(blank=True, null=True)),
                ('movi_sang', models.BooleanField(blank=True, null=True)),
                ('movi_vend_orig', models.IntegerField(blank=True, null=True)),
                ('movi_docu_fisc', models.IntegerField(blank=True, null=True)),
                ('movi_bare_ctrl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movicaixa',
                'managed': False,
            },
        ),
    ]
