# Generated by Django 2.2.28 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCentroCustoAnual',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expandido', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=1)),
                ('mes', models.CharField(max_length=50)),
                ('mes_num', models.IntegerField()),
                ('orcado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realizado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('perc_execucao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tem_filhos', models.BooleanField()),
                ('codigo_pai', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Centro de Custo (Anual)',
                'verbose_name_plural': 'Dashboard Centros de Custo (Anual)',
                'db_table': 'dashboardcentrocustoanual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osflorestal',
            fields=[
                ('osfl_empr', models.IntegerField()),
                ('osfl_fili', models.IntegerField()),
                ('osfl_orde', models.IntegerField(primary_key=True, serialize=False)),
                ('osfl_data_aber', models.DateField(blank=True, null=True)),
                ('osfl_hora_aber', models.TimeField(blank=True, null=True)),
                ('osfl_forn', models.IntegerField(blank=True, null=True)),
                ('osfl_stat', models.IntegerField(blank=True, choices=[(0, 'Aberto'), (1, 'Parcial'), (2, 'Faturada'), (3, 'Cancelada')], null=True)),
                ('osfl_situ', models.IntegerField(blank=True, null=True)),
                ('osfl_obje', models.TextField(blank=True, null=True)),
                ('osfl_func_terc_tipo', models.IntegerField(blank=True, null=True)),
                ('osfl_func_terc', models.IntegerField(blank=True, null=True)),
                ('osfl_prop', models.IntegerField(blank=True, null=True)),
                ('osfl_com_peca', models.BooleanField(blank=True, null=True)),
                ('osfl_com_serv', models.BooleanField(blank=True, null=True)),
                ('osfl_com_fina', models.BooleanField(blank=True, null=True)),
                ('osfl_libe_fatu', models.BooleanField(blank=True, null=True)),
                ('osfl_data_entr', models.DateField(blank=True, null=True)),
                ('osfl_data_fech', models.DateField(blank=True, null=True)),
                ('osfl_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('osfl_outr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('osfl_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('osfl_tota_hect', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('osfl_moti_canc', models.TextField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'osflorestal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osflorestalpecas',
            fields=[
                ('peca_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('peca_fili', models.IntegerField()),
                ('peca_orde', models.IntegerField()),
                ('peca_item', models.IntegerField()),
                ('peca_prod', models.CharField(max_length=20)),
                ('peca_quan', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_sobr', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_tota', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_hect', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('peca_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('peca_obse', models.TextField(blank=True, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'osflorestalpecas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osflorestalservicos',
            fields=[
                ('serv_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('serv_fili', models.IntegerField()),
                ('serv_orde', models.IntegerField()),
                ('serv_item', models.IntegerField()),
                ('serv_prod', models.CharField(blank=True, max_length=20, null=True)),
                ('serv_quan', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('serv_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('serv_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('serv_hect', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('serv_data', models.DateField(blank=True, null=True)),
                ('serv_obse', models.TextField(blank=True, null=True)),
                ('serv_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('field_log_data', models.DateField(blank=True, db_column='_log_data', null=True)),
                ('field_log_time', models.TimeField(blank=True, db_column='_log_time', null=True)),
            ],
            options={
                'db_table': 'osflorestalservicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propriedades',
            fields=[
                ('prop_empr', models.IntegerField(verbose_name='Empresa')),
                ('prop_fili', models.IntegerField(verbose_name='Filial')),
                ('prop_codi', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('prop_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Propriedade')),
                ('prop_hect', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Hectares')),
                ('prop_sigl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('prop_data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('prop_inat', models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'db_table': 'propriedades',
                'managed': False,
            },
        ),
    ]
