# Generated by Django 2.2.28 on 2025-12-03 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralDeAjuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cent_empr', models.IntegerField()),
                ('cent_modu', models.CharField(choices=[('1', 'Cadastros'), ('2', 'Estoque'), ('3', 'Vendas e Saídas'), ('4', 'Compras e Entradas'), ('5', 'Financeiro'), ('6', 'Caixa Diário'), ('7', 'Outros')], max_length=2)),
                ('cent_titu', models.CharField(max_length=255)),
                ('cent_cont', models.TextField()),
                ('cent_data_cria', models.DateTimeField(auto_now_add=True)),
                ('cent_data_atual', models.DateTimeField(auto_now=True)),
                ('cent_video', models.CharField(blank=True, max_length=255, null=True)),
                ('cent_usua_crio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cent_data_cria'],
            },
        ),
        migrations.CreateModel(
            name='CentralProgresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ajuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centraldeajuda.CentralDeAjuda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
