# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordemservico',
            fields=[
                ('orde_empr', models.IntegerField()),
                ('orde_fili', models.IntegerField()),
                ('orde_nume', models.IntegerField(primary_key=True, serialize=False)),
                ('orde_tipo', models.CharField(choices=[('1', 'Manutenção'), ('2', 'Revisão'), ('3', 'Upgrade')], default='1', max_length=20)),
                ('orde_data_aber', models.DateField(auto_now_add=True)),
                ('orde_hora_aber', models.TimeField(auto_now_add=True)),
                ('orde_stat_orde', models.IntegerField(choices=[(0, 'Aberta'), (1, 'Orçamento gerado'), (2, 'Aguardando Liberação'), (3, 'Liberada'), (4, 'Finalizada'), (5, 'Reprovada'), (20, 'Faturada_parcial')], default=0)),
                ('orde_seto', models.IntegerField(blank=True, null=True)),
                ('orde_prio', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('urgente', 'Urgente')], default='alerta', max_length=10)),
                ('orde_prob', models.TextField(blank=True, null=True)),
                ('orde_defe_desc', models.TextField(blank=True, null=True)),
                ('orde_obse', models.TextField(blank=True, null=True)),
                ('orde_plac', models.CharField(blank=True, max_length=20, null=True)),
                ('orde_enti', models.IntegerField(blank=True, null=True)),
                ('orde_data_fech', models.DateField(blank=True, null=True)),
                ('orde_hora_fech', models.TimeField(blank=True, null=True)),
                ('orde_tipo_serv', models.IntegerField(blank=True, null=True)),
                ('orde_usua_aber', models.IntegerField(blank=True, null=True)),
                ('orde_ulti_usua', models.CharField(blank=True, max_length=100, null=True)),
                ('orde_ulti_alte', models.DateTimeField(blank=True, null=True)),
                ('orde_tota', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'ordemservico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoFaseSetor',
            fields=[
                ('osfs_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('osfs_nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ordemservicofasesetor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemservicoimgantes',
            fields=[
                ('iman_id', models.AutoField(primary_key=True, serialize=False)),
                ('iman_empr', models.IntegerField()),
                ('iman_fili', models.IntegerField()),
                ('iman_orde', models.IntegerField()),
                ('iman_codi', models.IntegerField()),
                ('iman_come', models.TextField(blank=True, null=True)),
                ('iman_imag', models.BinaryField(blank=True, null=True)),
                ('iman_obse', models.CharField(blank=True, max_length=255, null=True)),
                ('img_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('img_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('img_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ordemservicoimgantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemservicoimgdepois',
            fields=[
                ('imde_id', models.AutoField(primary_key=True, serialize=False)),
                ('imde_empr', models.IntegerField()),
                ('imde_fili', models.IntegerField()),
                ('imde_orde', models.IntegerField()),
                ('imde_codi', models.IntegerField()),
                ('imde_come', models.TextField(blank=True, null=True)),
                ('imde_imag', models.BinaryField(blank=True, null=True)),
                ('imde_obse', models.CharField(blank=True, max_length=255, null=True)),
                ('img_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('img_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('img_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ordemservicoimgdepois',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemservicoimgdurante',
            fields=[
                ('imdu_id', models.AutoField(primary_key=True, serialize=False)),
                ('imdu_empr', models.IntegerField()),
                ('imdu_fili', models.IntegerField()),
                ('imdu_orde', models.IntegerField()),
                ('imdu_codi', models.IntegerField()),
                ('imdu_come', models.TextField(blank=True, null=True)),
                ('imdu_imag', models.BinaryField(blank=True, null=True)),
                ('imdu_obse', models.CharField(blank=True, max_length=255, null=True)),
                ('img_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('img_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('img_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ordemservicoimgdurante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemservicopecas',
            fields=[
                ('peca_id', models.IntegerField(primary_key=True, serialize=False)),
                ('peca_empr', models.IntegerField()),
                ('peca_fili', models.IntegerField()),
                ('peca_orde', models.IntegerField()),
                ('peca_codi', models.CharField(max_length=20)),
                ('peca_comp', models.TextField(blank=True, null=True)),
                ('peca_quan', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('peca_tota', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'ordemservicopecas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemservicoservicos',
            fields=[
                ('serv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('serv_empr', models.IntegerField()),
                ('serv_fili', models.IntegerField()),
                ('serv_orde', models.IntegerField()),
                ('serv_sequ', models.IntegerField()),
                ('serv_codi', models.CharField(max_length=20)),
                ('serv_comp', models.TextField(blank=True, null=True)),
                ('serv_quan', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('serv_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('serv_tota', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'ordemservicoservicos',
                'managed': False,
            },
        ),
    ]
