# Generated by Django 2.2.28 on 2025-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemdeServico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoWorkflow',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('hist_empr', models.IntegerField()),
                ('hist_fili', models.IntegerField()),
                ('hist_orde', models.IntegerField()),
                ('hist_seto_orig', models.IntegerField(blank=True, null=True)),
                ('hist_seto_dest', models.IntegerField()),
                ('hist_usua', models.IntegerField()),
                ('hist_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_workflow',
                'ordering': ['-hist_data'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSetor',
            fields=[
                ('wkfl_id', models.AutoField(primary_key=True, serialize=False)),
                ('wkfl_seto_orig', models.IntegerField()),
                ('wkfl_seto_dest', models.IntegerField()),
                ('wkfl_orde', models.IntegerField(default=1)),
                ('wkfl_ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workflow_setor',
                'ordering': ['wkfl_orde'],
                'unique_together': {('wkfl_seto_orig', 'wkfl_seto_dest')},
            },
        ),
    ]
