# Generated by Django 2.2.28 on 2025-09-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cole_prod', models.CharField(help_text='Código do produto', max_length=50)),
                ('cole_quan_lida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cole_data_leit', models.DateTimeField(auto_now_add=True)),
                ('cole_empr', models.CharField(help_text='Empresa da coleta', max_length=50)),
                ('cole_fili', models.CharField(help_text='Filial da coleta', max_length=50)),
                ('cole_usua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coleta de Estoque',
                'verbose_name_plural': 'Coletas de Estoque',
                'db_table': 'coletas_estoque',
            },
        ),
    ]
