# Generated by Django 2.2.28 on 2025-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletaestoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coletaestoque',
            name='cole_empr',
            field=models.IntegerField(default=1, help_text='Empresa da coleta'),
        ),
        migrations.AlterField(
            model_name='coletaestoque',
            name='cole_fili',
            field=models.IntegerField(default=1, help_text='Filial da coleta'),
        ),
    ]
