# Generated by Django 2.2.28 on 2025-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletaestoque', '0002_auto_20250911_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletaestoque',
            name='cole_data_processamento',
            field=models.DateTimeField(blank=True, help_text='Data do processamento', null=True),
        ),
        migrations.AddField(
            model_name='coletaestoque',
            name='cole_processado',
            field=models.BooleanField(default=False, help_text='Indica se a coleta foi processada'),
        ),
    ]
