# Generated by Django 2.2.28 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratosvendas',
            fields=[
                ('cont_empr', models.IntegerField()),
                ('cont_fili', models.IntegerField()),
                ('cont_cont', models.IntegerField(primary_key=True, serialize=False)),
                ('cont_data', models.DateField(blank=True, null=True)),
                ('cont_clie', models.IntegerField(blank=True, null=True)),
                ('cont_perm_alte_clie', models.BooleanField(blank=True, null=True)),
                ('cont_prod', models.CharField(blank=True, max_length=20, null=True)),
                ('cont_info_adic', models.TextField(blank=True, null=True)),
                ('cont_quan', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('cont_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('cont_perm_alte_unit', models.BooleanField(blank=True, null=True)),
                ('cont_tota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cont_entr', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('cont_sald', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('cont_cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cont_redu_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cont_aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cont_cst_pis', models.CharField(blank=True, max_length=2, null=True)),
                ('cont_aliq_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cont_cst_cofi', models.CharField(blank=True, max_length=2, null=True)),
                ('cont_aliq_cofi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cont_cfop_esta', models.IntegerField(blank=True, null=True)),
                ('cont_cfop_fora', models.IntegerField(blank=True, null=True)),
                ('cont_venc', models.DateField(blank=True, null=True)),
                ('cont_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('cont_port', models.IntegerField(blank=True, null=True)),
                ('cont_situ', models.IntegerField(blank=True, null=True)),
                ('cont_perm_alte_venc', models.BooleanField(blank=True, null=True)),
                ('cont_form', models.CharField(blank=True, max_length=2, null=True)),
                ('field_log_data', models.DateField(auto_now_add=True, db_column='_log_data')),
                ('field_log_time', models.TimeField(auto_now_add=True, db_column='_log_time')),
                ('cont_sem_fina', models.BooleanField(blank=True, null=True)),
                ('cont_tipo_fret', models.IntegerField(blank=True, null=True)),
                ('cont_tran', models.IntegerField(blank=True, null=True)),
                ('cont_veic', models.IntegerField(blank=True, null=True)),
                ('cont_cont_orig', models.CharField(blank=True, max_length=20, null=True)),
                ('cont_cond_fina', models.IntegerField(blank=True, null=True)),
                ('cont_pedi_nume', models.CharField(blank=True, max_length=15, null=True)),
                ('cont_pedi_item', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratosvendas',
                'managed': False,
            },
        ),
    ]
