from django import forms
from transportes.models import Veiculos

class VeiculosForm(forms.ModelForm):
    class Meta:
        model = Veiculos
        fields = [
            'veic_tran', 'veic_marc', 'veic_cecu', 
            'veic_plac', 'veic_espe', 'veic_frot', 
            'veic_aqui', 'veic_ano_fabr', 'veic_ano_mode', 
            'veic_cor', 'veic_tipo', 'veic_moti', 
            'veic_chass', 'veic_nume_moto', 'veic_rena', 
            'veic_rena_expe', 'veic_comb', 'veic_cida', 'veic_nome_cida',
            'veic_esta', 'veic_valo_aqui', 'veic_capa', 
            'veic_moto', 'veic_obse', 'veic_inat',
            'veic_baix', 'veic_nome_segu', 'veic_venc_segu',
            'veic_venc_exti', 'veic_ipva', 'veic_segu_obri',
            'veic_adic_km', 'veic_perc_comi', 'veic_agre',
            'veic_inic_agre', 'veic_fim_agre', 'veic_tara_km',
            'veic_capa_km', 'veic_capa_m3', 'veic_eixo',
            'veic_impl', 'veic_rntr', 'veic_prop_veic',
            'veic_tipo_veic', 'veic_tipo_roda', 'veic_tipo_carr',
            'veic_car1', 'veic_car2', 'veic_car3', 'veic_car4',
            'veic_tipo_prop', 'veic_fili_patr', 'veic_codi_patr',
            'veic_moni', 'veic_nume_rast'
        ]
        widgets = {
            'veic_tran': forms.HiddenInput(),
            'veic_marc': forms.HiddenInput(),
            'veic_cecu': forms.HiddenInput(),
            'veic_moto': forms.HiddenInput(),
            
            # Dates
            'veic_aqui': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_rena_expe': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_baix': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_venc_segu': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_venc_exti': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_ipva': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_segu_obri': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_inic_agre': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'veic_fim_agre': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),

            # Text Inputs
            'veic_plac': forms.TextInput(attrs={'class': 'form-control', 'data-mask': 'AAA-0A00'}),
            'veic_espe': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_frot': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_ano_fabr': forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}),
            'veic_ano_mode': forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}),
            'veic_cor': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_tipo': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_moti': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_chass': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_nume_moto': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_rena': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_comb': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_cida': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_nome_cida': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_esta': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '2'}),
            'veic_nome_segu': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_impl': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_rntr': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_prop_veic': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '1'}),
            'veic_tipo_veic': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '1'}),
            'veic_tipo_roda': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '2'}),
            'veic_tipo_carr': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '2'}),
            'veic_tipo_prop': forms.TextInput(attrs={'class': 'form-control', 'maxlength': '1'}),
            'veic_codi_patr': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_moni': forms.TextInput(attrs={'class': 'form-control'}),
            'veic_nume_rast': forms.TextInput(attrs={'class': 'form-control'}),

            # Numeric Inputs
            'veic_valo_aqui': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}),
            'veic_capa': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.001'}),
            'veic_adic_km': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_perc_comi': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}),
            'veic_tara_km': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.001'}),
            'veic_capa_km': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.001'}),
            'veic_capa_m3': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.001'}),
            'veic_eixo': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_fili_patr': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_car1': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_car2': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_car3': forms.NumberInput(attrs={'class': 'form-control'}),
            'veic_car4': forms.NumberInput(attrs={'class': 'form-control'}),

            # Checkbox / Textarea
            'veic_obse': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'veic_inat': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'veic_agre': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }
        labels = {
            'veic_tran': 'Transportadora',
            'veic_marc': 'Marca',
            'veic_cecu': 'Centro de Custos',
            'veic_plac': 'Placa',
            'veic_espe': 'Espécie',
            'veic_frot': 'Frota',
            'veic_aqui': 'Data de Aquisição',
            'veic_ano_fabr': 'Ano Fabricação',
            'veic_ano_mode': 'Ano Modelo',
            'veic_cor': 'Cor',
            'veic_tipo': 'Tipo',
            'veic_moti': 'Motivo Baixa',
            'veic_chass': 'Chassi',
            'veic_nume_moto': 'Número Motor',
            'veic_rena': 'Renavam',
            'veic_rena_expe': 'Expiração Renavam',
            'veic_comb': 'Combustível',
            'veic_cida': 'Cidade',
            'veic_nome_cida': 'Nome Cidade',
            'veic_esta': 'Estado',
            'veic_valo_aqui': 'Valor Aquisição',
            'veic_capa': 'Capacidade',
            'veic_moto': 'Motorista',
            'veic_obse': 'Observações',
            'veic_inat': 'Inativo',
            'veic_baix': 'Data Baixa',
            'veic_nome_segu': 'Nome Seguradora',
            'veic_venc_segu': 'Vencimento Seguro',
            'veic_venc_exti': 'Vencimento Extintor',
            'veic_ipva': 'Data IPVA',
            'veic_segu_obri': 'Seguro Obrigatório',
            'veic_adic_km': 'Adicional KM',
            'veic_perc_comi': '% Comissão',
            'veic_agre': 'Agregado',
            'veic_inic_agre': 'Início Agregado',
            'veic_fim_agre': 'Fim Agregado',
            'veic_tara_km': 'Tara KM',
            'veic_capa_km': 'Capacidade KM',
            'veic_capa_m3': 'Capacidade M3',
            'veic_eixo': 'Eixos',
            'veic_impl': 'Implementação',
            'veic_rntr': 'RNTR',
            'veic_prop_veic': 'Proprietário Veículo',
            'veic_tipo_veic': 'Tipo Veículo',
            'veic_tipo_roda': 'Tipo Roda',
            'veic_tipo_carr': 'Tipo Carroceria',
            'veic_car1': 'Carroceria 1',
            'veic_car2': 'Carroceria 2',
            'veic_car3': 'Carroceria 3',
            'veic_car4': 'Carroceria 4',
            'veic_tipo_prop': 'Tipo Proprietário',
            'veic_fili_patr': 'Filial Proprietária',
            'veic_codi_patr': 'Cód. Proprietária',
            'veic_moni': 'Monitor',
            'veic_nume_rast': 'Nº Rastreio',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Optional: Add error class or other attributes
