# Generated by Django 2.2.28 on 2026-02-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anim_faze', models.IntegerField(db_column='anim_faze')),
                ('anim_ident', models.CharField(help_text='Número de identificação ou tag do animal', max_length=100, unique=True)),
                ('anim_raca', models.CharField(blank=True, max_length=100, null=True)),
                ('anim_data_nasc', models.DateField(blank=True, null=True)),
                ('anim_sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True)),
                ('anim_peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anim_obse', models.TextField(blank=True, null=True)),
                ('anim_empr', models.IntegerField(db_column='anim_empr')),
                ('anim_fili', models.IntegerField(db_column='anim_fili')),
            ],
            options={
                'db_table': 'agricola_animais',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoInsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apli_talh', models.CharField(db_column='apli_talh', max_length=100)),
                ('apli_prod', models.CharField(db_column='apli_prod', max_length=100)),
                ('apli_quant', models.DecimalField(decimal_places=2, help_text='Quantidade de insumo aplicada', max_digits=10)),
                ('apli_data', models.DateTimeField(auto_now_add=True)),
                ('apli_resp', models.CharField(db_column='apli_resp', max_length=100)),
                ('apli_obse', models.TextField(blank=True, null=True)),
                ('apli_empr', models.CharField(db_column='apli_empr', max_length=100)),
                ('apli_fili', models.CharField(db_column='apli_fili', max_length=100)),
            ],
            options={
                'db_table': 'agricola_aplicacao_insumos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categorias_produtos_agricolas',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movi_estq_empr', models.CharField(db_column='movi_estq_empr', max_length=100)),
                ('movi_estq_fili', models.CharField(db_column='movi_estq_fili', max_length=100)),
                ('movi_estq_faze', models.CharField(db_column='movi_estq_faze', max_length=100)),
                ('movi_estq_prod', models.CharField(db_column='movi_estq_prod', max_length=100)),
                ('movi_estq_quant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movi_estq_tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('movi_estq_data', models.DateTimeField(auto_now_add=True)),
                ('movi_estq_usua', models.CharField(db_column='usua_movi_estq', max_length=100)),
                ('movi_estq_docu_refe', models.CharField(blank=True, max_length=255, null=True)),
                ('movi_estq_moti', models.CharField(blank=True, max_length=255, null=True)),
                ('movi_estq_cust_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Custo unitário na movimentação (para atualização do custo médio)', max_digits=10, null=True)),
                ('movi_estq_cust_tota', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total na movimentação (para atualização do custo médio)', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'agricola_movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='ProdutoAgro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_codi_agro', models.CharField(max_length=100, unique=True)),
                ('prod_nome_agro', models.CharField(max_length=255)),
                ('prod_cate_agro', models.CharField(db_column='prod_cate_agro', max_length=100)),
                ('prod_unmd_agro', models.CharField(choices=[('kg', 'Kilograma'), ('litro', 'Litro'), ('saco', 'Saco'), ('unidade', 'Unidade'), ('m²', 'Metro Quadrado'), ('ha', 'Hectare')], max_length=50)),
                ('prod_desc_agro', models.TextField(blank=True, help_text='Descrição do produto agrícola', null=True)),
                ('prod_cust_unit', models.DecimalField(decimal_places=2, default=0, help_text='Custo unitário do produto', max_digits=10)),
                ('prod_empr_agro', models.CharField(db_column='empr_prod_agro', max_length=100)),
                ('prod_fili_agro', models.CharField(db_column='fili_prod_agro', max_length=100)),
            ],
            options={
                'db_table': 'agricola_produtos_agro',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talh_empr', models.CharField(db_column='talh_empr', max_length=100)),
                ('talh_fili', models.CharField(db_column='talh_fili', max_length=100)),
                ('talh_faze', models.IntegerField(db_column='talh_faze')),
                ('talh_nome', models.CharField(max_length=255)),
                ('talh_area', models.DecimalField(decimal_places=2, help_text='Área do talhão (pode ser em hectares ou m²)', max_digits=10)),
                ('talh_unmd', models.CharField(default='hectares', help_text='Unidade de medida da área (ex: hectares, m²)', max_length=20)),
            ],
            options={
                'db_table': 'agricola_talhoes',
                'unique_together': {('talh_faze', 'talh_nome', 'talh_empr', 'talh_fili')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_faze', models.CharField(db_column='hist_faze', max_length=100)),
                ('hist_produto', models.CharField(db_column='hist_produto', max_length=100)),
                ('hist_quant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hist_tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('hist_data', models.DateTimeField(auto_now_add=True)),
                ('hist_usuario', models.CharField(db_column='hist_usuario', max_length=100)),
                ('hist_obse', models.TextField(blank=True, null=True)),
                ('hist_empr', models.CharField(db_column='hist_empr', max_length=100)),
                ('hist_fili', models.CharField(db_column='hist_fili', max_length=100)),
                ('hist_movi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Agricola.MovimentacaoEstoque')),
            ],
            options={
                'db_table': 'agricola_historico_movimentacoes',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faze_nome', models.CharField(max_length=255)),
                ('faze_loca', models.CharField(blank=True, max_length=255, null=True)),
                ('faze_empr', models.CharField(db_column='faze_empr', max_length=100)),
                ('faze_fili', models.CharField(db_column='faze_fili', max_length=100)),
                ('faze_area_tota', models.DecimalField(decimal_places=2, default=0, help_text='Área total da fazenda (pode ser em hectares ou m²)', max_digits=10)),
            ],
            options={
                'db_table': 'agricola_fazendas',
                'unique_together': {('faze_nome', 'faze_empr', 'faze_fili')},
            },
        ),
        migrations.CreateModel(
            name='EventoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evnt_tipo_even', models.CharField(choices=[('nascimento', 'Nascimento'), ('vacinacao', 'Vacinação'), ('engorda', 'Engorda'), ('abate', 'Abate'), ('venda', 'Venda')], max_length=50)),
                ('evnt_data_even', models.DateField()),
                ('evnt_cust', models.DecimalField(blank=True, decimal_places=2, help_text='Custo associado a esse evento (se aplicável)', max_digits=10, null=True)),
                ('evnt_desc', models.TextField(blank=True, null=True)),
                ('evnt_usua', models.IntegerField(blank=True, db_column='evnt_usua', null=True)),
                ('evnt_empr', models.IntegerField(db_column='evnt_empr')),
                ('evnt_fili', models.IntegerField(db_column='evnt_fili')),
                ('evnt_anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Agricola.Animal')),
            ],
            options={
                'db_table': 'agricola_eventos_animais',
            },
        ),
        migrations.CreateModel(
            name='EstoqueFazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estq_faze', models.CharField(db_column='estq_faze', max_length=100)),
                ('estq_prod', models.CharField(db_column='estq_prod', max_length=100)),
                ('estq_quant', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade do produto no estoque', max_digits=10)),
                ('estq_cust_medi', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio atualizado com base nas movimentações', max_digits=10)),
                ('estq_empr', models.CharField(db_column='estq_empr', max_length=100)),
                ('estq_fili', models.CharField(db_column='estq_fili', max_length=100)),
            ],
            options={
                'db_table': 'agricola_estoque_fazenda',
                'unique_together': {('estq_empr', 'estq_fili', 'estq_faze', 'estq_prod')},
            },
        ),
    ]
