# Generated by Django 2.2.28 on 2026-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoanimal',
            name='evnt_anim',
            field=models.CharField(db_column='evnt_anim_id', max_length=100),
        ),
    ]
