# Generated by Django 2.2.28 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0002_auto_20260211_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencialControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_empr', models.CharField(max_length=100)),
                ('seq_fili', models.CharField(max_length=100)),
                ('seq_tipo', models.CharField(max_length=30)),
                ('seq_chave_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('seq_atual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'controle_de_sequenciais',
                'unique_together': {('seq_empr', 'seq_fili', 'seq_tipo', 'seq_chave_extra')},
            },
        ),
        migrations.CreateModel(
            name='LoteProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_empr', models.CharField(db_column='lote_empr', max_length=100)),
                ('lote_fili', models.CharField(db_column='lote_fili', max_length=100)),
                ('lote_ident', models.CharField(db_column='lote_ident', help_text='Identificador único do lote', max_length=255)),
                ('lote_prod', models.CharField(db_column='lote_prod', help_text='Produto do lote', max_length=100)),
                ('lote_quant', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade do produto no lote', max_digits=10)),
                ('lote_cust_unit', models.DecimalField(decimal_places=2, default=0, help_text='Custo unitário do lote', max_digits=10)),
                ('lote_valo_vend', models.DecimalField(decimal_places=2, default=0, help_text='Valor de venda unitário do lote', max_digits=10)),
                ('lote_data_emi', models.DateField(blank=True, help_text='Data de emissão do lote', null=True)),
                ('lote_data_venc', models.DateField(blank=True, help_text='Data de vencimento do lote', null=True)),
            ],
            options={
                'db_table': 'produtos_lotes',
                'unique_together': {('lote_empr', 'lote_fili', 'lote_ident', 'lote_prod')},
            },
        ),
    ]
