# Generated by Django 2.2.28 on 2026-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0003_loteprodutos_sequencialcontrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimentacaoestoque',
            unique_together={('movi_estq_empr', 'movi_estq_fili', 'movi_estq_faze', 'id')},
        ),
        migrations.CreateModel(
            name='ParametroAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_empr', models.IntegerField(db_column='para_empr')),
                ('para_fili', models.IntegerField(db_column='para_fili')),
                ('para_chav', models.CharField(db_column='para_chav', max_length=60)),
                ('para_valo', models.TextField(db_column='para_valo')),
            ],
            options={
                'db_table': 'agricola_parametros',
                'unique_together': {('para_empr', 'para_fili', 'para_chav')},
            },
        ),
    ]
