# Generated by Django 2.2.28 on 2026-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0004_auto_20260213_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoagro',
            name='prod_codi_agro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='produtoagro',
            unique_together={('prod_codi_agro', 'prod_empr_agro', 'prod_fili_agro')},
        ),
    ]
