# Generated by Django 2.2.28 on 2026-02-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agricola', '0005_auto_20260213_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='movi_estq_enti',
            field=models.IntegerField(blank=True, db_column='movi_estq_enti', help_text='Entidade (Cliente/Fornecedor) para financeiro', null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='movi_estq_form_paga',
            field=models.CharField(blank=True, help_text='Forma de pagamento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='movi_estq_venc',
            field=models.DateField(blank=True, help_text='Data de vencimento do título financeiro', null=True),
        ),
    ]
