name: Fly Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@v1
        with:
          args: 'deploy'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
